/* Generated by tools/generate_input.py; MIT public interface. */
#ifndef EXEC_INPUT_H
#define EXEC_INPUT_H
#include <exec/tasklease.h>
#define INPUT_VERSION 2
#define INPUT_SOURCE_KEYBOARD 2
#define INPUT_OK 0
#define INPUT_EMPTY 1
#define INPUT_BUSY 2
#define INPUT_BAD_ARGUMENT 3
#define INPUT_INVALID_OWNER 4
#define INPUT_EXHAUSTED 5
#define INPUT_UNSUPPORTED 6
#define INPUT_NO_MEMORY 7
#define INPUT_FREE 0
#define INPUT_ACQUIRING 1
#define INPUT_ACTIVE 2
#define INPUT_RELEASING 3
#define INPUT_EVENT_KEY 1
#define INPUT_EVENT_POINTER 2
#define INPUT_EVENT_BUTTON 3
#define INPUT_EVENT_LOSS 4
#define INPUT_EVENT_CANCEL 5
#define INPUT_TICK_VALID 1
#define INPUT_INJECTED 2
#define INPUT_SHIFT 1
#define INPUT_CONTROL 2
#define INPUT_LEFT 1
#define INPUT_LOSS_RAW 1
#define INPUT_LOSS_NORMALIZED 2
#define INPUT_LOSS_HARDWARE 3
#define INPUT_CANCEL_BREAK 1
#define INPUT_CANCEL_KEY_FILTER 2
#define INPUT_CAPTURE_BREAK 1
#define INPUT_PENDING_DATA 1
#define INPUT_PENDING_LOSS 2
#define INPUT_PENDING_CANCEL 4
#define INPUT_ROUTE_SLOTS 16
#define INPUT_RAW_SLOTS 64
#define INPUT_SOURCE_POINTER 3
#define INPUT_POINTER_ST 1
#define INPUT_POINTER_RAW_SLOTS 32
#define INPUT_LEASE_BYTES 32
#define INPUT_CONFIG_BYTES 32
#define INPUT_EVENT_BYTES 24
struct InputLease {
    struct TaskLease owner;
    ULONG acquisition;
    ULONG route;
    ULONG wakeMask;
    UWORD state;
    UWORD flags;
    ULONG reserved;
};
struct InputConfig {
    UWORD version;
    UWORD source;
    ULONG wakeMask;
    UBYTE filter0Value;
    UBYTE filter0Mask;
    UBYTE filter1Value;
    UBYTE filter1Mask;
    UBYTE filterCount;
    UBYTE flags;
    UWORD reserved;
    UWORD pointerProtocol;
    UWORD pointerPort;
    WORD initialX;
    WORD initialY;
    WORD maxX;
    WORD maxY;
    ULONG reserved2;
};
struct InputEvent {
    ULONG acquisition;
    ULONG route;
    UWORD tick;
    UBYTE kind;
    UBYTE flags;
    UWORD code;
    UWORD qualifiers;
    WORD x;
    WORD y;
    UWORD buttons;
    UWORD reserved;
};
/* Acquire/Release validate registration lifetime. Keep the original lease
 * and signal live until successful Release; only its owner may Take/Release.
 * Take/Pending trust that contract and writable, aligned, bank-contained output
 * storage in production. Full per-use audits require --input-diagnostics.
 * Output buffers are borrowed only for the call; EMPTY leaves all bytes intact.
 * Shared Pending/route users must stop before owner Release. C huge-pointer
 * shape checks always precede narrowing. Route calls still audit until IR3.
 */
UWORD InputAcquire(struct InputLease *lease, const struct InputConfig *config);
UWORD InputCreateRoute(struct InputLease *lease, UWORD flags, ULONG *tag);
UWORD InputPublishRoute(struct InputLease *lease, ULONG tag);
UWORD InputRetireRoute(struct InputLease *lease, ULONG tag);
UWORD InputDiscard(struct InputLease *lease, ULONG tag);
UWORD InputPending(struct InputLease *lease, UWORD *mask);
UWORD InputTake(struct InputLease *lease, struct InputEvent *event);
UWORD InputRelease(struct InputLease *lease);
#endif
