/* Generated by tools/generate_widgets.py. MIT public interface. */
#ifndef EXEC_WIDGET_TYPES_H
#define EXEC_WIDGET_TYPES_H
#include <stdint.h>
#pragma pack(push, 2)
#define WIDGET_OBJECTS 32
#define WIDGET_DEPTH 8
#define WIDGET_TEXT_BYTES 1024
#define WIDGET_LABEL_MAX 63
#define WIDGET_PATCHES 8
#define WIDGET_PACKET_LIMIT 2048
#define WIDGET_CONTEXT_BYTES 4096
#define WIDGET_VERSION 1
#define WIDGET_OK 0
#define WIDGET_BAD_ARGUMENT 1
#define WIDGET_STALE 2
#define WIDGET_EXHAUSTED 3
#define WIDGET_OP_SET 1
#define WIDGET_OP_UPDATE 2
#define WIDGET_OP_READ 3
#define WIDGET_OP_DRAW 4
#define WIDGET_OP_POINTER 5
#define WIDGET_OP_KEY 6
#define WIDGET_OP_CANCEL 7
#define WIDGET_PATCH_STATE 1
#define WIDGET_PATCH_LABEL 2
#define WIDGET_PATCH_HIDDEN 4
#define WIDGET_G_BOX 20
#define WIDGET_G_IBOX 25
#define WIDGET_G_BUTTON 26
#define WIDGET_G_STRING 28
#define WIDGET_FLAG_SELECTABLE 1
#define WIDGET_FLAG_DEFAULT 2
#define WIDGET_FLAG_EXIT 4
#define WIDGET_FLAG_RADIO 16
#define WIDGET_FLAG_LAST 32
#define WIDGET_FLAG_HIDDEN 128
#define WIDGET_STATE_SELECTED 1
#define WIDGET_STATE_DISABLED 8
struct WidgetObject {
    int16_t next;
    int16_t head;
    int16_t tail;
    uint16_t kind;
    uint16_t flags;
    uint16_t state;
    uint32_t spec;
    int16_t x;
    int16_t y;
    int16_t width;
    int16_t height;
};
struct WidgetTree {
    uint16_t version;
    uint16_t count;
    uint16_t textBytes;
    uint16_t background;
    struct WidgetObject objects[WIDGET_OBJECTS];
    uint8_t text[WIDGET_TEXT_BYTES];
};
struct WidgetChange {
    uint16_t object;
    uint16_t mask;
    uint16_t state;
    uint16_t hidden;
    uint16_t offset;
    uint16_t length;
};
struct WidgetUpdate {
    uint32_t epoch;
    uint32_t revision;
    uint16_t count;
    uint16_t textBytes;
    struct WidgetChange changes[WIDGET_PATCHES];
    uint8_t text[WIDGET_TEXT_BYTES];
};
struct WidgetObjectState {
    uint16_t state;
    uint16_t flags;
};
struct WidgetSnapshot {
    uint32_t epoch;
    uint32_t revision;
    uint16_t count;
    int16_t focus;
    struct WidgetObjectState objects[WIDGET_OBJECTS];
};
struct WidgetPacket {
    uint16_t operation;
    uint16_t status;
    uint32_t context;
    uint32_t payload;
    uint16_t bytes;
    uint16_t width;
    uint16_t height;
    int16_t originX;
    int16_t originY;
    int16_t left;
    int16_t top;
    int16_t right;
    int16_t bottom;
    uint16_t index;
    int16_t x;
    int16_t y;
    uint16_t code;
    uint16_t qualifiers;
    uint16_t buttons;
    uint16_t kind;
    int16_t object;
    uint32_t epoch;
    uint32_t revision;
    uint16_t state;
    uint16_t changed;
};
#define WIDGET_OBJECT_SIZE 24
#define WIDGET_TREE_SIZE 1800
#define WIDGET_CHANGE_SIZE 12
#define WIDGET_UPDATE_SIZE 1132
#define WIDGET_OBJECTSTATE_SIZE 4
#define WIDGET_SNAPSHOT_SIZE 140
#define WIDGET_PACKET_SIZE 58
#pragma pack(pop)
#endif
