/* Generated by tools/generate_bitmap.py; do not edit. */
#ifndef EXEC_VBXE_COPY_H
#define EXEC_VBXE_COPY_H
#include <exec/types.h>
#define VBXE_COPY_VERSION 1
struct VbxeSurface { ULONG offset; UWORD pitch, width, height; };
struct VbxeCopy {
    struct VbxeSurface source, destination;
    UWORD sourceX, sourceY, destinationX, destinationY, width, height;
};
#endif
