/* Generated by tools/generate_desktop.py; do not edit. */
#ifndef EXEC_VBXE_SNAPSHOTS_H
#define EXEC_VBXE_SNAPSHOTS_H
#define DESKTOP_SNAPSHOT_0_BASE 327680UL
#define DESKTOP_SNAPSHOT_1_BASE 393216UL
#define DESKTOP_SNAPSHOT_BYTES 65536UL
#endif
