/* Generated by tools/generate_calypsi.py. */
#ifndef EXEC816_ABI_H
#define EXEC816_ABI_H
#include <exec/ports.h>

#define NT_UNKNOWN 0x0UL
#define NT_MSGPORT 0x4UL
#define NT_MESSAGE 0x5UL
#define NT_FREEMSG 0x6UL
#define NT_REPLYMSG 0x7UL
#define PF_ACTION 0x3UL
#define PA_SIGNAL 0x0UL
#define PA_SOFTINT 0x1UL
#define PA_IGNORE 0x2UL
#define NT_TASK 0x1UL
#define TS_INVALID 0x0UL
#define TS_ADDED 0x1UL
#define TS_RUN 0x2UL
#define TS_READY 0x3UL
#define TS_WAIT 0x4UL
#define TS_EXCEPT 0x5UL
#define TS_REMOVED 0x6UL
#define MEMF_ANY 0x0UL
#define MEMF_PUBLIC 0x1UL
#define MEMF_CHIP 0x2UL
#define MEMF_FAST 0x4UL
#define MEMF_BANK0 0x8UL
#define MEMF_UPPER 0x10UL
#define MEMF_LOCAL 0x100UL
#define MEMF_24BITDMA 0x200UL
#define MEMF_KICK 0x400UL
#define MEMF_CLEAR 0x10000UL
#define MEMF_LARGEST 0x20000UL
#define MEMF_REVERSE 0x40000UL
#define MEMF_TOTAL 0x80000UL
#define MEMF_LINEAR 0x100000UL
#define MEMF_NO_EXPUNGE 0x80000000UL
#endif
