/* Generated by tools/generate_aes_server.py; do not edit. */
#ifndef EXEC816_AES_WIRE_H
#define EXEC816_AES_WIRE_H
#include <exec/ports.h>
#define AES_VERSION 1
#define AES_CLIENTS 4
#define AES_CONTEXTS 8
#define AES_QUEUE_DEPTH 16
#define AES_MESSAGE_WORDS 8
#define AES_INTIN_WORDS 16
#define AES_INTOUT_WORDS 7
#define AES_GLOBAL_WORDS 15
#define AES_OP_INIT 10
#define AES_OP_WRITE 12
#define AES_OP_EXIT 19
#define AES_OP_MESAG 23
#define AES_OP_TIMER 24
#define AES_OP_MULTI 25
#define AES_OP_UPDATE 107
#define AES_OK 0
#define AES_MALFORMED 1
#define AES_UNSUPPORTED 2
#define AES_RESOURCE 3
#define AES_IDENTITY 4
#define AES_BUSY 5
#define AES_TIMER_ERROR 6
#define AES_OVERFLOW 7
#define AES_PENDING 8
#define AES_MU_MESAG 16
#define AES_MU_TIMER 32
#define AES_END_UPDATE 0
#define AES_BEG_UPDATE 1
#define AES_END_MCTRL 2
#define AES_BEG_MCTRL 3
#define AES_TRY 256
struct AESRequest {
    struct Message message;
    UWORD version;
    UWORD bytes;
    UWORD operation;
    UWORD status;
    ULONG client;
    ULONG sequence;
    struct Task EXEC_PTR * owner;
    UBYTE ownerPad;
    UBYTE EXEC_PTR * binding;
    UBYTE bindingPad;
    WORD intin[AES_INTIN_WORDS];
    WORD intout[AES_INTOUT_WORDS];
    WORD words[AES_MESSAGE_WORDS];
    WORD global[AES_GLOBAL_WORDS];
};
#define AES_REQUEST_SIZE 132
#define AES_REQUEST_OFFSET_MESSAGE 0
#define AES_REQUEST_OFFSET_VERSION 16
#define AES_REQUEST_OFFSET_BYTES 18
#define AES_REQUEST_OFFSET_OPERATION 20
#define AES_REQUEST_OFFSET_STATUS 22
#define AES_REQUEST_OFFSET_CLIENT 24
#define AES_REQUEST_OFFSET_SEQUENCE 28
#define AES_REQUEST_OFFSET_OWNER 32
#define AES_REQUEST_OFFSET_OWNERPAD 35
#define AES_REQUEST_OFFSET_BINDING 36
#define AES_REQUEST_OFFSET_BINDINGPAD 39
#define AES_REQUEST_OFFSET_INTIN 40
#define AES_REQUEST_OFFSET_INTOUT 72
#define AES_REQUEST_OFFSET_WORDS 86
#define AES_REQUEST_OFFSET_GLOBAL 102
#endif
