/* Generated by tools/generate_aes_server.py; do not edit. */
#ifndef EXEC816_AES_WIRE_H
#define EXEC816_AES_WIRE_H
#include <exec/ports.h>
#define AES_VERSION 2
#define AES_CLIENTS 4
#define AES_CONTEXTS 8
#define AES_QUEUE_DEPTH 16
#define AES_MESSAGE_WORDS 8
#define AES_INTIN_WORDS 16
#define AES_INTOUT_WORDS 7
#define AES_GLOBAL_WORDS 15
#define AES_OP_INIT 10
#define AES_OP_WRITE 12
#define AES_OP_EXIT 19
#define AES_OP_MESAG 23
#define AES_OP_TIMER 24
#define AES_OP_MULTI 25
#define AES_OP_UPDATE 107
#define AES_OK 0
#define AES_MALFORMED 1
#define AES_UNSUPPORTED 2
#define AES_RESOURCE 3
#define AES_IDENTITY 4
#define AES_BUSY 5
#define AES_TIMER_ERROR 6
#define AES_OVERFLOW 7
#define AES_PENDING 8
#define AES_MU_MESAG 16
#define AES_MU_TIMER 32
#define AES_END_UPDATE 0
#define AES_BEG_UPDATE 1
#define AES_END_MCTRL 2
#define AES_BEG_MCTRL 3
#define AES_TRY 256
#define AES_ENDPOINT_UNPUBLISHED 0
#define AES_ENDPOINT_ACCEPTING 1
#define AES_ENDPOINT_CLOSING 2
#define AES_ENDPOINT_RETIRED 3
struct AESDelivery {
    struct Message message;
    WORD words[AES_MESSAGE_WORDS];
};
#define AES_DELIVERY_SIZE 32
#define AES_DELIVERY_OFFSET_MESSAGE 0
#define AES_DELIVERY_OFFSET_WORDS 16
struct AESEndpoint {
    ULONG id;
    WORD gemId;
    UWORD state;
    struct Task EXEC_PTR * owner;
    UBYTE ownerPad;
    struct MsgPort EXEC_PTR * port;
    UBYTE portPad;
    struct AESDelivery EXEC_PTR * records;
    UBYTE recordsPad;
    UWORD holds;
    UWORD freeRecords;
};
#define AES_ENDPOINT_SIZE 24
#define AES_ENDPOINT_OFFSET_ID 0
#define AES_ENDPOINT_OFFSET_GEMID 4
#define AES_ENDPOINT_OFFSET_STATE 6
#define AES_ENDPOINT_OFFSET_OWNER 8
#define AES_ENDPOINT_OFFSET_OWNERPAD 11
#define AES_ENDPOINT_OFFSET_PORT 12
#define AES_ENDPOINT_OFFSET_PORTPAD 15
#define AES_ENDPOINT_OFFSET_RECORDS 16
#define AES_ENDPOINT_OFFSET_RECORDSPAD 19
#define AES_ENDPOINT_OFFSET_HOLDS 20
#define AES_ENDPOINT_OFFSET_FREERECORDS 22
struct AESDirectory {
    struct Task EXEC_PTR * owner;
    UBYTE ownerPad;
    ULONG mask;
    UWORD changed;
    struct AESEndpoint endpoints[AES_CLIENTS];
};
#define AES_DIRECTORY_SIZE 106
#define AES_DIRECTORY_OFFSET_OWNER 0
#define AES_DIRECTORY_OFFSET_OWNERPAD 3
#define AES_DIRECTORY_OFFSET_MASK 4
#define AES_DIRECTORY_OFFSET_CHANGED 8
#define AES_DIRECTORY_OFFSET_ENDPOINTS 10
struct AESRequest {
    struct Message message;
    UWORD version;
    UWORD bytes;
    UWORD operation;
    UWORD status;
    ULONG client;
    ULONG sequence;
    struct Task EXEC_PTR * owner;
    UBYTE ownerPad;
    UBYTE EXEC_PTR * binding;
    UBYTE bindingPad;
    WORD intin[AES_INTIN_WORDS];
    WORD intout[AES_INTOUT_WORDS];
    WORD words[AES_MESSAGE_WORDS];
    WORD global[AES_GLOBAL_WORDS];
    struct AESDirectory EXEC_PTR * directory;
    UBYTE directoryPad;
    struct MsgPort EXEC_PTR * receiving;
    UBYTE receivingPad;
    struct AESDelivery EXEC_PTR * records;
    UBYTE recordsPad;
};
#define AES_REQUEST_SIZE 144
#define AES_REQUEST_OFFSET_MESSAGE 0
#define AES_REQUEST_OFFSET_VERSION 16
#define AES_REQUEST_OFFSET_BYTES 18
#define AES_REQUEST_OFFSET_OPERATION 20
#define AES_REQUEST_OFFSET_STATUS 22
#define AES_REQUEST_OFFSET_CLIENT 24
#define AES_REQUEST_OFFSET_SEQUENCE 28
#define AES_REQUEST_OFFSET_OWNER 32
#define AES_REQUEST_OFFSET_OWNERPAD 35
#define AES_REQUEST_OFFSET_BINDING 36
#define AES_REQUEST_OFFSET_BINDINGPAD 39
#define AES_REQUEST_OFFSET_INTIN 40
#define AES_REQUEST_OFFSET_INTOUT 72
#define AES_REQUEST_OFFSET_WORDS 86
#define AES_REQUEST_OFFSET_GLOBAL 102
#define AES_REQUEST_OFFSET_DIRECTORY 132
#define AES_REQUEST_OFFSET_DIRECTORYPAD 135
#define AES_REQUEST_OFFSET_RECEIVING 136
#define AES_REQUEST_OFFSET_RECEIVINGPAD 139
#define AES_REQUEST_OFFSET_RECORDS 140
#define AES_REQUEST_OFFSET_RECORDSPAD 143
#endif
