/* Generated by tools/generate_aes_server.py; do not edit. */
#ifndef EXEC816_GEM_CONSTANTS_H
#define EXEC816_GEM_CONSTANTS_H
#define NAME 1
#define CLOSER 2
#define MOVER 8
#define WF_KIND 1
#define WF_NAME 2
#define WF_WXYWH 4
#define WF_CXYWH 5
#define WF_TOP 10
#define WF_FIRSTXYWH 11
#define WF_NEXTXYWH 12
#define WC_BORDER 0
#define WC_WORK 1
#define WM_REDRAW 20
#define WM_TOPPED 21
#define WM_MOVED 28
#define WM_CLOSED 22
#define WF_WORKXYWH WF_WXYWH
#define WF_CURRXYWH WF_CXYWH
#endif
