/* Generated by tools/generate_aes_server.py; do not edit. */
#ifndef EXEC816_GEM_CONSTANTS_H
#define EXEC816_GEM_CONSTANTS_H
#define NAME 1
#define CLOSER 2
#define MOVER 8
#define WF_KIND 1
#define WF_NAME 2
#define WF_WXYWH 4
#define WF_CXYWH 5
#define WF_TOP 10
#define WF_FIRSTXYWH 11
#define WF_NEXTXYWH 12
#define WC_BORDER 0
#define WC_WORK 1
#define WM_REDRAW 20
#define WM_TOPPED 21
#define WM_MOVED 28
#define WM_CLOSED 22
#define MU_KEYBD 1
#define MU_BUTTON 2
#define MU_M1 4
#define MU_M2 8
#define MU_MESAG 16
#define MU_TIMER 32
#define MN_SELECTED 10
#define SIZER 32
#define UPARROW 64
#define DNARROW 128
#define VSLIDE 256
#define WF_VSLIDE 9
#define WF_VSLSIZE 16
#define WM_ARROWED 24
#define WM_VSLID 26
#define WM_SIZED 27
#define WA_UPPAGE 0
#define WA_DNPAGE 1
#define WA_UPLINE 2
#define WA_DNLINE 3
#define WF_VSLSIZ 16
#define WF_WORKXYWH WF_WXYWH
#define WF_CURRXYWH WF_CXYWH
#endif
