/* Generated by tools/generate_vdi_client.py; do not edit. */
#ifndef EXEC816_VDI_UNIT_H
#define EXEC816_VDI_UNIT_H
#include <stdint.h>
#define EXEC_VDI_PHYSICAL 1
#define EXEC_VDI_VIRTUAL 2
#define EXEC_VDI_WIDTH 640
#define EXEC_VDI_HEIGHT 240
#define EXEC_VDI_FONT_WIDTH 8
#define EXEC_VDI_FONT_HEIGHT 8
#define EXEC_VDI_FONT_TOP 6
#define EXEC_VDI_TEXT_CHUNK 32
#define EXEC_VDI_STRIP_ROWS 16
struct ExecVDIUnit {
    uint16_t operation;
    uint16_t textColor;
    uint16_t fillColor;
    uint16_t left;
    uint16_t top;
    uint16_t right;
    uint16_t bottom;
    int16_t x;
    int16_t y;
    uint16_t count;
    const int16_t * glyphs;
};
void GemVdiPaint(void *context);
#endif
