#include "../../examples/gem-browser/browser.h"
#include <stddef.h>
__attribute__((section("exec_layout")))
const UWORD BrowserLayout[]={sizeof(struct Browser),
    offsetof(struct Browser,ready),
    offsetof(struct Browser,work),
    offsetof(struct Browser,tree),
    offsetof(struct Browser,menu),
    offsetof(struct Browser,path),
    offsetof(struct Browser,status),
    offsetof(struct Browser,target),
    offsetof(struct Browser,entries),
    offsetof(struct Browser,count),
    offsetof(struct Browser,first),
    offsetof(struct Browser,visible),
    offsetof(struct Browser,selected),
    offsetof(struct Browser,down),
    offsetof(struct Browser,armed),
    offsetof(struct Browser,truncated),
    offsetof(struct Browser,launches),
    offsetof(struct Browser,paints),
    offsetof(struct Browser,child),
    offsetof(struct Browser,result),
    offsetof(struct Browser,bar),
    offsetof(struct Browser,menuInstalled),
    offsetof(struct Browser,menuEnabled),
};
