/* Generated emitted-layout probe. */
#include <stddef.h>
#include <exec/widget-types.h>
__attribute__((section("exec_layout"))) const unsigned short __exec_layout[] = {
    sizeof(struct WidgetObject),
    sizeof(struct WidgetTree),
    sizeof(struct WidgetChange),
    sizeof(struct WidgetUpdate),
    sizeof(struct WidgetObjectState),
    sizeof(struct WidgetSnapshot),
    sizeof(struct WidgetDamageRect),
    sizeof(struct WidgetPacket),
    offsetof(struct WidgetObject, next),
    offsetof(struct WidgetObject, head),
    offsetof(struct WidgetObject, tail),
    offsetof(struct WidgetObject, kind),
    offsetof(struct WidgetObject, flags),
    offsetof(struct WidgetObject, state),
    offsetof(struct WidgetObject, spec),
    offsetof(struct WidgetObject, x),
    offsetof(struct WidgetObject, y),
    offsetof(struct WidgetObject, width),
    offsetof(struct WidgetObject, height),
    offsetof(struct WidgetTree, version),
    offsetof(struct WidgetTree, count),
    offsetof(struct WidgetTree, textBytes),
    offsetof(struct WidgetTree, background),
    offsetof(struct WidgetTree, objects),
    offsetof(struct WidgetTree, text),
    offsetof(struct WidgetChange, object),
    offsetof(struct WidgetChange, mask),
    offsetof(struct WidgetChange, state),
    offsetof(struct WidgetChange, hidden),
    offsetof(struct WidgetChange, offset),
    offsetof(struct WidgetChange, length),
    offsetof(struct WidgetUpdate, epoch),
    offsetof(struct WidgetUpdate, revision),
    offsetof(struct WidgetUpdate, count),
    offsetof(struct WidgetUpdate, textBytes),
    offsetof(struct WidgetUpdate, changes),
    offsetof(struct WidgetUpdate, text),
    offsetof(struct WidgetObjectState, state),
    offsetof(struct WidgetObjectState, flags),
    offsetof(struct WidgetSnapshot, epoch),
    offsetof(struct WidgetSnapshot, revision),
    offsetof(struct WidgetSnapshot, count),
    offsetof(struct WidgetSnapshot, focus),
    offsetof(struct WidgetSnapshot, objects),
    offsetof(struct WidgetDamageRect, left),
    offsetof(struct WidgetDamageRect, top),
    offsetof(struct WidgetDamageRect, right),
    offsetof(struct WidgetDamageRect, bottom),
    offsetof(struct WidgetPacket, operation),
    offsetof(struct WidgetPacket, status),
    offsetof(struct WidgetPacket, context),
    offsetof(struct WidgetPacket, payload),
    offsetof(struct WidgetPacket, bytes),
    offsetof(struct WidgetPacket, width),
    offsetof(struct WidgetPacket, height),
    offsetof(struct WidgetPacket, originX),
    offsetof(struct WidgetPacket, originY),
    offsetof(struct WidgetPacket, left),
    offsetof(struct WidgetPacket, top),
    offsetof(struct WidgetPacket, right),
    offsetof(struct WidgetPacket, bottom),
    offsetof(struct WidgetPacket, index),
    offsetof(struct WidgetPacket, x),
    offsetof(struct WidgetPacket, y),
    offsetof(struct WidgetPacket, code),
    offsetof(struct WidgetPacket, qualifiers),
    offsetof(struct WidgetPacket, buttons),
    offsetof(struct WidgetPacket, kind),
    offsetof(struct WidgetPacket, object),
    offsetof(struct WidgetPacket, epoch),
    offsetof(struct WidgetPacket, revision),
    offsetof(struct WidgetPacket, state),
    offsetof(struct WidgetPacket, changed),
    offsetof(struct WidgetPacket, damageCount),
    offsetof(struct WidgetPacket, damage),
};
