/* Generated by tools/generate_timer_device.py; do not edit. */
#ifndef DEVICES_TIMER_H
#define DEVICES_TIMER_H
#include <exec/io.h>
#define UNIT_VBLANK (1)
#define TR_ADDREQUEST (9)
#define TD_READCLOCK (10)
#define TD_WAITUNTIL (11)
#define TIMERERR_QUEUEFULL (1)
#define TIMERERR_OVERFLOW (2)
#define TIMERERR_CLOCK (3)
#define TIMERERR_BADTIME (4)

struct TimerRequest {
    struct IORequest tr_Request;
    ULONG seconds;
    ULONG microseconds;
};

struct TimerClockRequest {
    struct IORequest tc_Request;
    ULONG ticks_hi;
    ULONG ticks_lo;
    ULONG ticks_per_second;
};
#endif
