/* Generated by tools/generate_gem_interactive.py. */
#ifndef UI_ABI_H
#define UI_ABI_H
#include <proto/exec.h>
#define UI_VERSION 1
#define UI_START 1
#define UI_PROGRESS 2
#define UI_STOP 3
#define UI_DISK_DONE 4
#define UI_EXIT 5
#define UI_CONTROL_BYTES 32
struct UiControl {
    struct Message message;
    UWORD version;
    UWORD command;
    ULONG session;
    ULONG value;
    UWORD result;
    UWORD reserved;
};
#define UI_BOOT_BYTES 48
struct UiBoot {
    UWORD version;
    UWORD ready;
    ULONG session;
    struct Task EXEC_PTR * root;
    UBYTE pad0;
    struct Task EXEC_PTR * app;
    UBYTE pad1;
    struct MsgPort EXEC_PTR * rootPort;
    UBYTE pad2;
    struct MsgPort EXEC_PTR * appPort;
    UBYTE pad3;
    struct TaskLease appLease;
    ULONG rootMask;
    UWORD exitRequested;
    UWORD retired;
    UWORD result;
    UWORD diskDone;
};
#endif
