/* Generated by tools/generate_aes_server.py; do not edit. */
#include <exec816/aes.h>
__attribute__((section("exec_layout")))
const UWORD AESLayout[] = {
    sizeof(WORD),
    sizeof(void *),
    sizeof(void EXEC_PTR *),
    sizeof(struct AESRequest),
    offsetof(struct AESRequest, message),
    offsetof(struct AESRequest, version),
    offsetof(struct AESRequest, bytes),
    offsetof(struct AESRequest, operation),
    offsetof(struct AESRequest, status),
    offsetof(struct AESRequest, client),
    offsetof(struct AESRequest, sequence),
    offsetof(struct AESRequest, owner),
    offsetof(struct AESRequest, ownerPad),
    offsetof(struct AESRequest, binding),
    offsetof(struct AESRequest, bindingPad),
    offsetof(struct AESRequest, intin),
    offsetof(struct AESRequest, intout),
    offsetof(struct AESRequest, words),
    offsetof(struct AESRequest, global),
    sizeof(struct ExecAESContext),
    offsetof(struct ExecAESContext, request),
};
