#include <exec/input.h>
__attribute__((section("exec_layout")))
const unsigned short __exec_layout[] = {
    sizeof(struct InputLease),
    offsetof(struct InputLease, owner),
    offsetof(struct InputLease, acquisition),
    offsetof(struct InputLease, route),
    offsetof(struct InputLease, wakeMask),
    offsetof(struct InputLease, state),
    offsetof(struct InputLease, flags),
    offsetof(struct InputLease, reserved),
    sizeof(struct InputConfig),
    offsetof(struct InputConfig, version),
    offsetof(struct InputConfig, source),
    offsetof(struct InputConfig, wakeMask),
    offsetof(struct InputConfig, filter0Value),
    offsetof(struct InputConfig, filter0Mask),
    offsetof(struct InputConfig, filter1Value),
    offsetof(struct InputConfig, filter1Mask),
    offsetof(struct InputConfig, filterCount),
    offsetof(struct InputConfig, flags),
    offsetof(struct InputConfig, reserved),
    offsetof(struct InputConfig, pointerProtocol),
    offsetof(struct InputConfig, pointerPort),
    offsetof(struct InputConfig, initialX),
    offsetof(struct InputConfig, initialY),
    offsetof(struct InputConfig, maxX),
    offsetof(struct InputConfig, maxY),
    offsetof(struct InputConfig, reserved2),
    sizeof(struct InputEvent),
    offsetof(struct InputEvent, acquisition),
    offsetof(struct InputEvent, route),
    offsetof(struct InputEvent, tick),
    offsetof(struct InputEvent, kind),
    offsetof(struct InputEvent, flags),
    offsetof(struct InputEvent, code),
    offsetof(struct InputEvent, qualifiers),
    offsetof(struct InputEvent, x),
    offsetof(struct InputEvent, y),
    offsetof(struct InputEvent, buttons),
    offsetof(struct InputEvent, motionInfo),
};
