/* Generated by tools/generate_vdi_client.py; do not edit. */
#ifndef EXEC816_VDI_PRIVATE_H
#define EXEC816_VDI_PRIVATE_H
#include <exec816/aes.h>
#include <exec/display.h>
#include <exec816/vdi-unit.h>
struct ExecVDIWorkstation {
    struct DisplayGrant grant;
    BYTE signal;
    UBYTE clipped;
    WORD handle;
    WORD fillColor;
    WORD textColor;
    WORD clip[4];
    WORD control[12];
    WORD intin[32];
    WORD ptsin[4];
    WORD intout[45];
    WORD ptsout[12];
    struct ExecVDIUnit unit;
};
BOOL ExecVDIClose(struct ExecAESContext *context);
#endif
