/* Generated by tools/generate_gem_vdi.py. */
#ifndef GEM_ABI_H
#define GEM_ABI_H
#include <proto/exec.h>
#define GEM_VERSION 1
#define GEM_MAX_POINT_PAIRS 16
#define GEM_MAX_INT_WORDS 64
#define GEM_LIMIT_COMMANDS 16
#define GEM_LIMIT_PAYLOAD_BYTES 2048
#define GEM_LIMIT_PACKET_BYTES 2204
#define GEM_LIMIT_REPLY_WORDS 57
#define GEM_LIMIT_OUTSTANDING_PER_CLIENT 1
#define GEM_LIMIT_CLIENTS 1
#define GEM_OP_OPEN 1
#define GEM_OP_SUBMIT 2
#define GEM_OP_CLOSE 3
#define GEM_OP_STOP 4
#define GEM_OK 0
#define GEM_UNSUPPORTED 1
#define GEM_BAD_PACKET 2
#define GEM_BAD_SESSION 3
#define GEM_BUSY 4
#define GEM_NO_MEMORY 5
#define GEM_DEVICE_FAULT 6
#define GEM_STOPPING 7
#define GEM_EXHAUSTED 8
#define GEM_REQUEST_BYTES 156
struct GemRequest {
    struct Message message;
    UWORD version;
    UWORD total_bytes;
    UWORD operation;
    UWORD flags;
    ULONG session;
    ULONG sequence;
    UWORD command_count;
    UWORD result;
    UWORD completed_count;
    UWORD reserved;
    UWORD reply_words;
    WORD reply[57];
};
#define GEM_COMMAND_BYTES 12
struct GemCommand {
    UWORD opcode;
    UWORD subopcode;
    UWORD point_pairs;
    UWORD int_words;
    UWORD points_offset;
    UWORD ints_offset;
};
UWORD GemValidateCommand(UWORD operation, const struct GemCommand *command, const WORD *ints);
UWORD GemCommandReplyWords(UWORD opcode);
#endif
