/* Generated by tools/generate_gem_vdi.py. */
#include "gem-abi.h"
UWORD GemValidateCommand(UWORD operation, const struct GemCommand *c, const WORD *ints)
{
    UWORD i;
    switch (c->opcode) {
    case 1:
        if (operation != GEM_OP_OPEN || c->subopcode != 0 ||
            c->point_pairs < 0 || c->point_pairs > 0 ||
            c->int_words < 11 || c->int_words > 11) return GEM_UNSUPPORTED;
        if (ints[0] != 1) return GEM_UNSUPPORTED;
        if (ints[1] != 1) return GEM_UNSUPPORTED;
        if (ints[2] != 1) return GEM_UNSUPPORTED;
        if (ints[3] != 1) return GEM_UNSUPPORTED;
        if (ints[4] != 1) return GEM_UNSUPPORTED;
        if (ints[5] != 1) return GEM_UNSUPPORTED;
        if (ints[6] != 1) return GEM_UNSUPPORTED;
        if (ints[7] != 1) return GEM_UNSUPPORTED;
        if (ints[8] != 1) return GEM_UNSUPPORTED;
        if (ints[9] != 1) return GEM_UNSUPPORTED;
        if (ints[10] != 2) return GEM_UNSUPPORTED;
        return GEM_OK;
    case 2:
        if (operation != GEM_OP_CLOSE || c->subopcode != 0 ||
            c->point_pairs < 0 || c->point_pairs > 0 ||
            c->int_words < 0 || c->int_words > 0) return GEM_UNSUPPORTED;
        return GEM_OK;
    case 3:
        if (operation != GEM_OP_SUBMIT || c->subopcode != 0 ||
            c->point_pairs < 0 || c->point_pairs > 0 ||
            c->int_words < 0 || c->int_words > 0) return GEM_UNSUPPORTED;
        return GEM_OK;
    case 4:
        if (operation != GEM_OP_SUBMIT || c->subopcode != 0 ||
            c->point_pairs < 0 || c->point_pairs > 0 ||
            c->int_words < 0 || c->int_words > 0) return GEM_UNSUPPORTED;
        return GEM_OK;
    case 6:
        if (operation != GEM_OP_SUBMIT || c->subopcode != 0 ||
            c->point_pairs < 2 || c->point_pairs > 16 ||
            c->int_words < 0 || c->int_words > 0) return GEM_UNSUPPORTED;
        return GEM_OK;
    case 8:
        if (operation != GEM_OP_SUBMIT || c->subopcode != 0 ||
            c->point_pairs < 1 || c->point_pairs > 1 ||
            c->int_words < 0 || c->int_words > 64) return GEM_UNSUPPORTED;
        for (i = 0; i < c->int_words; ++i)
            if (ints[i] < 0 || ints[i] > 255) return GEM_UNSUPPORTED;
        return GEM_OK;
    case 11:
        if (operation != GEM_OP_SUBMIT || c->subopcode != 1 ||
            c->point_pairs < 2 || c->point_pairs > 2 ||
            c->int_words < 0 || c->int_words > 0) return GEM_UNSUPPORTED;
        return GEM_OK;
    case 17:
        if (operation != GEM_OP_SUBMIT || c->subopcode != 0 ||
            c->point_pairs < 0 || c->point_pairs > 0 ||
            c->int_words < 1 || c->int_words > 1) return GEM_UNSUPPORTED;
        if (ints[0] < 0 || ints[0] > 15) return GEM_UNSUPPORTED;
        return GEM_OK;
    case 22:
        if (operation != GEM_OP_SUBMIT || c->subopcode != 0 ||
            c->point_pairs < 0 || c->point_pairs > 0 ||
            c->int_words < 1 || c->int_words > 1) return GEM_UNSUPPORTED;
        if (ints[0] < 0 || ints[0] > 15) return GEM_UNSUPPORTED;
        return GEM_OK;
    case 23:
        if (operation != GEM_OP_SUBMIT || c->subopcode != 0 ||
            c->point_pairs < 0 || c->point_pairs > 0 ||
            c->int_words < 1 || c->int_words > 1) return GEM_UNSUPPORTED;
        if (ints[0] != 1) return GEM_UNSUPPORTED;
        return GEM_OK;
    case 25:
        if (operation != GEM_OP_SUBMIT || c->subopcode != 0 ||
            c->point_pairs < 0 || c->point_pairs > 0 ||
            c->int_words < 1 || c->int_words > 1) return GEM_UNSUPPORTED;
        if (ints[0] < 0 || ints[0] > 15) return GEM_UNSUPPORTED;
        return GEM_OK;
    case 32:
        if (operation != GEM_OP_SUBMIT || c->subopcode != 0 ||
            c->point_pairs < 0 || c->point_pairs > 0 ||
            c->int_words < 1 || c->int_words > 1) return GEM_UNSUPPORTED;
        if (ints[0] != 1) return GEM_UNSUPPORTED;
        return GEM_OK;
    case 129:
        if (operation != GEM_OP_SUBMIT || c->subopcode != 0 ||
            c->point_pairs < 2 || c->point_pairs > 2 ||
            c->int_words < 1 || c->int_words > 1) return GEM_UNSUPPORTED;
        if (ints[0] < 0 || ints[0] > 1) return GEM_UNSUPPORTED;
        return GEM_OK;
    default: return GEM_UNSUPPORTED;
    }
}
UWORD GemCommandReplyWords(UWORD opcode)
{
    switch (opcode) {
    case 1: return 57;
    case 17: return 1;
    case 22: return 1;
    case 23: return 1;
    case 25: return 1;
    case 32: return 1;
    default: return 0;
    }
}
