"""Resolve the hosted adapter state from the platform profile and ABI offsets."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def resident_addresses(profile=None):
    """Resolve the near adapter arena and its linker segment offsets."""
    profile = profile or json.loads((ROOT/'platform/altirraos/memory-4m.json').read_text())
    region = next(r for r in profile['regions'] if r['name'] == 'resident')
    base, size = region['address'], region['size']
    offsets = profile['resident_segments']
    names = ('BOOT','NMI','IRQ','GATE','CONSOLE','STUBS','FAULT','EXIT','COOP_BOOT')
    if (type(base) is not int or base % 256 or size != 4096 or
            not 0 <= base < base+size <= 0x8000 or
            set(offsets) != set(names) or
            any(type(v) is not int or not 0 <= v < size for v in offsets.values()) or
            [offsets[n] for n in names] != sorted(set(offsets.values())) or offsets['BOOT'] != 0):
        raise ValueError('Invalid resident adapter layout')
    return dict(RESIDENT_BASE=base, RESIDENT_BYTES=size,
                **{'RESIDENT_'+name:base+offsets[name] for name in names})


def hosted_config(profile=None):
    c = resident_addresses(profile)
    text = '# Generated by tools/generate_exec_abi.py; do not edit.\n'
    text += f'MEMORY {{ RAM: start = ${c["RESIDENT_BASE"]:04x}, size = ${c["RESIDENT_BYTES"]:04x}, file = %O, fill = yes; }}\nSEGMENTS {{\n'
    for name,address in list(c.items())[2:]:
        name = name.removeprefix('RESIDENT_')
        optional = ', optional = yes' if name in ('GATE','STUBS','COOP_BOOT') else ''
        text += f'    {name}: load = RAM, type = ro, start = ${address:04x}{optional};\n'
    return text+'}\n'


def diagnostic_addresses(profile=None):
    """Test-only borrowing; these bytes are not production reservations."""
    profile = profile or json.loads((ROOT/'platform/altirraos/memory-4m.json').read_text())
    result = {}
    for r in profile['test_scratch']:
        key = 'TEST_'+r['name'].upper().replace('-','_')
        if (key in result or type(r['address']) is not int or type(r['size']) is not int or
                not 0 <= r['address'] < r['address']+r['size'] <= 0x8000):
            raise ValueError('Invalid diagnostic scratch')
        result.update({key:r['address'],key+'_BYTES':r['size']})
    return result


def probe_address(slot):
    if not 0 <= slot < 8:
        raise ValueError('Register capture supports eight Tasks')
    return PROBE0+slot*32 if slot < 4 else TEST_REGISTER_EXTENSION+(slot-4)*32


def direct_pages(profile=None):
    """Resolve the physical DP map independently of the native field ABI."""
    profile = profile or json.loads((ROOT/'platform/altirraos/memory-4m.json').read_text())
    dp = profile['direct_pages']
    if (dp['task_stride'] != 256 or any(type(dp[k]) is not int or
            not 0 <= dp[k] <= 0xff00 or dp[k] % 256 for k in ('kernel','task_base'))):
        raise ValueError('Invalid aligned direct-page layout')
    return dict(KERNEL_DP=dp['kernel'], TASK0_DP=dp['task_base'],
                TASK1_DP=dp['task_base']+dp['task_stride'])


def stack_addresses(profile=None):
    """Resolve fixed bootstrap stacks; per-Task sizes use the capacity map."""
    profile = profile or json.loads((ROOT/'platform/altirraos/memory-4m.json').read_text())
    regions = {r['name']:r for r in profile['regions']}
    result = {}
    for owner in ('task0','task1','kernel'):
        region = regions[owner+'-stack']
        base, size = region['address']+16, region['size']-32
        if base % 16 or size != 1536 or not 16 <= base < base+size+16 <= 65536:
            raise ValueError('Invalid bootstrap stack reservation')
        result.update({owner.upper()+'_STACK_'+key:value for key,value in
                       dict(BASE=base,FLOOR=base+256,TOP=base+size-2,CEILING=base+size-1).items()})
    return result


def addresses(profile=None):
    profile = profile or json.loads((ROOT/'platform/altirraos/memory-4m.json').read_text())
    region = next(r for r in profile['regions'] if r['name'] == 'state')
    offsets = json.loads((ROOT/'abi/exec816-v1.json').read_text())['state_offsets']
    if region['size'] != 256 or any(not 0 <= value < 256 for value in offsets.values()):
        raise ValueError('Invalid adapter state page')
    return dict(STATE=region['address'], STATE_BYTES=region['size'],
                **{name:region['address']+offset for name,offset in offsets.items()})


# Host observers use the same single supported placement as generated bindings.
globals().update(addresses())
globals().update(direct_pages())
globals().update(stack_addresses())
globals().update(resident_addresses())
globals().update(diagnostic_addresses())
STOPPED = f'dw(${STATUS:04x})!=$ffff'
