"""Package the fixed C GUI image as a build-matched system-disk component."""
import binascii
import hashlib
import json
import struct
from pathlib import Path

from native_program import ROOT, require


def prepare(foreign, output):
    segments = foreign['segments']
    payload = b''.join(bytes(s['bytes']) for s in segments)
    layout = [(s['address'], len(s['bytes'])) for s in segments]
    identity = hashlib.sha256(json.dumps(dict(segments=layout,
        zero_fill=foreign['zero_fill']), sort_keys=True).encode()+payload).digest()[:16]
    checksum = binascii.crc_hqx(payload, 0xffff)
    header = struct.pack('<4sHHI16sHH', b'G816', 1, len(segments), len(payload),
                         identity, checksum, 0)
    path = output/'GEMSYS.BIN'
    path.write_bytes(header+payload)
    # The loader's destinations come from this link, never from the disk file.
    lines = ['; Generated by tools/gem_component.py.',
             'BYTE ARRAY componentHeader=['+' '.join(str(n) for n in header)+']',
             'PUBLIC CONST SEGMENTS='+str(len(segments)),
             'ADDRESS ARRAY destinations=['+' '.join(f'${a:x}' for a,_ in layout)+']',
             'LONGCARD ARRAY lengths=['+' '.join(str(n) for _,n in layout)+']',
             f'CONST CHECKSUM=${checksum:x}',
             'CARD ARRAY crcTable=[']
    table = [binascii.crc_hqx(bytes([n]), 0) for n in range(256)]
    for start in range(0, 256, 8):
        lines.append('  '+' '.join(f'${n:04x}' for n in table[start:start+8]))
    lines += [']', '']
    include = output/'gem-component.inc'
    include.write_text('\n'.join(lines))
    source = (ROOT/'lib/aes/gemcomponent.act').read_text().replace(
        '"gem-component.inc"', '"'+str(include.resolve())+'"')
    (output/'gemcomponent.act').write_text(source)
    for segment in segments:
        require(segment['address'] >= 0x10000, 'GUI component must use upper RAM')
        segment['deferred'] = True
    record = dict(file=path.name, bytes=len(header)+len(payload),
                  sha256=hashlib.sha256(header+payload).hexdigest(),
                  identity=identity.hex(), crc16=checksum, segments=layout,
                  zero_fill=foreign['zero_fill'])
    foreign['provenance']['disk_component'] = record
    (output/'c-image.json').write_text(json.dumps(foreign, indent=2)+'\n')
    return record
