#!/usr/bin/env python3
"""Generate the single current Exec memory API and native layouts."""
from library_paths import read_source
import argparse
import json
from pathlib import Path

from generate_memory import ROOT, integer, require

ABI_PATH = ROOT/'abi/heap-v1.json'
ABI = json.loads(ABI_PATH.read_text())
HEADER = '; Generated by tools/generate_heap.py; do not edit.\n'
RESULTS = {0:'None',3:'Some(NativeResult(A16X8ZeroExtended))',4:'Some(NativeResult(A16X16))'}
WIDTHS = {'EXECLISTS.Node':(11,1),'MemChunk POINTER':(3,1),'BYTE POINTER':(3,1),
          'BYTE':(1,1),'CARD':(2,2),'LONGCARD':(4,2)}
DECLARATIONS = {
    'AllocMem':'BYTE POINTER FUNC AllocMem(LONGCARD byteSize LONGCARD attributes)',
    'FreeMem':'PROC FreeMem(BYTE POINTER memoryBlock LONGCARD byteSize)',
    'AllocVec':'BYTE POINTER FUNC AllocVec(LONGCARD byteSize LONGCARD attributes)',
    'FreeVec':'PROC FreeVec(BYTE POINTER memoryBlock)',
    'AvailMem':'LONGCARD FUNC AvailMem(LONGCARD attributes)',
    'TypeOfMem':'LONGCARD FUNC TypeOfMem(BYTE POINTER address)',
    'Allocate':'BYTE POINTER FUNC Allocate(MemHeader POINTER memHeader LONGCARD byteSize)',
    'Deallocate':'PROC Deallocate(MemHeader POINTER memHeader BYTE POINTER memoryBlock LONGCARD byteSize)',
}
CLASSIC_FLAGS = {'ANY':0,'PUBLIC':1,'CHIP':2,'FAST':4,'LOCAL':256,'24BITDMA':512,
                 'KICK':1024,'CLEAR':65536,'LARGEST':131072,'REVERSE':262144,
                 'TOTAL':524288,'NO_EXPUNGE':2147483648}
NATIVE_FLAGS = {'BANK0':8,'UPPER':16,'LINEAR':1048576}


def constants(abi=ABI, max_banks=16, gateway=None, tasks=None, memory=None):
    gateway = gateway if gateway is not None else json.loads((ROOT/'abi/exec816-v1.json').read_text())
    tasks = tasks if tasks is not None else json.loads((ROOT/'abi/tasks.json').read_text())
    memory = memory if memory is not None else json.loads((ROOT/'abi/memory-v1.json').read_text())
    integer(max_banks,1,256,'MAX_BANKS')
    require(abi['abi']=='exec816.heap' and abi['revision']==3,'Unsupported heap ABI')
    require(abi['alignment']==8 and abi['bank_bytes']==65536,'Unsupported heap geometry')
    require(abi['flags']=={**CLASSIC_FLAGS,**NATIVE_FLAGS},'Invalid Exec memory flags')
    for name,value in abi['flags'].items(): integer(value,0,0xffffffff,'flag '+name)
    integer(abi['owner'],1,65535,'HEAP owner')
    require(all(value!=abi['owner'] or name=='HEAP' for name,value in memory['owners'].items()),
            'Heap owner collides with bank manager')
    if 'HEAP' in memory['owners']:
        require(memory['owners']['HEAP']==abi['owner'],'Heap owner differs from bank manager')
    for group,low,high in [('services',0,255),('errors',0xff00,0xffff)]:
        values=list(abi[group].values())
        require(len(values)==len(set(values)),f'Duplicate heap {group}')
        for value in values: integer(value,low,high,group)
        existing=set(gateway[group].values())|set(tasks[group].values())
        require(not existing.intersection(values),f'Heap {group} collide with existing ABI')
    require(set(abi['services'])=={'ALLOC_MEM','FREE_MEM','ALLOC_VEC','FREE_VEC','AVAIL_MEM','TYPE_OF_MEM'},
            'Invalid heap services')
    require(abi['compiler_frame']==tasks['compiler_frame'],'Heap saved-frame layout differs')
    require(set(abi['imports'])==set(DECLARATIONS),'Invalid heap imports')
    c=dict(REVISION=abi['revision'],OWNER=abi['owner'],ALIGNMENT=8,BANK_BYTES=65536,
           MAX_BANKS=max_banks,NT_MEMORY=abi['node_type'],ADDRESS_END=0x1000000)
    for group,prefix in [('services','SERVICE'),('errors','ERROR'),('flags','FLAG'),('compiler_frame','FRAME')]:
        c.update({f'{prefix}_{name.upper()}':value for name,value in abi[group].items()})
    require(set(abi['records'])=={'MemHeader','MemChunk','VecPrefix'},'Invalid heap records')
    for typename,record in abi['records'].items():
        cursor=0; names=set()
        for name,kind,offset in record['fields']:
            require(kind in WIDTHS,f'Invalid {typename} type')
            width,align=WIDTHS[kind];cursor=(cursor+align-1)//align*align
            require(name not in names and type(offset) is int and offset==cursor,f'Invalid {typename} layout')
            names.add(name);c[f'{typename.upper()}_{name.upper()}']=offset;cursor+=width
        require((cursor+1)//2*2==record['size'],f'Invalid {typename} size')
        c[typename.upper()+'_BYTES']=record['size']
    require(c['MEMCHUNK_BYTES']==8 and c['VECPREFIX_BYTES']==8,'Invalid chunk/prefix size')
    c.update(MAX_ORDINARY=65536,MAX_VECTOR_ORDINARY=65528)
    return c


def reserve_metadata(memory):
    """Private upper-RAM storage precedes emitted code in the kernel bank."""
    count=memory['constants']['MAX_BANKS']
    start=(memory['profile']['code_origin']+31)//32*32
    headers=(16+count+31)//32*32
    size=headers+(count-1)*32
    memory['upper_reservations'].append(dict(name='heap-metadata',address=start,size=size))
    memory['profile']['code_origin']=start+size
    memory['heap_storage']=dict(BASE=start,CLAIMS=start+16,HEADERS=start+headers,
                                CAPACITY=count-1,BYTES=size)


def registration_include(output,memory):
    write(Path(output)/'heap-storage.inc',HEADER+''.join(
        f'CONST HS_{name}=${value:x}\n' for name,value in memory['heap_storage'].items()),False)


def install_policy(output):
    source=read_source(ROOT/'lib/exec/heappolicy.act')
    (Path(output)/'heappolicy.act').write_text(source)


def types(public=False, abi=ABI):
    return ''.join(('PUBLIC ' if public else '')+'TYPE '+name+'=[\n'+''.join(
        f'  {kind} {field}\n' for field,kind,_ in record['fields'])+']\n'
        for name,record in abi['records'].items() if not public or name!='VecPrefix')


def public_api(abi=ABI):
    constants(abi)
    return HEADER+types(True,abi)+''.join(f'PUBLIC CONST MEMF_{name}=${value:x}\n'
        for name,value in abi['flags'].items())+f'PUBLIC CONST NT_MEMORY={abi["node_type"]}\n'


def internal_constants(abi=ABI):
    return HEADER+''.join(f'CONST H_{name}=${value:x}\n' for name,value in constants(abi).items())


def declarations():
    return ''.join('PUBLIC EXTERNAL '+line+'\n' for line in DECLARATIONS.values())


def call_types():
    # Native records include exactly the padding in imports; qualification
    # checks emitted offsets as well as actual public calls.
    return HEADER+'''TYPE HeapAllocArgs=[LONGCARD bytes LONGCARD flags]
TYPE HeapFreeArgs=[BYTE POINTER block LONGCARD bytes]
TYPE HeapPointerArgs=[BYTE POINTER block]
TYPE HeapQueryArgs=[LONGCARD flags]
'''+types(abi={'records':{'VecPrefix':ABI['records']['VecPrefix']}})


def check_compiler(compiler_abi, abi=ABI):
    require(compiler_abi['abi']=='action65816.native.v2','Unsupported compiler ABI')
    require({f['name']:f['offset'] for f in compiler_abi['saved_frame']['fields']}==abi['compiler_frame'],
            'Heap frame differs from pinned compiler')
    for name,width in [('data_pointer',3),('long_integer',4)]:
        require(compiler_abi['scalar_classes'][name]['size']==width,'Heap scalar width changed')


def check_routine(routine,name,abi=ABI):
    expected=abi['imports'][name]
    arguments=[{k:a[k] for k in ('alignment','offset','size')} for a in routine['arguments']]
    require(arguments==expected['arguments'] and routine['outgoing_bytes']==expected['outgoing_bytes'],
            f'Heap {name} native call layout changed')
    if 'result_bytes' in routine:
        require(routine['result_bytes']==expected['result_bytes'],f'Heap {name} result width changed')
    if 'result' in routine:
        require(routine['result']==RESULTS[expected['result_bytes']],f'Heap {name} result ABI changed')


def write(path,content,check):
    if check:
        require(path.is_file() and path.read_text().replace('\r\n','\n')==content,f'Stale generated heap file: {path}')
    else:
        path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content)


def generate(output,max_banks=16,check=False,abi=ABI):
    output=Path(output);c=constants(abi,max_banks)
    action=HEADER+''.join(f'CONST H_{name}=${value:x}\n' for name,value in c.items())+types(abi=abi)
    assembly=HEADER+''.join(f'H_{name} = ${value:x}\n' for name,value in c.items())
    for filename,content in [('heap-action.inc',action),('heap.inc',assembly),
                            ('heap.json',json.dumps(dict(abi=abi,constants=c),sort_keys=True,indent=2)+'\n')]:
        write(output/filename,content,check)
    return c


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',type=Path);parser.add_argument('--max-banks',type=int,default=16)
    parser.add_argument('--check',action='store_true');args=parser.parse_args()
    write(ROOT/'lib/exec/exec-memory-types.inc',public_api(),args.check)
    write(ROOT/'lib/exec/heap-constants.inc',internal_constants(),args.check)
    write(ROOT/'lib/exec/heap-call-types.inc',call_types(),args.check)
    if args.output: generate(args.output,args.max_banks,args.check)
