#!/usr/bin/env python3
"""Generate the ordinary-message AES protocol and independent layout probes."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ABI = json.loads((ROOT/'abi/aes-server.json').read_text())


def layout():
    sizes = {'BYTE': (1, 1), 'CARD': (2, 2), 'INT': (2, 2),
             'LONGCARD': (4, 2), 'EXEC.Message': (16, 2)}
    records = {}
    for name, fields in ABI['records'].items():
        offset, alignment, offsets = 0, 1, {}
        for field, kind, *counts in fields:
            size, align = (3, 1) if kind.endswith(' POINTER') else sizes[kind]
            count = ABI['constants'].get(counts[0], counts[0]) if counts else 1
            offset = (offset+align-1)//align*align
            offsets[field] = offset
            offset += size*count
            alignment = max(alignment, align)
        size = (offset+alignment-1)//alignment*alignment
        records[name] = dict(size=size, alignment=alignment, fields=offsets)
        sizes[name] = size, alignment
    return records


def expected_layout():
    result = [('WORD', 2), ('huge pointer', 4), ('native pointer', 3)]
    for name, record in layout().items():
        result += [(name+' size', record['size'])]
        result += [(name+' '+f, o) for f, o in record['fields'].items()]
    result += [('C context size', 169), ('C context request', 0)]
    return result


def files():
    constants = dict(VERSION=ABI['version'], **ABI['constants'])
    action = ['; Generated by tools/generate_aes_server.py; do not edit.',
              'MODULE AESTYPES', 'USE EXEC']
    header = ['/* Generated by tools/generate_aes_server.py; do not edit. */',
              '#ifndef EXEC816_AES_WIRE_H', '#define EXEC816_AES_WIRE_H',
              '#include <exec/ports.h>']
    action += [f'PUBLIC CONST {k}={v}' for k, v in constants.items()]
    header += [f'#define AES_{k} {v}' for k, v in constants.items()]
    c_types = {'BYTE': 'UBYTE', 'CARD': 'UWORD', 'INT': 'WORD',
               'LONGCARD': 'ULONG', 'EXEC.Message': 'struct Message',
               'EXEC.Task POINTER': 'struct Task EXEC_PTR *',
               'BYTE POINTER': 'UBYTE EXEC_PTR *'}
    expressions = ['sizeof(WORD)', 'sizeof(void *)', 'sizeof(void EXEC_PTR *)']
    for name, fields in ABI['records'].items():
        action += [f'PUBLIC TYPE {name}=[']
        header += [f'struct AES{name} {{']
        expressions += [f'sizeof(struct AES{name})']
        for field, kind, *counts in fields:
            action += [f'  {kind}'+(' ARRAY' if counts else '')+f' {field}'+
                       (f'({counts[0]})' if counts else '')]
            header += [f'    {c_types[kind]} {field}'+
                       (f'[AES_{counts[0]}]' if counts else '')+';']
            expressions += [f'offsetof(struct AES{name}, {field})']
        action += [']']
        header += ['};']
        record = layout()[name]
        values = {f'{name.upper()}_SIZE': record['size']}
        values.update({f'{name.upper()}_OFFSET_{f.upper()}': v for f, v in record['fields'].items()})
        action += [f'PUBLIC CONST {k}={v}' for k, v in values.items()]
        header += [f'#define AES_{k} {v}' for k, v in values.items()]
    return {
        ROOT/'lib/aes/aestypes.act': '\n'.join(action+['ENDMODULE', '']),
        ROOT/'c/include/exec816/aes-wire.h': '\n'.join(header+['#endif', '']),
        ROOT/'c/calypsi/aes-layout.c': '\n'.join([
            '/* Generated by tools/generate_aes_server.py; do not edit. */',
            '#include <exec816/aes.h>',
            '__attribute__((section("exec_layout")))',
            'const UWORD AESLayout[] = {',
            *['    '+e+',' for e in expressions],
            '    sizeof(struct ExecAESContext),',
            '    offsetof(struct ExecAESContext, request),', '};', ''])}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in files().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit('Stale AES layout: '+str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
