#!/usr/bin/env python3
"""Generate the private hosted service wire records and operation validator."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT/'ports/gem4xe/service'


def expected_layout():
    abi = json.loads((ROOT/'abi/gem-vdi.json').read_text())
    checks = []
    for name, record in abi['records'].items():
        checks.append((f'sizeof(struct Gem{name})',record['size']))
        checks += [(f'offsetof(struct Gem{name}, {field})',offset) for field,_,offset,_ in record['fields']]
    return checks


def files():
    abi = json.loads((ROOT/'abi/gem-vdi.json').read_text())
    header = ['/* Generated by tools/generate_gem_vdi.py. */',
              '#ifndef GEM_ABI_H', '#define GEM_ABI_H', '#include <proto/exec.h>',
              f'#define GEM_VERSION {abi["revision"]}']
    header += [f'#define GEM_MAX_POINT_PAIRS {max(op["point_pairs"][1] for op in abi["vdi_operations"])}',
               f'#define GEM_MAX_INT_WORDS {max(op["int_words"][1] for op in abi["vdi_operations"])}']
    for group,prefix in [('limits','LIMIT'),('services','OP'),('results','')]:
        header += [f'#define GEM_{prefix+"_" if prefix else ""}{name.upper()} {value}'
                   for name,value in abi[group].items()]
    types = {'ExecMessage':'struct Message','u16':'UWORD','u32':'ULONG','i16':'WORD'}
    for name,record in abi['records'].items():
        header += [f'#define GEM_{name.upper()}_BYTES {record["size"]}', f'struct Gem{name} {{']
        cursor=0
        for field,kind,offset,size in record['fields']:
            if offset!=cursor:
                raise ValueError('Unrepresented wire padding')
            base=kind.split('[')[0]
            suffix=kind[len(base):]
            header.append(f'    {types[base]} {field}{suffix};')
            cursor=offset+size
        if cursor!=record['size']:
            raise ValueError('Invalid wire extent')
        header.append('};')
    header += ['UWORD GemValidateCommand(UWORD operation, const struct GemCommand *command, const WORD *ints);',
               'UWORD GemCommandReplyWords(UWORD opcode);','#endif','']
    source = ['/* Generated by tools/generate_gem_vdi.py. */', '#include "gem-abi.h"',
              'UWORD GemValidateCommand(UWORD operation, const struct GemCommand *c, const WORD *ints)',
              '{', '    UWORD i;', '    switch (c->opcode) {']
    for op in abi['vdi_operations']:
        p,w=op['point_pairs'],op['int_words']
        source += [f'    case {op["opcode"]}:',
                   f'        if (operation != GEM_OP_{op["transport"]} || c->subopcode != {op["subopcode"]} ||',
                   f'            c->point_pairs < {p[0]} || c->point_pairs > {p[1]} ||',
                   f'            c->int_words < {w[0]} || c->int_words > {w[1]}) return GEM_UNSUPPORTED;']
        if 'int_values' in op:
            source += [f'        if (ints[{i}] != {v}) return GEM_UNSUPPORTED;' for i,v in enumerate(op['int_values'])]
        if 'value_range' in op:
            a,b=op['value_range']
            source += [f'        if (ints[0] < {a} || ints[0] > {b}) return GEM_UNSUPPORTED;']
        if 'glyph_range' in op:
            a,b=op['glyph_range']
            source += ['        for (i = 0; i < c->int_words; ++i)',
                       f'            if (ints[i] < {a} || ints[i] > {b}) return GEM_UNSUPPORTED;']
        source += ['        return GEM_OK;']
    source += ['    default: return GEM_UNSUPPORTED;', '    }', '}',
               'UWORD GemCommandReplyWords(UWORD opcode)', '{', '    switch (opcode) {']
    for op in abi['vdi_operations']:
        if op.get('reply_words',0):
            source += [f'    case {op["opcode"]}: return {op["reply_words"]};']
    source += ['    default: return 0;', '    }', '}', '']
    probe = ['/* Generated by tools/generate_gem_vdi.py. */','#include "gem-abi.h"',
             '__attribute__((section("exec_layout")))','const UWORD GemWireLayout[] = {']
    probe += [f'    {expr},' for expr,_ in expected_layout()]
    probe += ['};','']
    return {DEST/'gem-abi.h':'\n'.join(header),DEST/'gem-validation.c':'\n'.join(source),
            DEST/'gem-layout.c':'\n'.join(probe)}


if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    for path,content in files().items():
        if args.check:
            if not path.exists() or path.read_text()!=content:
                raise SystemExit('Stale GEM binding: '+str(path))
        else:
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_text(content)
