#!/usr/bin/env python3
"""Private resident keyboard state; independent of console metadata."""
import argparse
import json
from pathlib import Path
from generate_console import WIDTHS
from generate_memory import ROOT, require
from generate_heap import write

ABI = json.loads((ROOT/'abi/input-native.json').read_text())
HEADER = '; Generated by tools/generate_input_native.py; do not edit.\n'


def definitions():
    widths = {**WIDTHS, "INT": (2,2), "LONGINT": (4,2)}
    values = dict(ABI.get('constants', {}))
    native = HEADER+'MODULE INPUTNATIVE\nUSE EXEC\n'
    for name, record in ABI['records'].items():
        end = 0
        native += 'PUBLIC TYPE '+name+'=[\n'
        for field, kind, offset in record['fields']:
            base, count = kind[:-1].split('[') if '[' in kind else (kind, 1)
            size, align = widths[base]
            end = (end+align-1)//align*align
            require(offset == end, 'Invalid input-native field: '+name+'.'+field)
            values[name.upper()+'_'+field.upper()] = offset
            native += f'  {base} ARRAY {field}({count})\n' if '[' in kind else f'  {base} {field}\n'
            end += size*int(count)
        require((end+1)//2*2 == record['size'], 'Invalid input-native size')
        widths[name] = (record['size'],record['alignment'])
        values[name.upper()+'_SIZE'] = record['size']
        native += ']\n'
    native += ''.join(f'PUBLIC CONST {k}=${v:x}\n' for k,v in values.items())
    return values, native+'ENDMODULE\n'


def generate(output, memory):
    from generate_tasks import storage
    values, _ = definitions()
    base = storage(memory)['BASE']
    state = ABI['storage']['state_offset']
    capture = ABI['storage']['capture_offset']
    require(state >= 0xa60 and state+values['STATE_SIZE'] <= capture
            and capture+values['CAPTURE_SIZE'] <= 0xe30, 'Input exceeds existing Task arena slack')
    memory['input_storage'] = dict(STATE=base+state, CAPTURE=base+capture,
        STATE_BYTES=values['STATE_SIZE'], CAPTURE_BYTES=values['CAPTURE_SIZE'])
    layout = ABI['storage']
    from generate_platform_timer import ABI as timer
    from generate_program import ABI as program
    acquisitions = layout['acquisitions_offset']
    pointer_state = layout['pointer_state_offset']
    reserve = layout['pointer_reserve_offset']
    pointer = layout['pointer_capture_offset']
    require(acquisitions >= timer['state_offset']+timer['state_bytes']
            and acquisitions+4 <= 0x1000, 'Acquisition allocator overlaps fixed state/code')
    require(pointer_state >= program['provider_offset']+program['provider_capacity']
            and pointer_state+values['STATE_SIZE'] <= reserve, 'Pointer state overlaps provider table/capture')
    guard = layout['pointer_guard_bytes']
    require(pointer == reserve+guard
            and pointer+values['POINTERCAPTURE_SIZE']+guard <= reserve+layout['pointer_reserved_bytes']
            and reserve+layout['pointer_reserved_bytes'] <= 65536, 'Pointer reservation overflow')
    memory['input_storage'].update(ACQUISITIONS=base+acquisitions, POINTER_STATE=base+pointer_state,
        POINTER_CAPTURE=base+pointer, POINTER_RESERVE=base+reserve,
        POINTER_CAPTURE_BYTES=values['POINTERCAPTURE_SIZE'],
        POINTER_RESERVED_BYTES=layout['pointer_reserved_bytes'], POINTER_GUARD_BYTES=guard)
    for suffix, prefix in [('inc', ''), ('act.inc', 'CONST ')]:
        write(Path(output)/('input-storage.'+suffix), HEADER+''.join(
            f'{prefix}IN_{k}=${v:x}\n' for k,v in memory['input_storage'].items()), False)


if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--check',action='store_true')
    a = p.parse_args()
    values, native = definitions()
    write(ROOT/'lib/input/inputnative.act', native, a.check)
    write(ROOT/'platform/altirraos/input-native.inc', HEADER+''.join(
        f'IN_{k}=${v:x}\n' for k,v in values.items()), a.check)

    bounds = ABI['motion_interval_upper_bounds']
    require(len(bounds) == 16 and bounds == sorted(set(bounds)) and bounds[-1] == 255,
            'Invalid motion interval classes')
    ages = [16 if age in (0, 255) else next(i for i, limit in enumerate(bounds) if age <= limit)
            for age in range(256)]
    table = HEADER+'pointer_age_class:\n'
    table += ''.join('    .byte '+','.join(map(str, ages[i:i+16]))+'\n' for i in range(0,256,16))
    write(ROOT/'platform/altirraos/pointer-timing.inc', table, a.check)
