#!/usr/bin/env python3
"""Generate the native DOS source contract; private packets are not public APIs."""
from library_paths import library_file
import argparse,json,re
from pathlib import Path
from generate_memory import ROOT,require
from generate_heap import write
ABI=json.loads((ROOT/'abi/dos.json').read_text())
SIGNATURES={'Pipe':([3],4),'Open':([3,4],3),'Read':([3,3,4],4),'Write':([3,3,4],4),'Seek':([3,4,4],4),'Close':([3],4),'IoErr':([],4),'SetIoErr':([4],4),'Lock':([3,4],3),'UnLock':([3],0),'Examine':([3,3],4),'ExNext':([3,3],4),'ReleaseContext':([],4),'Input':([],3),'Output':([],3),'SelectInput':([3],3),'SelectOutput':([3],3),'IsInteractive':([3],4),'CurrentDir':([3],3),'NameFromLock':([3,3,4],4),'BeginForeground':([3],4),'EndForeground':([],4),'BreakPending':([],4),'ClearBreak':([],0)}
HEADER='; Generated by tools/generate_dos.py; do not edit.\n'
RESULTS={0:'None',3:'Some(NativeResult(A16X8ZeroExtended))',4:'Some(NativeResult(A16X16))'}
DECLARATIONS={
 'Pipe':'LONGINT FUNC Pipe(PipePair POINTER pair)',
 'BeginForeground':'LONGINT FUNC BeginForeground(FileHandle POINTER console)',
 'EndForeground':'LONGINT FUNC EndForeground()',
 'BreakPending':'LONGINT FUNC BreakPending()',
 'ClearBreak':'PROC ClearBreak()',
 'Open':'FileHandle POINTER FUNC Open(BYTE POINTER name LONGINT mode)',
 'Read':'LONGINT FUNC Read(FileHandle POINTER file BYTE POINTER buffer LONGINT length)',
 'Write':'LONGINT FUNC Write(FileHandle POINTER file BYTE POINTER buffer LONGINT length)',
 'Seek':'LONGINT FUNC Seek(FileHandle POINTER file LONGINT offset LONGINT mode)',
 'Close':'LONGINT FUNC Close(FileHandle POINTER file)',
 'IoErr':'LONGINT FUNC IoErr()',
 'SetIoErr':'LONGINT FUNC SetIoErr(LONGINT error)',
 'Lock':'FileLock POINTER FUNC Lock(BYTE POINTER name LONGINT mode)',
 'UnLock':'PROC UnLock(FileLock POINTER lock)',
 'Examine':'LONGINT FUNC Examine(FileLock POINTER lock FileInfoBlock POINTER info)',
 'ExNext':'LONGINT FUNC ExNext(FileLock POINTER lock FileInfoBlock POINTER info)',
 'ReleaseContext':'LONGINT FUNC ReleaseContext()',
 'Input':'FileHandle POINTER FUNC Input()',
 'Output':'FileHandle POINTER FUNC Output()',
 'SelectInput':'FileHandle POINTER FUNC SelectInput(FileHandle POINTER file)',
 'SelectOutput':'FileHandle POINTER FUNC SelectOutput(FileHandle POINTER file)',
 'IsInteractive':'LONGINT FUNC IsInteractive(FileHandle POINTER file)',
 'CurrentDir':'FileLock POINTER FUNC CurrentDir(FileLock POINTER lock)',
 'NameFromLock':'LONGINT FUNC NameFromLock(FileLock POINTER lock BYTE POINTER buffer LONGINT length)',
}

def constants(abi=ABI):
    require(abi['abi']=='exec816.dos' and abi['revision']==2,'Unsupported DOS ABI')
    require(set(abi['imports'])==set(DECLARATIONS),'Incomplete DOS calls')
    for namespace in ('process','program'):
        for name, value in json.loads((ROOT/'abi'/f'{namespace}.json').read_text())['errors'].items():
            own = 'ERROR_'+name
            if own in abi['dos_errors']:
                require(abi['dos_errors'][own]==value, 'Inconsistent shared error: '+own)
            else:
                require(value not in abi['dos_errors'].values(), 'DOS error collides with '+namespace+'.'+name)
    for name,(sizes,result) in SIGNATURES.items():
        cursor=0;args=[]
        for size in sizes:
            align=1 if size==3 else 2;cursor=(cursor+align-1)//align*align
            args.append(dict(alignment=align,offset=cursor,size=size));cursor+=size
        require(abi['imports'][name]==dict(arguments=args,outgoing_bytes=cursor|1,result_bytes=result),'Invalid DOS call ABI: '+name)
    require(set(abi['records'])=={'DateStamp','FileInfoBlock','DosPacket','StandardPacket','PipePair'},'Incomplete DOS records')
    require(set(abi['services'])=={'CONTEXT','MOUNT_REFERENCE'},'Unexpected DOS service')
    widths={'FileHandle POINTER':(3,1),'LONGINT':(4,2),'CARD':(2,2),'EXEC.Message':(16,2),'EXEC.Message POINTER':(3,1),'EXEC.MsgPort POINTER':(3,1)}
    c={**abi['constants'],**abi['dos_errors'],**abi['actions']}
    for name,record in abi['records'].items():
        cursor=0
        for field,kind,offset in record['fields']:
            array=re.fullmatch(r'BYTE\[(\d+)\]',kind)
            size,align=(int(array[1]),1) if array else widths[kind]
            cursor=(cursor+align-1)//align*align
            require(offset==cursor,'Invalid DOS field offset: '+field)
            c[name.upper()+'_'+field.upper()]=offset;cursor+=size
        require(record['alignment']==2 and record['size']==(cursor+1)//2*2,'Invalid DOS size: '+name)
        widths[name]=(record['size'],2);c[name.upper()+'_SIZE']=record['size']
    existing=set()
    for filename in ('exec816-v1.json','tasks.json','heap-v1.json','ports.json','io.json'):
        existing.update(json.loads((ROOT/'abi'/filename).read_text())['services'].values())
    values=list(abi['services'].values())
    require(len(set(values))==len(values) and all(type(v) is int and 0<=v<256 and v not in existing for v in values),'DOS selector collision')
    faults=set()
    for filename in ('exec816-v1.json','tasks.json','heap-v1.json','ports.json','io.json'):
        faults.update(json.loads((ROOT/'abi'/filename).read_text())['errors'].values())
    require(set(abi['errors'])=={'MISUSE'} and all(type(v) is int and 0xff00<=v<=0xffff and v not in faults and v not in (0xff91,0xff92,0xff93) for v in abi['errors'].values()),'DOS fault collision')
    c.update({'ERROR_'+k:v for k,v in abi['errors'].items()})
    c.update({'SERVICE_'+k:v for k,v in abi['services'].items()})
    return c

def types(public=False,private=False):
    result=''
    if public:
        result+='; Opaque identities. Only DOS creates/frees them; this token is not their storage layout.\n'
        result+='PUBLIC TYPE FileHandle=[BYTE opaque]\nPUBLIC TYPE FileLock=[BYTE opaque]\n'
    for name,record in ABI['records'].items():
        if (name in ('DosPacket','StandardPacket'))!=private:continue
        result+=('PUBLIC ' if public else '')+'TYPE '+name+'=[\n'
        for field,kind,_ in record['fields']:
            array=re.fullmatch(r'BYTE\[(\d+)\]',kind)
            result+=f'  BYTE ARRAY {field}({array[1]})\n' if array else f'  {kind} {field}\n'
        result+=']\n'
    return result

def private_api():
    constants()
    return (HEADER+''.join(f'CONST DOS_ERROR_{k}=${v:x}\n' for k,v in ABI['errors'].items())
            +''.join(f'CONST DOS_{k}={v}\n' for k,v in ABI['actions'].items())+types(private=True))

def public_api():
    constants()
    return HEADER+types(True)+''.join(f'PUBLIC CONST {k}={v}\n' for k,v in {**ABI['constants'],**ABI['dos_errors']}.items())+''.join(
        f'PUBLIC CONST {name.upper()}_SIZE={ABI["records"][name]["size"]}\n' for name in ('DateStamp','FileInfoBlock'))

def declarations():return ''.join('PUBLIC EXTERNAL '+d+'\n' for d in DECLARATIONS.values())

def cooked_api():
    spec=ABI['cooked'];record=spec['session'];cursor=0
    text=HEADER+''.join(f'PUBLIC CONST {"LONGINT " if v<0 else ""}{k}={v}\n' for k,v in spec['constants'].items())
    text+=f'PUBLIC CONST SESSION_SIZE={record["size"]}\nPUBLIC TYPE Session=[\n'
    for field,kind,offset in record['fields']:
        array=re.fullmatch(r'BYTE\[(\d+)\]',kind)
        size,align=(int(array[1]),1) if array else {'BYTE':(1,1),'CARD':(2,2),'LONGINT':(4,2)}[kind]
        cursor=(cursor+align-1)//align*align
        require(offset==cursor,'Invalid cooked field: '+field);cursor+=size
        text+=f'  BYTE ARRAY {field}({array[1]})\n' if array else f'  {kind} {field}\n'
    require((cursor+1)//2*2==record['size'],'Invalid cooked session size')
    return text+']\n'

def break_api():
    record=ABI['foreground'];cursor=0
    text=HEADER+'MODULE DOSBREAKTYPES\nPUBLIC CONST SCOPE_SIZE='+str(record['size'])+'\nPUBLIC TYPE Scope=[\n'
    for field,kind,offset in record['fields']:
        size,align={'BYTE':(1,1),'BYTE POINTER':(3,1),'LONGCARD':(4,2)}[kind]
        cursor=(cursor+align-1)//align*align
        require(offset==cursor,'Invalid foreground field: '+field);cursor+=size
        text+='  '+kind+' '+field+'\n'
    require((cursor+1)//2*2==record['size'] and record['size']<=64,'Invalid foreground scope size')
    return text+']\nENDMODULE\n'

def check_routine(routine,name):
    expected=ABI['imports'][name]
    args=[{k:a[k] for k in ('alignment','offset','size')} for a in routine['arguments']]
    require(args==expected['arguments'] and routine['outgoing_bytes']==expected['outgoing_bytes'],'DOS call shape changed: '+name)
    if 'result_bytes' in routine:require(routine['result_bytes']==expected['result_bytes'],'DOS result width changed')
    if 'result' in routine:require(routine['result']==RESULTS[expected['result_bytes']],'DOS result ABI changed')

def production_binding(interface):
    check_routine(interface,interface['name'].split('.')[1])
    raise ValueError('Unimplemented DOS import: '+interface['name'])

def check_public():
    for filename,expected in (('dos-types.inc',public_api()),('dos-packets.inc',private_api()),('dos.act',HEADER+'MODULE DOS\nINCLUDE "dos-types.inc"\n'+declarations()+'ENDMODULE\n')):
        require((library_file(filename)).read_text().replace('\r\n','\n')==expected,'Stale DOS declarations: '+filename)
    require((ROOT/'lib/dos/dosbreaktypes.act').read_text()==break_api(),'Stale foreground layout')
    require((ROOT/'lib/dos/dos-cooked-types.inc').read_text()==cooked_api(),'Stale cooked session layout')

def reserve_metadata(memory,capacity):
    start=(memory['profile']['code_origin']+15)//16*16
    size=capacity*16
    require(start+size<=(memory['constants']['KERNEL_BANK']+1)*65536,'DOS metadata exceeds kernel bank')
    memory['upper_reservations'].append(dict(name='dos-contexts',address=start,size=size))
    shared=start+size
    stream_bytes=ABI['streams']['slots']*ABI['streams']['slot_bytes']
    require(ABI['streams']==dict(slots=4,slot_bytes=16),'Invalid stream registry capacity')
    require(shared+96+stream_bytes<=(memory['constants']['KERNEL_BANK']+1)*65536,'DOS service metadata exceeds kernel bank')
    memory['upper_reservations'].append(dict(name='dos-service',address=shared,size=96))
    streams=shared+96
    memory['upper_reservations'].append(dict(name='dos-streams',address=streams,size=stream_bytes))
    memory['profile']['code_origin']=streams+stream_bytes
    memory['dos_storage']=dict(BASE=start,BYTES=size,CAPACITY=capacity,SHARED=shared,SERVICE_BYTES=96,
                               STREAMS=streams,STREAM_BYTES=stream_bytes,STREAM_SLOTS=ABI['streams']['slots'])

def registration_include(output,memory):
    write(Path(output)/'dos-storage-action.inc',HEADER+''.join(f'CONST DS_{k}=${v:x}\n' for k,v in memory['dos_storage'].items()),False)

def generate(output,check=False):
    c=constants();output=Path(output)
    write(output/'dos.inc',HEADER+''.join(f'DOS_{k} = {v}\n' for k,v in c.items()),check)
    write(output/'dos-action.inc',HEADER+''.join(f'CONST DOS_{k}={v}\n' for k,v in c.items()),check)

if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--output',type=Path);p.add_argument('--check',action='store_true');a=p.parse_args()
    write(ROOT/'lib/dos/dos-types.inc',public_api(),a.check)
    write(ROOT/'lib/dos/dos-packets.inc',private_api(),a.check)
    write(ROOT/'lib/dos/dos.act',HEADER+'MODULE DOS\nINCLUDE "dos-types.inc"\n'+declarations()+'ENDMODULE\n',a.check)
    write(ROOT/'lib/dos/dos-cooked-types.inc',cooked_api(),a.check)
    write(ROOT/'lib/dos/dosbreaktypes.act',break_api(),a.check)
    if a.output:generate(a.output,a.check)
