#!/usr/bin/env python3
"""Generate loader policy and command definitions from the public program contract."""
import argparse
import json
import re
import struct
from pathlib import Path
from generate_memory import ROOT
from generate_heap import write
from generate_dos import ABI as DOS_ABI, types as dos_types

ABI = json.loads((ROOT/'abi/program.json').read_text())


def fault_messages(dos=DOS_ABI, program=ABI):
    messages = {}
    for definitions, descriptions in ((dos['dos_errors'], dos['error_messages']),
                                       (program['errors'], program['error_messages'])):
        if set(definitions) != set(descriptions):
            raise ValueError('Incomplete fault descriptions')
        if len(set(definitions.values())) != len(definitions):
            raise ValueError('Duplicate fault code')
        for name, code in definitions.items():
            text = descriptions[name]
            if not text or len(text) > 80 or any(not 32 <= ord(c) <= 126 or c in '"\\' for c in text):
                raise ValueError('Invalid fault description: '+name)
            if code in messages and messages[code] != text:
                raise ValueError('Conflicting fault description: '+name)
            messages[code] = text
    return messages


def fault_table():
    text = '; Generated by tools/generate_program.py; do not edit.\n'
    text += 'CSTRING FUNC Message(LONGINT code)\n\n  CASE code OF\n'
    for code, description in sorted(fault_messages().items()):
        text += f'  WHEN {code} THEN\n    RETURN(c"{description}")\n'
    return text+'  ESAC\n\nRETURN(NULL)\n'


def constants():
    text = '; Generated by tools/generate_program.py; do not edit.\n'
    text += f'PUBLIC CONST ENTRY_SIGNATURE=LONGCARD(${ABI["entry_signature"]:x})\n'
    text += f'PUBLIC CONST PROVIDER_CAPACITY={ABI["provider_capacity"]}\nPUBLIC CONST PROVIDER_OPERATION={ABI["provider_operation"]}\n'
    for group, prefix in [('limits', 'LIMIT'), ('errors', 'ERROR')]:
        text += ''.join(f'PUBLIC CONST {prefix}_{key}=LONGCARD({value})\n'
                        for key, value in ABI[group].items())
    return text


def command_results():
    return ('; Generated by tools/generate_program.py; do not edit.\n'
            +''.join(f'PUBLIC CONST RETURN_{name}={value}\n'
                     for name, value in ABI['result_codes'].items()))


def command_errors():
    return ('; Generated by tools/generate_program.py from abi/dos.json; do not edit.\n'
            +''.join(f'PUBLIC CONST {name}={value}\n'
                     for name, value in DOS_ABI['dos_errors'].items()))


def command_modes():
    return ('; Generated by tools/generate_program.py from abi/dos.json; do not edit.\n'
            +''.join(f'PUBLIC CONST {name}={DOS_ABI["constants"][name]}\n'
                     for name in ('MODE_OLDFILE', 'MODE_NEWFILE', 'MODE_READWRITE',
                                  'OFFSET_BEGINNING', 'OFFSET_CURRENT', 'OFFSET_END')))


def command_args():
    return ('; Generated by tools/generate_program.py; do not edit.\n'
            + ''.join(f'PUBLIC CONST ARGS_MAX_{name}={value}\n'
                      for name, value in ABI['argument_limits'].items())
            + ''.join(f'PUBLIC CONST ARGS_{name}={value}\n' for name,value in ABI['argument_results'].items())
            + f'PUBLIC CONST ARGS_STORAGE_BYTES={ABI["argument_limits"]["TEXT"]+1+4*ABI["argument_limits"]["FIELDS"]+3*(ABI["argument_limits"]["MULTI"]+1)}\n')


def command_buffers():
    text = '; Generated by tools/generate_program.py; do not edit.\n'
    for key, value in ABI['stream_limits'].items():
        text += f'PUBLIC CONST STREAM_{key}={value}\n'
    for name, fields in ABI['records'].items():
        text += f'PUBLIC TYPE {name}=[\n'
        for kind, member in fields:
            array = re.fullmatch(r'BYTE\[(\d+)\]', kind)
            text += f'  BYTE ARRAY {member}({array[1]})\n' if array else f'  {kind} {member}\n'
        text += ']\n'
    return text


def command_api():
    text = '; Generated by tools/generate_program.py; do not edit.\nMODULE COMMAND\n'
    text += 'INCLUDE "command-results.inc"\n'
    text += 'INCLUDE "command-errors.inc"\n'
    text += 'INCLUDE "command-modes.inc"\n'
    text += 'INCLUDE "command-args.inc"\n'
    text += 'INCLUDE "command-buffers.inc"\n'
    text += f'PUBLIC CONST FAULT_BUFFER_BYTES={DOS_ABI["constants"]["FAULT_BUFFER_BYTES"]}\n'
    text += dos_types(public=True)
    text += 'PUBLIC CONST SHARED_LOCK=-2\n'
    for name, spec in ABI['providers'].items():
        kind = 'PROC' if spec['result'] == 'PROC' else spec['result']+' FUNC'
        args = ' '.join(kind+' '+name for kind, name in spec['arguments'])
        text += f'PUBLIC EXTERNAL {kind} {name}({args})\n'
    return text+'ENDMODULE\n'


def kernel_constants():
    return ('; Generated by tools/generate_program.py; do not edit.\n'
            +f'CONST PROGRAM_PROVIDER_OPERATION={ABI["provider_operation"]}\n'
            +f'CONST PROGRAM_PROVIDER_OFFSET=${ABI["provider_offset"]:x}\n')


def library_contracts(compiler_directory):
    """An explicit allowlist of compiler-owned resident libraries."""
    path = Path(compiler_directory)/'embedded/modules/cstring/contract.json'
    contract = json.loads(path.read_text())
    if (contract['schema_version'] != 1 or contract['abi'] != ABI['native_abi'] or
            contract['module'] != 'CSTRING' or contract['implementation'] != 'CSTRING.IMPL'):
        raise ValueError('Unsupported resident library contract: '+str(path))
    for name, spec in contract['providers'].items():
        if spec['symbol'] != 'cstring_'+name+'_v1' or not 0 <= spec['signature'] < 1 << 32:
            raise ValueError('Invalid CSTRING provider contract: '+name)
    return [contract]


def command_import(interface, libraries):
    name = interface['name']
    if name.startswith('COMMAND.') and name[8:] in ABI['providers']:
        public = 'exec816_'+name[8:].lower()+'_v1'
    else:
        found = [(contract, spec) for contract in libraries
                 for member, spec in contract['providers'].items()
                 if name.upper() == (contract['module']+'.'+member).upper()]
        if len(found) != 1:
            raise ValueError('Unsupported command interface: '+name)
        contract, spec = found[0]
        args, incoming, _ = physical(spec)
        if (interface['signature'] != spec['signature'] or interface['abi'] != contract['abi'] or
                interface['arguments'] != args or interface['outgoing_bytes'] != incoming):
            raise ValueError('Resident library interface mismatch: '+name)
        public = spec['symbol']
    return dict(symbol=interface['symbol'],name=public,stack_peak=0,checks_stack=True,domains=1)


def physical(spec):
    widths = {'BYTE POINTER':(3,1), 'ADDRESS POINTER':(3,1), 'CARD':(2,2), 'LONGINT':(4,2), 'LONGCARD':(4,2), 'PROC':(0,1),
              'SIZE':(3,2), 'SYS.CSTRING':(3,1), 'INT':(2,2), 'BYTE':(1,1)}
    at, arguments = 0, []
    for kind, _ in spec['arguments']:
        size, alignment = widths[kind]
        at = (at+alignment-1)//alignment*alignment
        arguments.append(dict(offset=at, size=size, alignment=alignment))
        at += size
    return arguments, at|1, widths[spec['result']][0]


def provider_manifest(image, labels, checked, libraries=()):
    """Bind only explicit API routines actually present in this checked build."""
    if not any(r['name'].startswith('M_PROGRAMPROVIDERS_') for r in image['routines']):
        return b'', []
    if not checked:
        raise ValueError('Hosted o65 requires a checked kernel')
    providers = [dict(name='__a816_stack_overflow_v2',address=labels['stack_overflow'],
                      size=labels['stack_overflow_end']-labels['stack_overflow'],
                      contract=dict(abi=ABI['native_abi'],signature=0,arguments=[],result=0,
                                    incoming=0,stack_peak=0,irq_effect=0,kind=1,domains=3))]
    groups = [('PROGRAMAPI', [('exec816_'+name.lower()+'_v1', name, spec)
                              for name, spec in ABI['providers'].items()])]
    for library in libraries:
        groups.append((library['implementation'].replace('.', '_'),
                       [(spec['symbol'], name, spec) for name, spec in library['providers'].items()]))
    for implementation, exports in groups:
        for public, name, spec in exports:
            matches = [r for r in image['routines'] if re.fullmatch('M_'+implementation+'_'+name.upper()+r'_[0-9A-F]+',r['name'])]
            if len(matches) != 1: raise ValueError('Missing or ambiguous program provider: '+name)
            routine = matches[0]
            args, incoming, result = physical(spec)
            if 'signature' in spec and routine['signature'] != spec['signature']:
                raise ValueError('Program provider signature mismatch: '+public)
            if ([{k:a[k] for k in ('offset','size','alignment')} for a in routine['arguments']] != args or
                    routine['outgoing_bytes'] != incoming or routine['result_bytes'] != result):
                raise ValueError('Program provider ABI mismatch: '+name)
            if not any(s['executable'] and s['address'] <= routine['address'] and
                       routine['address']+routine['size'] <= s['address']+len(s['bytes']) for s in image['segments']):
                raise ValueError('Program provider outside emitted executable storage: '+name)
            providers.append(dict(name=public,address=routine['address'],size=routine['size'],
                                  contract=dict(abi=ABI['native_abi'],signature=routine['signature'],arguments=args,
                                                result=result,incoming=incoming,stack_peak=0,irq_effect=0,kind=0,domains=1)))
    ranges = sorted((p['address'],p['address']+p['size']) for p in providers)
    if any(a[1] > b[0] for a,b in zip(ranges,ranges[1:])): raise ValueError('Overlapping provider extents')
    payload = bytearray(b'EPV2'+bytes(4)+struct.pack('<HHBBH',len(providers),0,1,1,0))
    for p in providers:
        name = p['name'].encode('ascii')
        payload += struct.pack('<I',len(name))+name+p['address'].to_bytes(3,'little')+struct.pack('<II',p['size'],p['contract']['signature'])
    payload[4:8] = struct.pack('<I',len(payload))
    if len(payload)>ABI['provider_capacity']: raise ValueError('Program provider manifest exceeds reserved capacity')
    return bytes(payload), providers


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    write(ROOT/'lib/dos/dos-fault-messages.inc', fault_table(), args.check)
    write(ROOT/'lib/dos/o65-constants.inc', constants(), args.check)
    write(ROOT/'lib/dos/command-buffers.inc', command_buffers(), args.check)
    write(ROOT/'lib/dos/command.act', command_api(), args.check)
    write(ROOT/'lib/dos/command-results.inc', command_results(), args.check)
    write(ROOT/'lib/dos/command-errors.inc', command_errors(), args.check)
    write(ROOT/'lib/dos/command-modes.inc', command_modes(), args.check)
    write(ROOT/'lib/dos/command-args.inc', command_args(), args.check)
    write(ROOT/'lib/dos/program-kernel.inc', kernel_constants(), args.check)
