#!/usr/bin/env python3
"""Private console layout, shared by the terminal, worker and native adapter."""
import argparse,json
from pathlib import Path
from generate_memory import ROOT,require
from generate_heap import write

ABI=json.loads((ROOT/'abi/console.json').read_text())
HEADER='; Generated by tools/generate_console.py; do not edit.\n'
WIDTHS={'BYTE':(1,1),'CARD':(2,2),'LONGCARD':(4,2),'BYTE POINTER':(3,1),
        'EXECLISTS.MinList':(9,1),'EXEC.MsgPort':(27,1),'EXEC.Task':(62,2),'EXEC.TaskLease':(12,2)}

def constants(abi=ABI):
    require(abi['schema_version']==1,'Invalid console schema')
    widths=dict(WIDTHS);result=dict(abi['constants'])
    for name,record in abi['records'].items():
        cursor=0;alignment=1;names=set()
        for field,kind,offset in record['fields']:
            base,count=kind[:-1].split('[') if '[' in kind else (kind,1)
            size,align=widths[base];size*=int(count)
            cursor=(cursor+align-1)//align*align;alignment=max(alignment,align)
            require(field not in names and offset==cursor,'Invalid console field: '+name+'.'+field)
            names.add(field);result[name.upper()+'_'+field.upper()]=offset;cursor+=size
        require(record['alignment']==alignment and record['size']==(cursor+alignment-1)//alignment*alignment,
                'Invalid console size: '+name)
        widths[name]=(record['size'],alignment);result[name.upper()+'_SIZE']=record['size']
    require(result['BINDING_SIZE']==12 and result['CAPTURE_SIZE']==560 and result['RAW_SLOTS']==64
            and result['INPUT_BYTES']==128 and result['CELL_BYTES']==960,'Invalid console capacity')
    require(result['CONERR_INPUTOVERFLOW']==1 and result['RAWEVENT_SIZE']==8,'Invalid console event/error contract')
    require(result['ROUTE_SIZE']==16 and result['ROUTES_SIZE']==264,'Invalid route retention capacity')
    require(result['SOURCE_QUANTUM']==64 and result['MAX_WIDTH']==40
            and result['MAX_HEIGHT']==24,'Invalid initial console geometry/quanta')
    require(result['WINDOW_SLOTS']==4 and result['WINDOW_SIZE']==38 and result['WINDOWS_SIZE']==172,'Invalid window capacity')
    s=abi['storage'];end=0
    for name,key in [('Service','service_offset'),('Instance','instance_offset'),('Presentation','presentation_offset'),('Routes','routes_offset'),('Windows','windows_offset')]:
        start=s[key];require(start>=end,'Overlapping console metadata')
        end=start+abi['records'][name]['size']
    require(end<=s['reserved_bytes'] and s['reserved_bytes']%16==0,'Console metadata exceeds reservation')
    require(s['capture_offset']>=0xa60 and s['capture_offset']+result['CAPTURE_SIZE']<=0x1000,
            'Console capture overlaps DOS descriptors or native code')
    require(s['glyph_offset']>=s['capture_offset']+result['CAPTURE_SIZE']
            and s['keymap_offset']==s['glyph_offset']+128
            and s['keymap_offset']+128<=0x1000,'Console tables overlap arena reservations')
    require(set(abi['keymaps'])=={'normal','shifted'} and all(len(v)==64 and all(type(x) is int and 0<=x<128 for x in v) for v in abi['keymaps'].values()),'Invalid keyboard map')
    require(abi['keymaps']['normal'][18]==99,'Ctrl-C native capture scan changed')
    return result

def types():
    c=constants();lines=[HEADER,'MODULE CONSOLETYPES\nUSE EXEC\nUSE EXECLISTS\n']
    for name,record in ABI['records'].items():
        lines.append('PUBLIC TYPE '+name+'=[\n')
        for field,kind,offset in record['fields']:
            if '[' in kind:
                base,count=kind[:-1].split('[');lines.append(f'  {base} ARRAY {field}({count})\n')
            else:lines.append(f'  {kind} {field}\n')
        lines.append(']\n')
    lines.extend(f'PUBLIC CONST {name}=${value:x}\n' for name,value in c.items())
    return ''.join(lines)+'ENDMODULE\n'

def glyphs():
    # Pinned Atari ROM font: ASCII punctuation/capitals at 0..63, lower case
    # at 97..122 and vertical bar at 124. Other printable ASCII uses '?'.
    return [value-32 if 32<=value<=95 else value if 97<=value<=122 or value==124 else 31 for value in range(128)]

def assembly():
    return HEADER+''.join(f'CON_{name} = ${value:x}\n' for name,value in constants().items())

def reserve_metadata(memory):
    from generate_tasks import storage
    c=constants();s=ABI['storage'];base=(memory['profile']['code_origin']+15)//16*16
    end=base+s['reserved_bytes']
    require(base>>16==memory['constants']['KERNEL_BANK'] and end<=(base&0xff0000)+65536,
            'Console metadata exceeds kernel bank')
    require(all(end<=r['address'] or base>=r['address']+r['size'] for r in memory['upper_reservations']),
            'Console metadata overlap')
    memory['upper_reservations'].append(dict(name='console-resident',address=base,size=s['reserved_bytes']))
    memory['profile']['code_origin']=end
    memory['console_storage']=dict(BASE=base,BYTES=s['reserved_bytes'],INSTANCE=base+s['instance_offset'],
        PRESENTATION=base+s['presentation_offset'],ROUTES=base+s['routes_offset'],WINDOWS=base+s['windows_offset'],CAPTURE=storage(memory)['BASE']+s['capture_offset'],
        GLYPHS=storage(memory)['BASE']+s['glyph_offset'],KEYMAP=storage(memory)['BASE']+s['keymap_offset'])

def generate(output,memory):
    constants();output=Path(output)
    (output/'console-tables.bin').write_bytes(bytes(glyphs()+ABI['keymaps']['normal']+ABI['keymaps']['shifted']))
    write(output/'console-storage.inc',HEADER+''.join(f'CS_{n} = ${v:x}\n' for n,v in memory['console_storage'].items()),False)
    write(output/'console-storage-action.inc',HEADER+''.join(f'CONST CS_{n}=${v:x}\n' for n,v in memory['console_storage'].items()),False)
    write(output/'console-action.inc',HEADER+''.join(f'CONST CON_{n}=${v:x}\n' for n,v in constants().items()),False)

if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');a=p.parse_args()
    write(ROOT/'lib/console/consoletypes.act',types(),a.check)
    write(ROOT/'platform/altirraos/console-layout.inc',assembly(),a.check)
