#!/usr/bin/env python3
"""Generate the small C binding's constants and layout checks from Exec's ABI."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def load(name):
    return json.loads((ROOT / 'abi' / name).read_text())


def expected_layout():
    checks = [(f'sizeof({kind})', size) for kind, size in
              [('BYTE', 1), ('WORD', 2), ('LONG', 4), ('BPTR', 4), ('APTR', 4),
               ('void EXEC_PTR *', 3), ('struct Node', 11), ('struct List', 11),
               ('struct MinNode', 6), ('struct MinList', 9)]]
    for name, record in dict(load('ports.json')['records'], Task=load('tasks.json')['task']).items():
        checks.append((f'sizeof(struct {name})', record['size']))
        checks += [(f'offsetof(struct {name}, {field})', offset) for field, _, offset in record['fields']]
    packet = load('tasks.json')['create_packet']
    checks.append(('sizeof(struct ExecCreateTaskPacket)', packet['size']))
    checks += [(f'offsetof(struct ExecCreateTaskPacket, {name})', offset)
               for name, _, offset in packet['fields']]
    checks += [('sizeof(struct ExecDosWriteArgs)', 12),
               ('offsetof(struct ExecDosWriteArgs, file)', 0),
               ('offsetof(struct ExecDosWriteArgs, buffer)', 4),
               ('offsetof(struct ExecDosWriteArgs, length)', 8)]
    return checks


def files():
    tasks, ports, heap, gateway = (load(name) for name in
        ('tasks.json', 'ports.json', 'heap-v1.json', 'exec816-v1.json'))
    header = ['/* Generated by tools/generate_calypsi.py. */',
              '#ifndef EXEC816_ABI_H', '#define EXEC816_ABI_H',
              '#include <exec/ports.h>', '']
    constants = dict(ports['constants'], NT_TASK=tasks['node_type'])
    constants.update({'TS_' + k: v for k, v in tasks['states'].items()})
    constants.update({'MEMF_' + k: v for k, v in heap['flags'].items()})
    header += [f'#define {name} 0x{value:x}UL' for name, value in constants.items()]
    header += ['#endif', '']
    # Calypsi's frontend static_assert does not use its final far24 layout.
    # Check emitted target constants; this object is never linked into the demo.
    probe = ['/* Generated by tools/generate_calypsi.py. */', '#include <proto/exec.h>',
             '#include "create-task-packet.h"',
             '#include "dos-bridge.h"',
             '__attribute__((section("exec_layout")))', 'const UWORD ExecCLayout[] = {']
    probe += [f'    {expression},' for expression, _ in expected_layout()]
    probe += ['};', '']
    selectors = ['/* Generated by tools/generate_calypsi.py. */']
    for abi in (gateway, tasks, ports, heap):
        selectors += [f'#define EXEC_{name} {value}' for name, value in abi['services'].items()]
    assembly = ['; Generated by tools/generate_calypsi.py.',
                f'EXEC_COP .equ {gateway["cop_signature"]}',
                f'EXEC_PROFILE_TAG .equ {tasks["constants"]["PROFILE_TAG"]}', '']
    packet = ['/* Generated from abi/tasks.json; do not edit. */',
              '#ifndef EXEC_CREATE_TASK_PACKET_H', '#define EXEC_CREATE_TASK_PACKET_H',
              '#include <exec/types.h>', 'struct ExecCreateTaskPacket {']
    types = {'CSTRING': ('const char EXEC_PTR *', 3), 'LONGINT': ('LONG ', 4),
             'BYTE POINTER': ('void EXEC_PTR *', 3), 'LONGCARD': ('ULONG ', 4)}
    cursor = 0
    for name, kind, offset in tasks['create_packet']['fields']:
        if cursor < offset:
            packet.append(f'    UBYTE pad{cursor}[{offset-cursor}];')
        ctype, width = types[kind]
        packet.append(f'    {ctype}{name};')
        cursor = offset+width
    packet += ['};', '#endif', '']
    return {ROOT/'c/calypsi/create-task-packet.h': '\n'.join(packet),
            ROOT/'c/include/exec816/abi.h': '\n'.join(header),
            ROOT/'c/calypsi/layout-check.c': '\n'.join(probe),
            ROOT/'c/calypsi/selectors.h': '\n'.join(selectors)+'\n',
            ROOT/'c/calypsi/gateway.inc': '\n'.join(assembly)}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in files().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit('Stale C binding: ' + str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
