#!/usr/bin/env python3
"""Generate host and Action filesystem IDs from the common mount contract."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generate(check=False):
    spec = json.loads((ROOT/'abi/filesystems.json').read_text())
    formats = spec['formats']
    if spec['schema_version'] != 1 or len(set(formats.values())) != len(formats):
        raise ValueError('Invalid filesystem IDs')
    if any(type(value) is not int or not 1 <= value <= 255 for value in formats.values()):
        raise ValueError('Filesystem IDs must fit a byte')
    action = '; Generated by tools/generate_filesystem_formats.py.\nMODULE FSFORMATS\n'
    action += ''.join(f'PUBLIC CONST {name}={value}\n' for name, value in formats.items())+'ENDMODULE\n'
    host = '# Generated by tools/generate_filesystem_formats.py.\n'
    host += ''.join(f'{name} = {value}\n' for name, value in formats.items())
    host += f'DEFAULT = {spec["default"]}\nFORMATS = '+repr(tuple(formats.values()))+'\n'
    for path, text in ((ROOT/'lib/fs/fsformats.act', action), (ROOT/'tools/filesystem_formats.py', host)):
        if check:
            if not path.exists() or path.read_text() != text: raise ValueError('Stale generated file: '+str(path))
        else: path.write_text(text)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true')
    generate(parser.parse_args().check)
