#!/usr/bin/env python3
"""Generate private VDI layouts, inquiry data and emitted C layout checks."""
import argparse
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
ABI=json.loads((ROOT/'abi/vdi-client.json').read_text())


def records():
    sizes={'UWORD':2,'WORD':2,'BYTE':1,'UBYTE':1,'const WORD *':4,'struct DisplayGrant':32}
    result={}
    for name,fields in [('ExecVDIUnit',ABI['unit']),('ExecVDIWorkstation',ABI['workstation'])]:
        cursor=0;offsets={}
        for field,kind,*count in fields:
            offsets[field]=cursor;cursor+=sizes[kind]*(count[0] if count else 1)
        result[name]=dict(size=cursor,fields=offsets);sizes['struct '+name]=cursor
    return result


def expected_layout():
    result=[]
    for name,r in records().items():
        result.append((f'sizeof(struct {name})',r['size']))
        result.extend((f'offsetof(struct {name}, {f})',v) for f,v in r['fields'].items())
    return result


def files():
    prefix='/* Generated by tools/generate_vdi_client.py; do not edit. */\n'
    unit=prefix+'#ifndef EXEC816_VDI_UNIT_H\n#define EXEC816_VDI_UNIT_H\n#include <stdint.h>\n'
    unit+=''.join(f'#define EXEC_VDI_{k} {v}\n' for k,v in ABI['constants'].items())
    unit+='struct ExecVDIUnit {\n'
    unit_types={'WORD':'int16_t','UWORD':'uint16_t','const WORD *':'const int16_t *'}
    unit+=''.join(f'    {unit_types[k]} {n};\n' for n,k in ABI['unit'])
    unit+='};\nvoid GemVdiPaint(void *context);\n#endif\n'
    private=prefix+'#ifndef EXEC816_VDI_PRIVATE_H\n#define EXEC816_VDI_PRIVATE_H\n#include <exec816/aes.h>\n#include <exec/display.h>\n#include <exec816/vdi-unit.h>\nstruct ExecVDIWorkstation {\n'
    private+=''.join(f'    {k} {n}'+(f'[{c[0]}]' if c else '')+';\n' for n,k,*c in ABI['workstation'])
    private+='};\nBOOL ExecVDIClose(struct ExecAESContext *context);\n#endif\n'
    probe=prefix+'#include "vdi-private.h"\n__attribute__((section("exec_layout")))\nconst UWORD VDILayout[] = {\n'
    probe+=''.join('    '+expression+',\n' for expression,_ in expected_layout())+'};\n'
    inquiry=prefix+'static const WORD workoutInts[45] = {'+','.join(map(str,ABI['workout_ints']))+'};\n'
    inquiry+='static const WORD workoutPoints[12] = {'+','.join(map(str,ABI['workout_points']))+'};\n'
    assert len(ABI['workout_ints'])==45 and len(ABI['workout_points'])==12
    return {ROOT/'c/include/exec816/vdi-unit.h':unit,ROOT/'c/calypsi/vdi-private.h':private,
            ROOT/'c/calypsi/vdi-layout.c':probe,ROOT/'c/calypsi/vdi-inquiry.inc':inquiry}


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    for path,text in files().items():
        if args.check:
            if not path.exists() or path.read_text()!=text: raise SystemExit('Stale VDI file: '+str(path))
        else:path.write_text(text)
