#!/usr/bin/env python3
"""Generate native limits for the bounded C application file ABI."""
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def files():
    abi=json.loads((ROOT/'abi/c-program.json').read_text())
    pairs=[('VERSION',str(abi['version'])),('FILE_MAGIC','LONGCARD($'+format(int.from_bytes(abi['magic'].encode(),'little'),'x')+')'),
           ('HEADER_BYTES',str(abi['header_bytes'])),('SEGMENT_LIMIT',str(abi['segment_limit'])),
           ('SPAN_LIMIT','LONGCARD('+str(abi['span_limit'])+')'),('FILE_LIMIT','LONGCARD('+str(abi['file_limit'])+')'),
           ('LINK_BANK',str(abi['link_bank'])),('BANK_LIMIT',str(abi['max_banks']))]
    return {ROOT/'lib/dos/c-program-abi.inc':'; Generated by tools/generate_c_program.py from abi/c-program.json.\n'+
            ''.join('PUBLIC CONST '+name+'='+value+'\n' for name,value in pairs)}

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for path,content in files().items():
        if args.check:
            if not path.exists() or path.read_text()!=content:raise SystemExit('Stale C program ABI: '+str(path))
        else:path.write_text(content)
