#!/usr/bin/env python3
"""Generate the small C binding's constants and layout checks from Exec's ABI."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def load(name):
    return json.loads((ROOT / 'abi' / name).read_text())


def expected_layout():
    checks = [(f'sizeof({kind})', size) for kind, size in
              [('BYTE', 1), ('WORD', 2), ('LONG', 4), ('BPTR', 4), ('APTR', 4),
               ('void EXEC_PTR *', 3), ('struct Node', 11), ('struct List', 11),
               ('struct MinNode', 6), ('struct MinList', 9)]]
    records = {**load('ports.json')['records'], **load('io.json')['records'],
               'Task': load('tasks.json')['task']}
    for name, record in records.items():
        checks.append((f'sizeof(struct {name})', record['size']))
        checks += [(f'offsetof(struct {name}, {field})', offset) for field, _, offset in record['fields']]
    packet = load('tasks.json')['create_packet']
    checks.append(('sizeof(struct ExecCreateTaskPacket)', packet['size']))
    checks += [(f'offsetof(struct ExecCreateTaskPacket, {name})', offset)
               for name, _, offset in packet['fields']]
    checks += [('sizeof(struct ExecDosWriteArgs)', 12),
               ('offsetof(struct ExecDosWriteArgs, file)', 0),
               ('offsetof(struct ExecDosWriteArgs, buffer)', 4),
               ('offsetof(struct ExecDosWriteArgs, length)', 8)]
    lease = load('tasks.json')['lease']
    checks.append(('sizeof(struct TaskLease)', lease['size']))
    checks += [(f'offsetof(struct TaskLease, {name})', offset) for name,_,offset in lease['fields']]
    checks += [('sizeof(struct ExecRetainTaskPacket)', 6),
               ('offsetof(struct ExecRetainTaskPacket, lease)', 3)]
    for name in ('DateStamp','FileInfoBlock'):
        record=load('dos.json')['records'][name]
        checks.append((f'sizeof(struct {name})',record['size']))
        checks += [(f'offsetof(struct {name}, {field})',offset) for field,_,offset in record['fields']]
    return checks


def files():
    tasks, ports, heap, gateway = (load(name) for name in
        ('tasks.json', 'ports.json', 'heap-v1.json', 'exec816-v1.json'))
    header = ['/* Generated by tools/generate_calypsi.py. */',
              '#ifndef EXEC816_ABI_H', '#define EXEC816_ABI_H',
              '#include <exec/ports.h>', '']
    constants = dict(ports['constants'], NT_TASK=tasks['node_type'])
    constants.update({'TS_' + k: v for k, v in tasks['states'].items()})
    constants.update({'MEMF_' + k: v for k, v in heap['flags'].items()})
    header += [f'#define {name} 0x{value:x}UL' for name, value in constants.items()]
    header += ['#endif', '']
    # Calypsi's frontend static_assert does not use its final far24 layout.
    # Check emitted target constants; this object is never linked into the demo.
    probe = ['/* Generated by tools/generate_calypsi.py. */', '#include <proto/exec.h>',
             '#include "create-task-packet.h"',
             '#include "dos-bridge.h"', '#include <dos/dos.h>',
             '#include "tasklease-packet.h"',
             '__attribute__((section("exec_layout")))', 'const UWORD ExecCLayout[] = {']
    probe += [f'    {expression},' for expression, _ in expected_layout()]
    probe += ['};', '']
    selectors = ['/* Generated by tools/generate_calypsi.py. */']
    for abi in (gateway, tasks, ports, heap):
        selectors += [f'#define EXEC_{name} {value}' for name, value in abi['services'].items()]
    assembly = ['; Generated by tools/generate_calypsi.py.',
                f'EXEC_COP .equ {gateway["cop_signature"]}',
                f'EXEC_PROFILE_TAG .equ {tasks["constants"]["PROFILE_TAG"]}', '']
    packet = ['/* Generated from abi/tasks.json; do not edit. */',
              '#ifndef EXEC_CREATE_TASK_PACKET_H', '#define EXEC_CREATE_TASK_PACKET_H',
              '#include <exec/types.h>', 'struct ExecCreateTaskPacket {']
    types = {'CSTRING': ('const char EXEC_PTR *', 3), 'LONGINT': ('LONG ', 4),
             'BYTE POINTER': ('void EXEC_PTR *', 3), 'LONGCARD': ('ULONG ', 4)}
    cursor = 0
    for name, kind, offset in tasks['create_packet']['fields']:
        if cursor < offset:
            packet.append(f'    UBYTE pad{cursor}[{offset-cursor}];')
        ctype, width = types[kind]
        packet.append(f'    {ctype}{name};')
        cursor = offset+width
    packet += ['};', '#endif', '']
    lease = ['/* Generated from abi/tasks.json; do not edit. */',
             '#ifndef EXEC_TASKLEASE_H', '#define EXEC_TASKLEASE_H',
             '#include <exec/tasks.h>', 'struct TaskLease {']
    lease_types = {'Task POINTER':'struct Task EXEC_PTR *', 'BYTE':'UBYTE ',
                   'LONGCARD':'ULONG ', 'ADDRESS':'void EXEC_PTR *'}
    lease += [f'    {lease_types[kind]}{name};' for name,kind,_ in tasks['lease']['fields']]
    lease += ['};', 'UBYTE EXEC_CALL RetainTask(struct Task *task, struct TaskLease *lease);',
              'UBYTE EXEC_CALL ReleaseTask(struct TaskLease *lease);', '#endif', '']
    retain_packet = '''/* Generated from abi/tasks.json; do not edit. */
#ifndef EXEC_TASKLEASE_PACKET_H
#define EXEC_TASKLEASE_PACKET_H
#include <exec/tasklease.h>
struct ExecRetainTaskPacket {
    struct Task EXEC_PTR *task;
    struct TaskLease EXEC_PTR *lease;
};
#endif
'''
    lifetime = '''/* Generated by tools/generate_calypsi.py; do not edit. */
UBYTE EXEC_CALL RetainTask(struct Task *task, struct TaskLease *lease)
{
    struct ExecRetainTaskPacket args;
    if ((ULONG)task > 0xffffffUL || (ULONG)lease > 0xffffffUL)
        return 0;
    args.task = task;
    args.lease = lease;
    return (UBYTE)_ExecPacket(EXEC_RETAIN_TASK, &args);
}

UBYTE EXEC_CALL ReleaseTask(struct TaskLease *lease)
{
    struct PointerPacket args;
    if ((ULONG)lease > 0xffffffUL)
        return 0;
    args.pointer = lease;
    return (UBYTE)_ExecPacket(EXEC_RELEASE_TASK, &args);
}
'''
    dos=['/* Generated from abi/dos.json by tools/generate_calypsi.py. */',
         '#ifndef EXEC_DOS_H','#define EXEC_DOS_H','#include <exec/types.h>']
    dos += [f'#define {name} ({value}L)' for name,value in
            {**load('dos.json')['constants'],**load('dos.json')['dos_errors']}.items()]
    for name in ('DateStamp','FileInfoBlock'):
        dos.append('struct '+name+' {')
        for field,kind,offset in load('dos.json')['records'][name]['fields']:
            if kind.startswith('BYTE['):decl='UBYTE '+field+kind[4:]
            else:decl={'LONGINT':'LONG','CARD':'UWORD','DateStamp':'struct DateStamp'}[kind]+' '+field
            dos.append('    '+decl+';')
        dos.append('};')
    dos += ['#endif','']
    return {ROOT/'c/include/dos/dos.h':'\n'.join(dos),
            ROOT/'c/include/exec/tasklease.h' :'\n'.join(lease),
            ROOT/'c/calypsi/tasklease-packet.h':retain_packet,
            ROOT/'c/calypsi/tasklease.inc':lifetime,
            ROOT/'c/calypsi/create-task-packet.h': '\n'.join(packet),
            ROOT/'c/include/exec816/abi.h': '\n'.join(header),
            ROOT/'c/calypsi/layout-check.c': '\n'.join(probe),
            ROOT/'c/calypsi/selectors.h': '\n'.join(selectors)+'\n',
            ROOT/'c/calypsi/gateway.inc': '\n'.join(assembly)}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in files().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit('Stale C binding: ' + str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
