#!/usr/bin/env python3
"""Generate the VBI timer's public records and fixed upper storage contract."""
import argparse
import json
from pathlib import Path
from generate_memory import ROOT, require
from generate_heap import write

ABI = json.loads((ROOT/'abi/timer-device.json').read_text())
HEADER = '; Generated by tools/generate_timer_device.py; do not edit.\n'


def constants(a=ABI):
    require(a['abi'] == 'exec816.timer.device' and a['revision'] == 1, 'Unsupported timer ABI')
    require(a['constants']==dict(UNIT_VBLANK=1,TR_ADDREQUEST=9,TD_READCLOCK=10,
            TD_WAITUNTIL=11,TIMERERR_QUEUEFULL=1,TIMERERR_OVERFLOW=2,
            TIMERERR_CLOCK=3,TIMERERR_BADTIME=4), 'Invalid timer commands/errors')
    require(set(a['records'])=={'TimerRequest','TimerClockRequest'}, 'Invalid timer records')
    require(a['state_bytes']==512, 'Invalid timer state reservation')
    require(a['open_capacity'] == 8 and a['pending_capacity'] == 16
            and a['completion_budget'] == 4, 'Unsupported timer capacities')
    require(a['pending_stride'] == 16 and a['open_stride'] == 24, 'Invalid timer slot size')
    require(a['fields'] == dict(CLOCK_HI=0,CLOCK_LO=4,VERSION=8,FAULT=9,RATE=10,
            OPENS=16,GENERATION=18,EDIT=20,ARMED=21,HEAD=22,COUNT=23,
            PENDING=32,OPEN=288,NAME=480), 'Invalid timer state layout')
    native = json.loads((ROOT/'abi/native-interrupts.json').read_text())
    require(a['state_offset'] >= native['state_offset']+native['state_bytes']
            and a['state_offset']+a['state_bytes'] <= native['code_offset'],
            'Timer state overlaps native storage')
    c = dict(a['constants'], STATE_OFFSET=a['state_offset'], STATE_BYTES=a['state_bytes'],
             OPEN_CAPACITY=a['open_capacity'], PENDING_CAPACITY=a['pending_capacity'],
             COMPLETION_BUDGET=a['completion_budget'], PENDING_STRIDE=a['pending_stride'], OPEN_STRIDE=a['open_stride'])
    for name, record in a['records'].items():
        expected=([['tr_Request','IORequest',0],['seconds','LONGCARD',26],['microseconds','LONGCARD',30]]
                  if name=='TimerRequest' else [['tc_Request','IORequest',0],['ticks_hi','LONGCARD',26],
                       ['ticks_lo','LONGCARD',30],['ticks_per_second','LONGCARD',34]])
        require(record['fields']==expected, 'Invalid timer request fields')
        cursor = 0
        for field, kind, offset in record['fields']:
            require(offset == cursor, 'Invalid timer field offset')
            cursor += {'IORequest':26,'LONGCARD':4}[kind]
            c[name.upper()+'_'+field.upper()] = offset
        require(record['size'] == cursor, 'Invalid timer record size')
        c[name.upper()+'_SIZE'] = cursor
    return c


def types():
    constants()
    return HEADER+''.join(f'PUBLIC CONST {k}={v}\n' for k,v in ABI['constants'].items())+''.join(
        'PUBLIC TYPE '+n+'=[\n'+''.join('  '+('EXEC.IORequest' if k=='IORequest' else k)+' '+f+'\n'
            for f,k,_ in r['fields'])+']\n' for n,r in ABI['records'].items())


def assembly():
    return HEADER+''.join(f'TI_{k} = ${v:x}\n' for k,v in constants().items())+'TI_BASE = T_BASE+TI_STATE_OFFSET\n'+''.join(
        f'TI_{k} = TI_BASE+{v}\n' for k,v in ABI['fields'].items())


def c_header():
    constants()
    text='/* Generated by tools/generate_timer_device.py; do not edit. */\n#ifndef DEVICES_TIMER_H\n#define DEVICES_TIMER_H\n#include <exec/io.h>\n'
    text+=''.join(f'#define {k} ({v})\n' for k,v in ABI['constants'].items())
    for name,record in ABI['records'].items():
        text+='\nstruct '+name+' {\n'+''.join(
            f'    {"struct IORequest" if kind=="IORequest" else "ULONG"} {field};\n'
            for field,kind,_ in record['fields'])+'};\n'
    return text+'#endif\n'


def generate(output, base, memory):
    require((ROOT/'lib/io/timer-types.inc').read_text() == types(), 'Stale timer records')
    require((ROOT/'platform/altirraos/timer-device.inc').read_text() == assembly(), 'Stale timer assembly')
    start=base+ABI['state_offset']
    memory['timer_device_storage']=dict(BASE=start,BYTES=ABI['state_bytes'])
    text=HEADER+'MODULE TIMERMETA\n'+f'PUBLIC CONST BASE=${start:x}\n'
    text+=''.join(f'PUBLIC CONST {k}=${start+v:x}\n' for k,v in ABI['fields'].items())
    text+=''.join(f'PUBLIC CONST {k}={v}\n' for k,v in constants().items() if k in (
        'OPEN_CAPACITY','PENDING_CAPACITY','OPEN_STRIDE','PENDING_STRIDE'))
    write(Path(output)/'timermeta.act',text+'ENDMODULE\n',False)


if __name__ == '__main__':
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--check',action='store_true')
    args=p.parse_args()
    write(ROOT/'lib/io/timer-types.inc',types(),args.check)
    write(ROOT/'platform/altirraos/timer-device.inc',assembly(),args.check)
    write(ROOT/'c/include/devices/timer.h',c_header(),args.check)
