#!/usr/bin/env python3
"""Generate Task layouts, native call bindings and per-image kernel modules."""
from library_paths import library_file, read_source
import argparse
import json
import re
from pathlib import Path

from os_boundary import ROOT, require
import generate_heap
import generate_ports
import generate_io

ABI = json.loads((ROOT/'abi/tasks.json').read_text())
HEADER = '; Generated by tools/generate_tasks.py; do not edit.\n'
RESULTS = {0:'None', 1:'Some(NativeResult(A8ZeroExtended))',
           3:'Some(NativeResult(A16X8ZeroExtended))', 4:'Some(NativeResult(A16X16))'}
WIDTHS = {'EXECLISTS.Node':(11,1), 'EXECLISTS.List':(11,1),
          'EXECLISTS.MinList':(9,1), 'EXECLISTS.MinNode':(6,1), 'BYTE':(1,1), 'ADDRESS':(3,2),
          'CARD':(2,2), 'LONGCARD':(4,2), 'Task POINTER':(3,1),
          'TaskControl POINTER':(3,1), 'CSTRING':(3,1), 'LONGINT':(4,2), 'BYTE POINTER':(3,1)}
SIGNALS = ('AllocSignal','FreeSignal','SetSignal','Signal','Wait')
SELECTORS = dict(zip(SIGNALS, ('ALLOC_SIGNAL','FREE_SIGNAL','SET_SIGNAL','SIGNAL','WAIT')))
SELECTORS.update(CreateTask='CREATE_TASK',RetainTask='RETAIN_TASK',ReleaseTask='RELEASE_TASK',RegisterResident='REGISTER_RESIDENT',UnregisterResident='UNREGISTER_RESIDENT')


def fields(layout, prefix):
    cursor = 0
    result = {}
    for name, kind, offset in layout['fields']:
        width, alignment = WIDTHS[kind]
        cursor = (cursor+alignment-1)//alignment*alignment
        require(cursor == offset, 'Invalid '+prefix+' layout: '+name)
        result[prefix+'_'+name.upper()] = offset
        cursor += width
    require((cursor+1)//2*2 == layout['size'], 'Invalid '+prefix+' size')
    return result


def constants(abi=ABI):
    require(abi['task']['size'] == 62, 'Incompatible Task size')
    c = {'VERSION':abi['version'], 'TASK_SIZE':abi['task']['size'], 'NT_TASK':abi['node_type']}
    c.update(fields(abi['task'], 'TASK'))
    c.update(fields(abi['context'], 'TCB'))
    c.update(fields(abi['lease'], 'LEASE'))
    c['LEASE_SIZE']=abi['lease']['size']
    c.update(fields(abi['create_packet'], 'CREATE'))
    c['CREATE_BYTES']=abi['create_packet']['size']
    c.update(fields(abi['metadata']['header'],'META'))
    c.update(fields({'size':abi['constants']['BINDING_BYTES'],
                     'fields':abi['metadata']['binding_fields']}, 'BINDING'))
    for group, prefix in [('services','SERVICE'), ('states','TS'), ('errors','ERROR'),
                           ('context_states','STATE'), ('wait_reasons','WAIT')]:
        values = list(abi[group].values())
        require(len(set(values)) == len(values), 'Duplicate task '+group)
        c.update({f'{prefix}_{name}':value for name,value in abi[group].items()})
    for path in (ROOT/'abi').glob('*.json'):
        if path.name == 'tasks.json':
            continue
        other = json.loads(path.read_text())
        selectors = set(other.get('services', {}).values()) | set(other.get('private_services', {}).values())
        require(not set(abi['services'].values()) & selectors, 'Task service collision: '+path.name)
    c.update({'FRAME_'+name.upper():value for name,value in abi['compiler_frame'].items()})
    c.update(abi['constants'])
    require(abi['raw']['profile_tag']['value'] == c['PROFILE_TAG'] >> 8, 'Task packet profile tag disagrees with its generated value')
    c['PUBLIC_CONTEXT_BYTES'] = c['CAPACITY']*c['SIZE']
    require(c['MANAGED_STRIDE'] >= c['TASK_SIZE'] and c['MANAGED_STRIDE'] % 2 == 0, 'Invalid managed Task stride')
    require(abi['context']['size'] == c['SIZE'] == 1 << c['SHIFT'], 'Invalid context stride')
    return c


def storage(memory):
    """Reserve one explicit, relocatable upper-bank arena; reject image overlap later."""
    c = constants()
    if 'task_capacity' in memory:
        c.update(CAPACITY=memory['task_capacity'],IDLE=memory['task_capacity'],PUBLIC_CONTEXT_BYTES=memory['task_capacity']*c['SIZE'])
    require(memory['usable_banks'], 'Tasks need an upper metadata bank')
    base = max(memory['usable_banks']) << 16
    c['BASE'] = base
    cursor = base+(c['IDLE']+1)*c['SIZE']
    for name,size,align in [('READY',9,1), ('WAKE',9,1), ('LIVE',1,1),
                            ('TIMER_PENDING',1,1), ('IDLE_RUNS',2,2), ('ENTRY_COUNT',2,2),
                            ('CREATED',2,2), ('ENTRIES',3*c['ENTRY_CAPACITY'],1),
                            ('WRITABLE_COUNT',2,2), ('WRITABLE_POINTER',3,1),
                            ('SERIAL_BINDING',c['BINDING_BYTES'],2), ('ROOT',c['TASK_SIZE'],2), ('SERIAL_STATE',4,1), ('SLEEPERS',1,1)]:
        cursor = (cursor+align-1)//align*align
        c[name] = cursor
        cursor += size
    c['MANAGED'] = (cursor+1)//2*2
    c['MANAGED_BYTES'] = (c['CAPACITY']-1)*c['MANAGED_STRIDE']
    cursor = c['MANAGED']+c['MANAGED_BYTES']
    c['METADATA_END'] = (cursor+63)//64*64
    c['METADATA_BYTES'] = c['METADATA_END']-base
    c.update(WAKE_PENDING=0x203a, IRQ_ALLOW=0x203b)
    require(c['METADATA_BYTES'] <= 0x800, 'Task metadata overlaps SIO descriptor')
    return c


def task_type(public=False):
    return ('PUBLIC ' if public else '')+'TYPE Task=[\n'+''.join(
        f'  {kind} {name}\n' for name,kind,_ in ABI['task']['fields'])+']\n'


def lease_type(public=False):
    return ('PUBLIC ' if public else '')+'TYPE TaskLease=[\n'+''.join(f'  {kind} {name}\n' for name,kind,_ in ABI['lease']['fields'])+']\n'

def public_api():
    constants()
    return HEADER+task_type(True)+lease_type(True)+''.join(f'PUBLIC CONST TS_{name}=${value:x}\n'
        for name,value in ABI['states'].items())+f'PUBLIC CONST NT_TASK=${ABI["node_type"]:x}\n'+\
        f'PUBLIC CONST TASK_SIZE=${ABI["task"]["size"]:x}\nPUBLIC CONST TASK_ABI_VERSION=${ABI["version"]:x}\n'


def declarations():
    return '''PUBLIC EXTERNAL Task POINTER FUNC CreateTask(CSTRING name LONGINT priority PROC POINTER entry() LONGCARD stackSize)
PUBLIC EXTERNAL Task POINTER FUNC AddTask(Task POINTER task PROC POINTER initialPC() PROC POINTER finalPC())
PUBLIC EXTERNAL PROC RemTask(Task POINTER task)
PUBLIC EXTERNAL Task POINTER FUNC FindTask(BYTE POINTER name)
PUBLIC EXTERNAL BYTE FUNC SetTaskPri(Task POINTER task BYTE priority)
PUBLIC EXTERNAL PROC Forbid()
PUBLIC EXTERNAL PROC Permit()
PUBLIC EXTERNAL BYTE FUNC AllocSignal(BYTE number)
PUBLIC EXTERNAL PROC FreeSignal(BYTE number)
PUBLIC EXTERNAL LONGCARD FUNC SetSignal(LONGCARD signals LONGCARD mask)
PUBLIC EXTERNAL PROC Signal(Task POINTER task LONGCARD signals)
PUBLIC EXTERNAL LONGCARD FUNC Wait(LONGCARD mask)
PUBLIC EXTERNAL BYTE FUNC RetainTask(Task POINTER task TaskLease POINTER lease)
PUBLIC EXTERNAL BYTE FUNC ReleaseTask(TaskLease POINTER lease)
PUBLIC EXTERNAL BYTE FUNC RegisterResident(LONGCARD stopMask)
PUBLIC EXTERNAL BYTE FUNC UnregisterResident()
'''


def check_routine(routine, name):
    expected = ABI['imports'][name]
    args = [{k:a[k] for k in ('alignment','offset','size')} for a in routine['arguments']]
    require(args == expected['arguments'] and routine['outgoing_bytes'] == expected['outgoing_bytes'],
            f'Task {name} native arguments changed')
    if 'result_bytes' in routine:
        require(routine['result_bytes'] == expected['result_bytes'], f'Task {name} result changed')
    else:
        require(routine['result'] == RESULTS[expected['result_bytes']], f'Task {name} result changed')


def gateway():
    text = HEADER+'; Native M=X=0. Packet remains on the calling task stack.\n.a16\n.i16\n'
    for name in (*SIGNALS, 'CreateTask', 'RetainTask','ReleaseTask','RegisterResident','UnregisterResident'):
        label = 'tasks_'+SELECTORS[name].lower()
        text += f'''.export {label}, {label}_end
{label}:
    tsc
    clc
    adc #4
    tax
    ldy #T_PROFILE_TAG
    lda #T_SERVICE_{SELECTORS[name]}
    cop $50
    rtl
{label}_end:
'''
    return text


def generate(output, memory=None):
    output = Path(output)
    output.mkdir(parents=True,exist_ok=True)
    c = constants() if memory is None else storage(memory)
    text = HEADER+task_type()+lease_type()+''.join(f'CONST T_{name}=${value:x}\n' for name,value in c.items())
    text += 'TYPE CreateArguments=[\n'+''.join(f'  {kind} {name}\n' for name,kind,_ in ABI['create_packet']['fields'])+']\n'
    text += 'TYPE TaskControl=[\n'+''.join(f'  {kind} {name}\n' for name,kind,_ in ABI['context']['fields'])+']\n'
    text += 'TYPE SignalBinding=[\n'+''.join(f'  {kind} {name}\n' for name,kind,_ in ABI['metadata']['binding_fields'])+']\n'
    (output/'task-types.inc').write_text(text)
    (output/'task-abi.inc').write_text(HEADER+''.join(f'T_{name} = ${value:06x}\n' for name,value in c.items()))
    (output/'signal-gateway.inc').write_text(gateway())
    return c


def generate_kernel(output, labels=None, entries=(), writable=(0,0), *, memory):
    output = Path(output)
    c = generate(output,memory)
    c.update(RETURN=(labels or {}).get('native_return',0x3000)-1,
             TASK_START=(labels or {}).get('general_task_start',0x3a00),
             IDLE_ENTRY=(labels or {}).get('idle_start',0x3a00))
    require(len(entries) <= c['ENTRY_CAPACITY'], 'Too many task entries')
    (output/'tasks.inc').write_text(HEADER+''.join(f'T_{name} = ${value:06x}\n' for name,value in c.items()))
    action = (output/'task-types.inc').read_text()+''.join(
        f'CONST T_{name}=${c[name]:x}\n' for name in ('RETURN','TASK_START','IDLE_ENTRY'))
    action += 'TYPE TaskMetadata=[\n'+''.join(f'  {kind} {name}\n' for name,kind,_ in ABI['metadata']['header']['fields'])+']\n'
    action += 'TYPE WritableRange=[ADDRESS base SIZE bytes]\n'
    pools=memory.get('task_pools',ABI['pools'])
    action += 'CARD ARRAY poolSize=['+' '.join(str(p.get('stack_bytes',1536)) for p in pools)+']\n'
    action += 'CARD ARRAY poolDpBytes=['+' '.join(str(p.get('dp_reserved_bytes',288)) for p in pools)+']\n'
    action += 'CARD ARRAY poolDp=['+' '.join(str(p['dp']) for p in pools)+']\n'
    action += 'CARD ARRAY poolStack=['+' '.join(str(p['stack_base']) for p in pools)+']\n'
    (output/'tasks-action.inc').write_text(action)
    bound = '.segment "TASK_BINDINGS"\n.export task_bindings\ntask_bindings:\n'
    bound += f'.word {len(entries)},0\n'+''.join(f'.faraddr ${entry:06x}\n' for entry in entries)
    bound += f'.res {(c["ENTRY_CAPACITY"]-len(entries))*3},0\n.word {writable[0]}\n.faraddr ${writable[1]:06x}\n.byte 0\n'
    (output/'tasks-bindings.inc').write_text(bound)


def validate_pools(memory):
    """Pools may reclaim only the dead INITAD loader/staging after Adopt."""
    reserved = list(memory['regions'].items())
    spans = [(0x2d00, 0x2df0, 'task records')]
    for i, pool in enumerate(ABI['pools']):
        spans += [(pool['dp']-16, pool['dp']+272, f'dp{i}'),
                  (pool['stack_base']-16, pool['stack_base']+1552, f'stack{i}')]
    require(memory['profile']['image_near'] == [0x8800, 0x9000], 'Task near layout changed')
    for a, b, name in spans:
        for other, (x, y) in reserved:
            if a < y and x < b:
                require(other in ('task0-dp', 'task1-dp', 'task0-stack', 'task1-stack', 'loader', 'staging'),
                        f'Task pool {name} overlaps {other}')
    for i, (a, b, _) in enumerate(spans):
        require(all(b <= x or a >= y for x, y, _ in spans[i+1:]), 'Task pools overlap')
    # Every new permanent reservation must also be excluded from image writes.
    memory['task_pools'] = ABI['pools']
    memory['reclaimed_after_adopt'] = ['loader', 'staging']



def validate_memory(memory):
    if 'task_capacity' not in memory: validate_pools(memory)
    c=storage(memory)
    require(c['WRITABLE_POINTER']+4 == c['ENTRY_COUNT']+c['BINDINGS_BYTES'], 'Invalid binding extent')


def policy_modules(output, policy_probe=0, memory=None, manual_wake=False, irq_probe=0, io_test_device=False, dos_test=False, dos_system=False, console=False, sio_request_probe=False,sio_lifetime_probe=False):
    if memory is None:
        from generate_memory import layout
        memory=layout()
        generate_heap.reserve_metadata(memory)
        generate_ports.reserve_metadata(memory)
    from generate_dos import generate as generate_dos, check_public as check_dos
    check_dos()
    generate_dos(output)
    from generate_dos import reserve_metadata as reserve_dos, registration_include as register_dos
    if 'dos_storage' not in memory:reserve_dos(memory,memory.get('task_capacity',ABI['constants']['CAPACITY']))
    register_dos(output,memory)
    generate_ports.generate(output)
    generate_io.generate(output)
    generate_io.registration_include(output,memory,io_test_device)
    generate_ports.registration_include(output,memory)
    pools=(memory or {}).get('task_pools',ABI['pools'])
    capacity=(memory or {}).get('task_capacity',ABI['constants']['CAPACITY'])
    directory=Path(output)/'task-kernel';directory.mkdir(parents=True,exist_ok=True)
    from generate_process import state_source, reserve_metadata as reserve_process, check_public as check_process
    check_process()
    if 'process_storage' not in memory:reserve_process(memory,capacity)
    (directory/'processstate.act').write_text(state_source(capacity,memory['process_storage']['BASE']))
    inspection = read_source(ROOT/'lib/exec/taskinspect.act')
    layout = storage(memory)
    task_memory=read_source(ROOT/'lib/exec/taskmemory.act').replace(
        '; Generated image binding addresses go here.',
        f'CONST COUNT=${layout["WRITABLE_COUNT"]:x}, RANGES=${layout["WRITABLE_POINTER"]:x}')
    (directory/'taskmemory.act').write_text(task_memory)
    inspection = inspection.replace('; Generated layout constants go here.',
        f'PUBLIC CONST CAPACITY={capacity}\n'+
        ''.join(f'PUBLIC CONST STATE_{name}={value}\n' for name,value in ABI['context_states'].items())+
        ''.join(f'CONST {name}=${value:x}\n' for name,value in {
            'TABLE_BASE':layout['BASE'], 'RECORD_SHIFT':layout['SHIFT'],
            'ITEM_OFFSET':layout['TCB_ITEM'], 'STATE_OFFSET':layout['TCB_STATE']}.items()))
    (directory/'taskinspect.act').write_text(inspection)
    devices = read_source(ROOT/'lib/io/deviceinspect.act').replace(
        '; Generated console address goes here.',
        f'CONST CONSOLE_BASE=${memory["console_storage"]["BASE"] if console else 0:x}')
    (directory/'deviceinspect.act').write_text(devices)
    (directory/'exec.act').write_text('MODULE EXEC\nUSE EXECLISTS\nUSE TASKPOLICY\n'+public_api()+declarations()+generate_heap.public_api()+generate_heap.declarations()+generate_ports.public_api()+generate_ports.declarations()+generate_io.public_api()+generate_io.declarations()+'''
PUBLIC EXTERNAL CARD FUNC Version()
PUBLIC EXTERNAL PROC Yield()
PUBLIC EXTERNAL PROC Poll()
ENDMODULE
''')
    if dos_system:
        from generate_dos import HEADER, public_api as dos_api
        (directory/'dos.act').write_text(HEADER+'MODULE DOS\nUSE DOSCALLS\nUSE DOSCLIENT\n'+dos_api()+'INCLUDE "'+str(ROOT/'lib/dos/dos-implementation.inc')+'"\nENDMODULE\n')
    elif dos_test:
        from generate_dos import HEADER, public_api as dos_api, DECLARATIONS
        (directory/'dos.act').write_text(HEADER+'MODULE DOS\nUSE DOSCLIENT\n'+dos_api()+''.join('PUBLIC EXTERNAL '+v+'\n' for k,v in DECLARATIONS.items() if k not in ('IoErr','ReleaseContext'))+'PUBLIC LONGINT FUNC IoErr()\nRETURN(DOSCLIENT.IoErr())\nPUBLIC LONGINT FUNC ReleaseContext()\nRETURN(DOSCLIENT.ReleaseContext())\nENDMODULE\n')
    (directory/'exectasks.act').write_text('MODULE EXECTASKS\nPUBLIC CONST ERROR_LOCK=$ff12\nPUBLIC CONST ERROR_TICKS=$ff18\nPUBLIC EXTERNAL CARD FUNC Sleep(CARD ticks)\nENDMODULE\n')
    (directory/'taskstacks.act').write_text('MODULE TASKSTACKS\n'+f'PUBLIC CONST CAPACITY={capacity}\n'+''.join(
        f'PUBLIC CONST LOWER{i}=${p["stack_base"]:x}\nPUBLIC CONST UPPER{i}=${p["stack_base"]+p.get("stack_bytes",1536):x}\n'
        for i,p in enumerate(pools[:capacity]))+
        'CARD ARRAY lower=['+' '.join(str(p['stack_base']) for p in pools[:capacity])+']\n'+
        'CARD ARRAY upper=['+' '.join(str(p['stack_base']+p.get('stack_bytes',1536)) for p in pools[:capacity])+']\n'+
        'PUBLIC CARD FUNC StackLower(BYTE slot)\nRETURN(lower(slot))\nPUBLIC CARD FUNC StackUpper(BYTE slot)\nRETURN(upper(slot))\nENDMODULE\n')
    driver=read_source(ROOT/'lib/io/siodriver.act')
    if sio_request_probe:
        requests=read_source(ROOT/'lib/io/sio-requests.inc')
        claim='  bus.active=request\n  bus.phase=0\n  bus.cancelled=0\n  cancel^=0\n'
        reply='  bus.active=EXEC.IORequest POINTER(0)\n  bus.phase=0\n  bus.cancelled=0\n'
        require(requests.count(claim)==requests.count(reply)==1,'Stale SIO ownership checkpoints')
        requests=requests.replace(claim,'  RequestCheckpoint(3)\n'+claim).replace(reply,reply+'  RequestCheckpoint(5)\n')
        probe=directory/'sio-requests-probe.inc'
        probe.write_text(read_source(ROOT/'tests/programs/sio_request_probe.inc')+requests)
        driver=driver.replace(str((ROOT/'lib/io/sio-requests.inc').resolve()),str(probe.resolve()))
    if sio_lifetime_probe:
        lifetime=read_source(ROOT/'lib/io/sio-lifetime.inc')
        checkpoint='    WaitChange(bus,@waiter)\n    Reap(bus)\n'
        require(lifetime.count(checkpoint)==1,'Stale SIO stop-return checkpoint')
        lifetime=lifetime.replace(checkpoint,'    WaitChange(bus,@waiter)\n    LifecycleCheckpoint(11)\n    Reap(bus)\n')
        probe=directory/'sio-lifetime-probe.inc'
        probe.write_text(read_source(ROOT/'tests/programs/sio_lifetime_probe.inc')+lifetime)
        driver=driver.replace(str((ROOT/'lib/io/sio-lifetime.inc').resolve()),str(probe.resolve()))
        before='    okay=EXECPRODUCER.Bind(EXEC.FindTask(BYTE POINTER(0)),LONGCARD($40000000))\n'
        after='  SIOADAPTER.Shutdown()\n  EXECPRODUCER.Release()\n  EXECPRODUCER.Drain()\n'
        require(driver.count(before)==driver.count(after)==1,'Stale SIO binding checkpoints')
        driver=driver.replace(before,'    LifecycleCheckpoint(7)\n'+before).replace(after,after+'  LifecycleCheckpoint(9)\n')
    for filename in ('sio-storage-action.inc','io-storage-action.inc'):
        driver=driver.replace('"'+filename+'"','"'+str(Path(output)/filename)+'"')
    (directory/'siodriver.act').write_text(driver)
    streams=read_source(ROOT/'lib/dos/dosraw.act')
    streams=streams.replace('"dos-storage-action.inc"','"'+str(Path(output)/'dos-storage-action.inc')+'"')
    (directory/'dosraw.act').write_text(streams)
    registry=read_source(ROOT/'lib/dos/doscore.act')
    registry=registry.replace('"dos-storage-action.inc"','"'+str(Path(output)/'dos-storage-action.inc')+'"')
    (directory/'doscore.act').write_text(registry)
    policy_includes = {name: Path(output)/name for name in (
        'tasks-action.inc', 'ports-action.inc', 'port-packets.inc',
        'ports-storage-action.inc', 'io-action.inc', 'io-storage-action.inc',
        'sio-storage-action.inc', 'dos-action.inc', 'dos-storage-action.inc')}
    policy_includes.update({name: directory/name for name in (
        'task-console.inc', 'task-signals.inc', 'task-wakes.inc')})
    policy=read_source(ROOT/'lib/exec/taskpolicy.act', policy_includes)
    init='PROC InitResidentStorage()\n  BYTE POINTER bytes\n  CARD POINTER name\n  CARD i\n  bytes=BYTE POINTER(ADDRESS(IS_BASE+64))\n  FOR i=0 TO 191 DO bytes(i)=0 OD\n  name=CARD POINTER(ADDRESS(IS_BASE+224))\n  name(0)=$6973 name(1)=$2e6f name(2)=$6564 name(3)=$6976 name(4)=$6563 name(5)=0\nRETURN\n'
    policy=policy.replace('PUBLIC CARD FUNC Init()',init+'\nPUBLIC CARD FUNC Init()')
    if console:
        for module in ('consoledriver','consoleinput','consoledisplay','consoleforeground','consolewindows'):
            driver=read_source(library_file(module+'.act'))
            driver=driver.replace('"console-storage-action.inc"','"'+str(Path(output)/'console-storage-action.inc')+'"')
            (directory/(module+'.act')).write_text(driver)
        console_policy=read_source(ROOT/'lib/console/task-console.inc')
        for name in ('console-storage-action.inc','console-action.inc'):
            console_policy=console_policy.replace('"'+name+'"','"'+str(Path(output)/name)+'"')
    else:
        (directory/'consoleforeground.act').write_text('MODULE CONSOLEFOREGROUND\nUSE DOSBREAKTYPES\nPUBLIC BYTE FUNC Begin(DOSBREAKTYPES.Scope POINTER scope)\nRETURN(0)\nPUBLIC PROC End(DOSBREAKTYPES.Scope POINTER scope)\nRETURN\nPUBLIC PROC Notify(DOSBREAKTYPES.Scope POINTER scope)\nRETURN\nPUBLIC BYTE FUNC Handoff(DOSBREAKTYPES.Scope POINTER previous,target BYTE carry)\nRETURN(0)\nENDMODULE\n')
        console_policy='''PROC ConsoleInit()
RETURN
BYTE FUNC ConsoleService(BYTE service)
RETURN(0)
BYTE FUNC ConsoleProducerBound(TaskControl POINTER ctx)
RETURN(0)
CARD FUNC ConsoleProducerControl(TaskControl POINTER caller CARD saved BYTE service)
RETURN(T_FAULT)
'''
    if not console:
        console_policy+='BYTE FUNC ConsoleName(BYTE POINTER name)\nRETURN(0)\nBYTE FUNC ConsoleDevice(IORequest POINTER request)\nRETURN(0)\n'
    (directory/'task-console.inc').write_text(console_policy)
    signals=read_source(ROOT/'lib/exec/task-signals.inc')
    require(0 <= policy_probe <= 6, 'Invalid signal NMI checkpoint')
    (directory/'task-signals.inc').write_text(signals)
    wakes=read_source(ROOT/'lib/exec/task-wakes.inc')
    if irq_probe == 9:
        wakes='PUBLIC EXTERNAL PROC ClaimCheckpoint(TaskControl POINTER ctx)\n'+wakes
        claim='  LET item=ctx.item\n'
        require(wakes.count(claim)==1, 'Missing claimed-wake checkpoint site')
        wakes=wakes.replace(claim, '  ClaimCheckpoint(ctx)\n'+claim, 1)
    (directory/'task-wakes.inc').write_text(wakes)
    (directory/'execsignalirq.act').write_text('MODULE EXECSIGNALIRQ\nUSE EXEC\nPUBLIC EXTERNAL PROC PumpStart()\nPUBLIC EXTERNAL PROC IRQContext()\nENDMODULE\n')
    if manual_wake:
        drain='  IF DrainWakes()=0 THEN\n    RETURN(T_FAULT)\n  FI\n'
        require(policy.count(drain)==1, 'Missing automatic selection wake drain')
        policy=policy.replace(drain,'',1)
        first=policy.index('CARD FUNC FinishDispatch(')
        last=policy.index('PUBLIC CARD FUNC Dispatch',first)
        policy=policy[:first]+'CARD FUNC FinishDispatch(TaskControl POINTER ctx CARD saved CARD selected)\nRETURN(selected)\n\n'+policy[last:]
    (directory/'taskpolicy.act').write_text(policy)
    return directory


def application_entry(routine):
    # These shared resident shell helpers run on the shell's Task. They are
    # included into several application/fixture modules, not Task entries.
    if re.fullmatch(r'M_.+_SHELL(?:DIAGNOSTIC|PROMPT|CLEAR|RELEASELOCK|DIR|CLOSECOMMANDINPUT|TYPE|MEM|UNREDIRECT|EXTERNAL|DISPATCH|COMMAND|READSTEP|INITIALPROMPT)_[0-9A-F]+', routine['name']):
        return False
    if routine['name'].startswith('M_PROCESS_') and not re.fullmatch(r'M_PROCESS_(?:RUN|FINISH|EXECUTEIMAGE)_[0-9A-F]+',routine['name']):
        return False
    if routine['name'].startswith(('M_PROGRAM_', 'M_PROGRAMAPI_', 'M_PROGRAMIMAGE_', 'M_PROGRAMPLACE_', 'M_PROGRAMPROVIDERS_', 'M_PROGRAMLIBRARIES_', 'M_CSTRING_IMPL_')):
        return False
    if routine['name'].startswith(('M_DOSPROCESS_','M_DOSINHERIT_','M_FSFILES_','M_FSOBJECTS_','M_DOSCANCEL_','M_FSOPERATION_','M_FSABORT_','M_FSACTIVE_','M_DOSBREAK_','M_CONSOLE_', 'M_CONSOLEWINDOWS_','M_CONSOLETILING_','M_CONSOLEFOREGROUND_','M_CONSOLEDISPLAY_','M_CONSOLEDRIVER_','M_CONSOLEINPUT_','M_CONSOLECORE_','M_DOS_','M_DOSCALLS_','M_DOSRAW_','M_DOSSTREAMS_','M_DOSOBJECTS_','M_FSDIRECTORY_','M_FSMUX_','M_FSMOUNT_','M_FSMANAGER_','M_FSPACKET_','M_FSINFO_','M_FSIO_','M_FSINIT_','M_FSBOOT_','M_FSWORKER_','M_FSREGISTRY_','M_FSTYPES_','M_FSHANDLER_','M_FSPORTS_','M_FSNAMES_','M_DOSCLIENT_','M_DOSCORE_','M_DOSWIRE_','M_BLOCKIO_','M_BLOCKWIRE_','M_BLOCKTYPES_','M_MYDOSFILE_','M_MYDOS_','M_FS83_','M_FSCORE_','M_MYDOSTYPES_')):return False
    if re.match(r'M_(?:EXEC|EXECLISTS|EXECMEMORY|HEAPCORE|HEAPPOLICY|PORTCORE|IOCORE|IORESIDENT|IOTESTDRIVER|PRODUCERPROBE|EXECTASKS|TASKPOLICY)_', routine['name']):
        return False
    return True


def task_entries(image):
    entries = []
    registered={name.replace('.', '_').upper() for name in ABI['registered_entries']}
    resident_modules={name.split('.')[0].upper() for name in ABI['registered_entries']}
    found=set()
    for routine in image['routines']:
        identity=routine['name'][2:].rsplit('_',1)[0]
        module=next((m for m in sorted(resident_modules,key=len,reverse=True) if identity.startswith(m+'_')),None)
        if module is not None:
            if identity not in registered:continue
            require(not routine['arguments'] and routine['result_bytes']==0, 'Registered Task entry must be a zero-argument procedure')
            found.add(identity)
        if module is None and not application_entry(routine):continue
        if routine['arguments'] or routine['result_bytes'] != 0:
            continue
        require(routine['outgoing_bytes'] == 1, 'Task entry call layout changed')
        address = routine['address']
        require(type(address) is int and any(s['executable'] and
                s['address'] <= address < s['address']+len(s['bytes']) for s in image['segments']),
                'Task entry is outside executable image memory')
        require(address not in entries, 'Duplicate task entry address')
        entries.append(address)
    present={m for m in resident_modules if any(r['name'].startswith('M_'+m+'_') for r in image['routines'])}
    expected={name.replace('.', '_').upper() for name in ABI['registered_entries'] if name.split('.')[0].upper() in present}
    require(found == expected, 'Missing registered resident Task entry')
    require(image['entry'] in entries, 'Root is not an application task entry')
    entries.remove(image['entry'])
    entries.insert(0, image['entry'])
    require(len(entries) <= ABI['constants']['ENTRY_CAPACITY'], 'Too many task entries (maximum 16)')
    return entries



def writable_bindings(image, memory=None):
    """Publish only writable payload extents, subtracting kernel globals."""
    reserved = [(d['address'],d['address']+d['size']) for d in image['data']
                if re.match(r'M_(?:PROCESSSTATE|EXEC|TASKPOLICY|EXECMEMORY|HEAPCORE|HEAPPOLICY|PORTCORE|IOCORE|EXECLISTS|EXECTASKS)_',d['name'])]
    ranges = [(s['address'],s['address']+len(s['bytes'])) for s in image['segments'] if s['writable']]
    ranges += [(s['address'],s['address']+s['size']) for s in image['zero_fill'] if s['writable']]
    for start,end in reserved:
        pieces = []
        for low,high in ranges:
            if end <= low or start >= high:
                pieces.append((low,high))
            else:
                if low < start: pieces.append((low,start))
                if end < high: pieces.append((end,high))
        ranges = pieces
    # Only the embedded public Task records are admitted writable bindings.
    from generate_process import ABI as PROCESS_ABI
    for data in image['data']:
        if re.fullmatch(r'M_PROCESSSTATE_TABLE',data['name']):
            stride = PROCESS_ABI['record_bytes']
            require((data['size']-4) % stride == 0, 'Invalid Process table extent')
            ranges += [(base,base+ABI['task']['size'])
                       for base in range(data['address'],data['address']+data['size']-4,stride)]
    if memory is not None:
        for resident in generate_io.ABI['resident_dispatch']['residents'].values():
            arena=resident.get('storage','io_storage')
            if arena not in memory:continue
            if 'task_offset' in resident:
                base=memory[arena]['BASE']+resident['task_offset']
                ranges.append((base,base+ABI['task']['size']))
            if 'lease_offset' in resident:
                base=memory[arena]['BASE']+resident['lease_offset']
                ranges.append((base,base+ABI['lease']['size']))
    if memory is not None and 'console_storage' in memory:
        from generate_console import ABI as CONSOLE_ABI
        cs=memory['console_storage'];records=CONSOLE_ABI['records']
        def field(record,name):return next(o for n,k,o in records[record]['fields'] if n==name)
        ranges.append((cs['INSTANCE']+field('Instance','lease'),cs['INSTANCE']+field('Instance','lease')+12))
        ranges.append((cs['WINDOWS']+field('Windows','presenter'),cs['WINDOWS']+field('Windows','presenter')+12))
        for slot in range(CONSOLE_ABI['constants']['WINDOW_SLOTS']):
            base=cs['WINDOWS']+field('Windows','items')+slot*records['Window']['size']+field('Window','lease')
            ranges.append((base,base+12))
    merged = []
    for low,high in sorted(ranges):
        if merged and low == merged[-1][1]:
            merged[-1] = (merged[-1][0],high)
        else:
            merged.append((low,high))
    require(len(merged) <= 64, 'Too many writable task ranges')
    end = max([s['address']+len(s['bytes']) for s in image['segments']]+
              [s['address']+s['size'] for s in image['zero_fill']])
    address = (end+1)//2*2
    raw = b''.join(low.to_bytes(3,'little')+b'\0'+(high-low).to_bytes(3,'little')+b'\0'
                   for low,high in merged) or bytes(8)
    image['segments'].append({'address':address,'bytes':list(raw),'writable':False,'executable':False})
    return len(merged),address




if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--output', type=Path)
    args = parser.parse_args()
    path = ROOT/'lib/exec/exec-task-types.inc'
    if args.check:
        require(path.read_text().replace('\r\n','\n') == public_api(), 'Stale Task definitions')
    else:
        path.write_text(public_api())
    if args.output:
        from generate_memory import layout
        generate(args.output,layout())
