"""Build immutable renderer tables in the dedicated Calypsi read-only bank."""
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT/'c/include/hardware/vbxe.h'


def tables():
    source = CONTRACT.read_text()
    def constant(name):
        return int(re.search(r'^#define '+name+r' (\d+)(?:UL)?$', source, re.M)[1])
    count, work, rows = (constant(n) for n in
                        ('VBXE_LIST_RECORDS', 'VBXE_LIST_WORK', 'VBXE_CHUNK_ROWS'))
    if (count, work, rows) != (64, 8192, 16):
        raise ValueError('Revisit the bounded VBXE table layout for these limits')
    result = {'GemRecordOffsets': (2, [n*21 for n in range(count+1)])}
    for factor in (2, 3):
        result[f'GemRowLimit{factor}'] = (1, [min(rows, work//(width*factor))
                                            for width in range(1, 513)])
        result[f'GemWork{factor}'] = (2, [width*height*factor
                                        for height in range(1, rows+1)
                                        for width in range(1, 513)])
    for stride in (320, 640, 1024, 1280):
        result[f'GemStep{stride}'] = (2, [n*stride for n in range(rows+1)])
    result['GemScreenRows'] = (4, [y*320 for y in range(256)])
    return result


def generate(output):
    items = tables()
    lines = ['/* Generated by tools/generate_vbxe_tables.py. Do not edit. */',
             '#ifndef GEM_VBXE_TABLES_H', '#define GEM_VBXE_TABLES_H']
    for name, (size, values) in items.items():
        typename = {1:'UBYTE', 2:'UWORD', 4:'ULONG'}[size]
        lines.append(f'__attribute__((section("gemtables"))) static const {typename} {name}[{len(values)}]={{')
        for offset in range(0, len(values), 16):
            lines.append('    '+','.join(str(n)+('UL' if size==4 else '')
                         for n in values[offset:offset+16])+',')
        lines.append('};')
    lines.append('#endif')
    output.write_text('\n'.join(lines)+'\n')
    digest = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()
    return dict(generator_sha256=digest(Path(__file__)), contract_sha256=digest(CONTRACT),
                header_sha256=digest(output),
                tables={name:dict(element_bytes=size, entries=len(values), bytes=size*len(values))
                        for name, (size, values) in items.items()},
                payload_bytes=sum(size*len(values) for size, values in items.values()))
