#!/usr/bin/env python3
"""Prepack the fixed arrow for even/odd packed-pixel destinations."""
import argparse
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
BLACK=[0x8000,0xc000,0xa000,0x9000,0x8800,0x8400,0x8200,0x8100,0x8080,0x87c0,0x9400,0xa400,0xca00,0x8a00,0x0600,0]
WHITE=[0,0,0x4000,0x6000,0x7000,0x7800,0x7c00,0x7e00,0x7f00,0x7800,0x6800,0x4800,0x0400,0x0400,0,0]
def output():
    text='/* Generated by tools/generate_gem_cursor.py; fixed 16x16 arrow. */\nstatic const UBYTE cursorMasks[2][512]={\n'
    for parity in range(2):
        data=bytearray([255]*256+[0]*256)
        for row in range(16):
            for col in range(16):
                bit=0x8000>>col;offset=row*16+(parity+col)//2;shift=0 if (parity+col)&1 else 4
                if (BLACK[row]|WHITE[row])&bit:data[offset]&=255^(15<<shift)
                if BLACK[row]&bit:data[256+offset]|=15<<shift
        text+='  {\n'+''.join('    '+','.join(f'0x{v:02x}' for v in data[i:i+16])+',\n' for i in range(0,512,16))+'  },\n'
    return text+'};\n'
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');a=p.parse_args()
    path=ROOT/'ports/gem4xe/adapter/gem-cursor-masks.h';text=output()
    if a.check:assert path.read_text()==text,'Stale cursor masks'
    else:path.write_text(text)
