#!/usr/bin/env python3
"""Generate the ordinary-call Layers records; no kernel or wire protocol."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ABI = json.loads((ROOT / 'abi/layers.json').read_text())


def layout():
    sizes = {'BYTE': 1, 'CARD': 2, 'INT': 2, 'LONGCARD': 4}
    records = {}
    for name, fields in ABI['records'].items():
        offset = 0
        offsets = {}
        for field in fields:
            count = field.get('count', 1)
            if isinstance(count, str):
                count = ABI['constants'][count]
            offsets[field['name']] = offset
            offset += sizes[field['type']] * count
        sizes[name] = offset
        records[name] = dict(size=offset, fields=offsets)
    return records


def files():
    lines = ['; Generated by tools/generate_layers.py; do not edit.',
             'MODULE LAYERTYPES', f'PUBLIC CONST VERSION={ABI["version"]}']
    lines += [f'PUBLIC CONST {name}={value}'
              for name, value in ABI['constants'].items()]
    for name, fields in ABI['records'].items():
        lines.append(f'PUBLIC TYPE {name}=[')
        for field in fields:
            count = field.get('count')
            suffix = f'({count})' if count is not None else ''
            array = ' ARRAY' if count is not None else ''
            lines.append(f'  {field["type"]}{array} {field["name"]}{suffix}')
        lines.append(']')
    for name, record in layout().items():
        lines.append(f'PUBLIC CONST {name.upper()}_SIZE={record["size"]}')
        lines += [f'PUBLIC CONST {name.upper()}_{field.upper()}={offset}'
                  for field, offset in record['fields'].items()]
    lines += ['ENDMODULE', '']
    return {ROOT / 'lib/display/layertypes.act': '\n'.join(lines)}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in files().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit('Stale Layers layout: ' + str(path))
        else:
            path.write_text(content)
