#!/usr/bin/env python3
"""Generate bounded native interrupt storage and entry declarations."""
import argparse
import json
from pathlib import Path

from generate_memory import ROOT, require
from generate_heap import write

ABI = json.loads((ROOT/'abi/native-interrupts.json').read_text())
HEADER = '; Generated by tools/generate_native_interrupts.py; do not edit.\n'


def constants(abi=ABI):
    a = abi
    require(a['schema_version'] == 1, 'Unsupported native interrupt ABI')
    require(a['source_capacity'] == 1 and a['sources'] == {'TIMER': 0}
            and a['test_source_capacity'] == 1 and a['test_sources'] == {'PROBE': 1},
            'Unsupported native source table')
    require(a['service_budget'] in range(1, 5), 'Unbounded native service budget')
    require(a['fields'] == dict(ACTIVE=0, PORT_BUSY=1, ENABLED=2, PENDING=4,
                                RUNNING=6, BLOCKED=8, BUDGET=10, RESUME=16) and a['resume_stride'] == 4,
            'Invalid native interrupt state fields')
    blitter = json.loads((ROOT/'abi/blitter.json').read_text())
    require(a['state_offset'] >= blitter['code_offset']+blitter['code_reserved_bytes']
            and a['state_offset']+a['state_bytes'] <= a['code_offset']
            and a['code_offset']+a['code_reserved_bytes'] <= 65536,
            'Native interrupt storage overlaps another reservation')
    require(a['fields']['RESUME']+9*a['resume_stride'] <= a['state_bytes'],
            'Native return slots exceed state reservation')
    return dict(STATE_OFFSET=a['state_offset'], STATE_BYTES=a['state_bytes'],
                CODE_OFFSET=a['code_offset'], CODE_BYTES=a['code_reserved_bytes'],
                SOURCE_CAPACITY=a['source_capacity'], SERVICE_BUDGET=a['service_budget'],
                TEST_SOURCE_CAPACITY=a['test_source_capacity'],
                RESUME_STRIDE=a['resume_stride'],
                **{f'SOURCE_{k}': v for k, v in (a['sources'] | a['test_sources']).items()})


def assembly():
    c = constants()
    return (HEADER + ''.join(f'NI_{k} = ${v:x}\n' for k, v in c.items())
            + 'NI_STATE = T_BASE+NI_STATE_OFFSET\n'
            + 'NI_SOURCE_COUNT = NI_SOURCE_CAPACITY+HEAP_PROBE*NI_TEST_SOURCE_CAPACITY\n'
            + ''.join(f'NI_{k} = NI_STATE+{v}\n' for k, v in ABI['fields'].items()))


def generate(output, base, memory):
    require((ROOT/'platform/altirraos/native-interrupts.inc').read_text() == assembly(),
            'Stale native interrupt definitions')
    a = ABI
    memory['native_interrupt_storage'] = dict(
        BASE=base+a['state_offset'], BYTES=a['state_bytes'],
        CODE_BASE=base+a['code_offset'], CODE_BYTES=a['code_reserved_bytes'],
        RESERVATION_BASE=base+a['state_offset'],
        RESERVATION_BYTES=a['code_offset']+a['code_reserved_bytes']-a['state_offset'])


if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--check', action='store_true')
    args = p.parse_args()
    write(ROOT/'platform/altirraos/native-interrupts.inc', assembly(), args.check)
