#!/usr/bin/env python3
"""Generate Task-side GEM keyboard data from the pinned reference mapping."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT/'ports/gem4xe/aes-keyboard-inputs.json'
OUTPUT = ROOT/'lib/aes/aes-keyboard.inc'


def render():
    data = json.loads(INPUT.read_text())
    scans = data['scan_codes']
    assert len(scans) == 64 and all(0 <= v < 128 for v in scans)
    lines = ['; Generated by tools/generate_aes_keyboard.py. GPL-3.0-only.',
             '; GEM4XE kb_st/kb_translate: see ports/gem4xe/aes-keyboard-inputs.json.',
             *[f'CONST {name}={data["policy"][field]}' for name,field in (
                 ('KEYDEF_ADDRESS','keydef_address'), ('CAPS_TOGGLE','caps_toggle'),
                 ('CAPS_ON','caps_on'), ('TAB_INDEX','tab_index'),
                 ('TAB_KEY','tab_all_modifiers'))],
             'BYTE ARRAY scans=[']
    lines += ['  '+' '.join(f'${v:02x}' for v in scans[i:i+16]) for i in range(0,64,16)]
    lines += [']', '', 'CARD FUNC Special(BYTE value)', '', '  CASE value OF']
    for value, result in data['atascii_to_gem'].items():
        lines += [f'  WHEN ${int(value):02x} THEN', f'    RETURN(${result:04x})']
    lines += ['  ESAC', '', 'RETURN(0)', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = render()
    if args.check:
        assert OUTPUT.read_text() == text, 'Regenerate AES keyboard mapping'
    else:
        OUTPUT.write_text(text)
