#!/usr/bin/env python3
"""Generate the single current native message/port contract."""
import argparse
import json
from pathlib import Path

from generate_memory import ROOT, integer, require
from generate_heap import RESULTS, write

ABI = json.loads((ROOT/'abi/ports.json').read_text())
HEADER = '; Generated by tools/generate_ports.py; do not edit.\n'
WIDTHS = {'EXECLISTS.Node':(11,1),'EXECLISTS.List':(11,1),
          'BYTE':(1,1),'CARD':(2,2),'Task POINTER':(3,1),'MsgPort POINTER':(3,1)}
DECLARATIONS = {
    'PutMsg':'PROC PutMsg(MsgPort POINTER port Message POINTER message)',
    'GetMsg':'Message POINTER FUNC GetMsg(MsgPort POINTER port)',
    'ReplyMsg':'PROC ReplyMsg(Message POINTER message)',
    'WaitPort':'Message POINTER FUNC WaitPort(MsgPort POINTER port)',
    'CreateMsgPort':'MsgPort POINTER FUNC CreateMsgPort()',
    'DeleteMsgPort':'PROC DeleteMsgPort(MsgPort POINTER port)',
    'AddPort':'PROC AddPort(MsgPort POINTER port)',
    'RemPort':'PROC RemPort(MsgPort POINTER port)',
    'FindPort':'MsgPort POINTER FUNC FindPort(BYTE POINTER name)',
}
CLASSIC = dict(NT_UNKNOWN=0,NT_MSGPORT=4,NT_MESSAGE=5,NT_FREEMSG=6,
               NT_REPLYMSG=7,PF_ACTION=3,PA_SIGNAL=0,PA_SOFTINT=1,PA_IGNORE=2)
IMPLEMENTED = {'PutMsg':'put_msg','GetMsg':'get_msg','ReplyMsg':'reply_msg','WaitPort':'wait_port',
               'CreateMsgPort':'create_msg_port','DeleteMsgPort':'delete_msg_port',
               'AddPort':'add_port','RemPort':'rem_port','FindPort':'find_port'}


def reserve_metadata(memory):
    start=(memory['profile']['code_origin']+15)//16*16
    require(start>>16==memory['constants']['KERNEL_BANK'] and
            start+16<=(memory['constants']['KERNEL_BANK']+1)*65536,
            'Port registry exceeds kernel bank')
    memory['upper_reservations'].append(dict(name='port-registry',address=start,size=16))
    memory['profile']['code_origin']=start+16
    memory['ports_storage']=dict(BASE=start,BYTES=16,ACTIVE_BYTES=11)


def registration_include(output,memory):
    values=memory['ports_storage']
    write(Path(output)/'ports-storage.inc',HEADER+''.join(f'PS_{name} = ${value:x}\n' for name,value in values.items()),False)
    write(Path(output)/'ports-storage-action.inc',HEADER+''.join(f'CONST PS_{name}=${value:x}\n' for name,value in values.items()),False)


def constants(abi=ABI):
    require(abi['abi']=='exec816.ports' and abi['revision']==1,'Unsupported port ABI')
    require(abi['constants']==CLASSIC,'Invalid classic port constants')
    require(set(abi['services'])=={'PUT_MSG','GET_MSG','REPLY_MSG','WAIT_HEAD','DELETE_CHECK','ADD_PORT','REM_PORT','FIND_PORT'},
            'Invalid port service family')
    require(set(abi['imports'])==set(DECLARATIONS),'Invalid port imports')
    require(set(abi['records'])=={'MsgPort','Message'},'Invalid port records')
    require(abi.get('native_bindings') == {'ReplyMsg': {
        'symbol': 'exec_reply_msg_native',
        'address': 'A16 low word, X16 zero-extended bank',
        'entry': dict(E=0, M=0, X=0, I=1),
        'preserved': ['A', 'X', 'Y', 'P', 'D', 'DBR', 'S'],
        'context': 'admitted native IRQ or deferred native continuation'}},
        'Invalid native ReplyMsg binding')
    c=dict(abi['constants'])
    for group,prefix,low in [('services','SERVICE',0),('errors','ERROR',0xff00)]:
        values=list(abi[group].values())
        require(len(set(values))==len(values),'Duplicate port '+group)
        existing=set()
        for path in ('exec816-v1.json','tasks.json','heap-v1.json'):
            existing.update(json.loads((ROOT/'abi'/path).read_text())[group].values())
        for name,value in abi[group].items():
            integer(value,low,255 if group=='services' else 65535,name)
            require(value not in existing,'Port '+group+' collision')
            c[prefix+'_'+name]=value
    for name,record in abi['records'].items():
        cursor=0;alignment=1;seen=set()
        for field,kind,offset in record['fields']:
            require(kind in WIDTHS and field not in seen,'Invalid port field')
            seen.add(field);width,align=WIDTHS[kind];alignment=max(alignment,align)
            cursor=(cursor+align-1)//align*align
            require(offset==cursor,'Invalid '+name+' offset')
            c[name.upper()+'_'+field.upper()]=offset;cursor+=width
        require(record['alignment']==alignment and record['size']==(cursor+alignment-1)//alignment*alignment,
                'Invalid '+name+' size/alignment')
        c[name.upper()+'_BYTES']=record['size']
    for name,shape in abi['imports'].items():
        count=2 if name=='PutMsg' else 0 if name=='CreateMsgPort' else 1
        expected=dict(arguments=[dict(alignment=1,offset=i*3,size=3) for i in range(count)],
                      outgoing_bytes=(count*3)|1,
                      result_bytes=3 if name in ('GetMsg','WaitPort','CreateMsgPort','FindPort') else 0)
        require(shape==expected,'Invalid port import '+name)
    return c


def types(public=False):
    return ''.join(('PUBLIC ' if public else '')+'TYPE '+name+'=[\n'+''.join(
        f'  {kind} {field}\n' for field,kind,_ in record['fields'])+']\n'
        for name,record in ABI['records'].items())


def public_api():
    c=constants()
    return HEADER+types(True)+''.join(f'PUBLIC CONST {name}=${value:x}\n' for name,value in CLASSIC.items())+\
        ''.join(f'PUBLIC CONST {name}_SIZE={c[name+"_BYTES"]}\n' for name in ('MSGPORT','MESSAGE'))


def declarations():
    return ''.join('PUBLIC EXTERNAL '+line+'\n' for line in DECLARATIONS.values())


def native_declarations():
    constants()
    return HEADER+'''; Native IRQ/resident assembly binding; not the Task compiler ABI.
; JSL with E=0, M=X=0, I=1 and an adapter-admitted complete native frame.
; A16 = message low word; X16 = zero-extended bank.
; Preserves A/X/Y/P/D/DBR/S. Publishes queue and signal before returning.
; No scheduling, allocation, COP, waiting or raw-NMI/ROM entry is permitted.
; The producer owns the request and retains its endpoint until publication.
.import exec_reply_msg_native
'''


def call_types():
    return HEADER+types()+'''TYPE PortSendArgs=[MsgPort POINTER port Message POINTER message]
TYPE PortPointerArgs=[BYTE POINTER value]
'''


def check_routine(routine,name):
    expected=ABI['imports'][name]
    args=[{k:a[k] for k in ('alignment','offset','size')} for a in routine['arguments']]
    require(args==expected['arguments'] and routine['outgoing_bytes']==expected['outgoing_bytes'],
            'Port native call layout changed: '+name)
    if 'result_bytes' in routine:require(routine['result_bytes']==expected['result_bytes'],'Port result width changed')
    if 'result' in routine:require(routine['result']==RESULTS[expected['result_bytes']],'Port result ABI changed')


def generate(output,check=False):
    c=constants();output=Path(output)
    write(output/'ports.inc',HEADER+''.join(f'P_{name} = ${value:x}\n' for name,value in c.items()),check)
    write(output/'ports-action.inc',HEADER+''.join(f'CONST P_{name}=${value:x}\n' for name,value in c.items())+types(),check)
    write(output/'port-packets.inc',HEADER+'''TYPE PortSendArgs=[MsgPort POINTER port Message POINTER message]
TYPE PortPointerArgs=[BYTE POINTER value]
''',check)
    return c


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',type=Path);parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    write(ROOT/'lib/exec/exec-port-types.inc',public_api(),args.check)
    write(ROOT/'lib/exec/port-call-types.inc',call_types(),args.check)
    write(ROOT/'lib/exec/exec-native-ports.inc',native_declarations(),args.check)
    if args.output:generate(args.output,args.check)
