#!/usr/bin/env python3
"""Generate the current native device contract and validate implemented bindings."""
import adapter_state as adapter
import argparse
import json
from pathlib import Path

from generate_memory import ROOT, integer, require
from generate_heap import write

ABI = json.loads((ROOT/'abi/io.json').read_text())
SIO = json.loads((ROOT/'abi/sio.json').read_text())
HEADER = '; Generated by tools/generate_io.py; do not edit.\n'
RESULTS = {0:'None',2:'Some(NativeResult(A16))',3:'Some(NativeResult(A16X8ZeroExtended))'}
DECLARATIONS = {
    'CreateIORequest':'IORequest POINTER FUNC CreateIORequest(MsgPort POINTER replyPort LONGCARD size)',
    'DeleteIORequest':'PROC DeleteIORequest(IORequest POINTER request)',
    'OpenDevice':'INT FUNC OpenDevice(BYTE POINTER name LONGCARD unit IORequest POINTER request LONGCARD flags)',
    'CloseDevice':'PROC CloseDevice(IORequest POINTER request)',
    'BeginIO':'PROC BeginIO(IORequest POINTER request)',
    'SendIO':'PROC SendIO(IORequest POINTER request)',
    'DoIO':'INT FUNC DoIO(IORequest POINTER request)',
    'CheckIO':'IORequest POINTER FUNC CheckIO(IORequest POINTER request)',
    'WaitIO':'INT FUNC WaitIO(IORequest POINTER request)',
    'AbortIO':'PROC AbortIO(IORequest POINTER request)',
}
CLASSIC = dict(IOF_QUICK=1, **{'CMD_'+name:i for i,name in enumerate(
    ('INVALID','RESET','READ','WRITE','UPDATE','CLEAR','STOP','START','FLUSH','NONSTD'))})
ERRORS = {'IOERR_'+name:-i for i,name in enumerate(
    ('OPENFAIL','ABORTED','NOCMD','BADLENGTH','BADADDRESS','UNITBUSY','SELFTEST'),1)}
SIO_CONSTANTS = dict(SIOCMD_TRANSACTION=9,SIODIR_NONE=0,SIODIR_READ=1,SIODIR_WRITE=2,
    **{'SIOERR_'+name:i for i,name in enumerate(
        ('TIMEOUT','NAK','DEVICE','CHECKSUM','OVERRUN','FRAMING','PROTOCOL','BUSUNAVAILABLE','BADPROFILE'),1)})
WIDTHS = {'Message':(16,2),'BYTE POINTER':(3,1),'BYTE':(1,1),'CARD':(2,2),'LONGCARD':(4,2)}
FIELDS = [('io_Message','Message'),('io_Device','BYTE POINTER'),('io_Unit','BYTE POINTER'),
          ('io_Command','CARD'),('io_Flags','BYTE'),('io_Error','BYTE')]
STANDARD = FIELDS+[('io_Actual','LONGCARD'),('io_Length','LONGCARD'),
                   ('io_Data','BYTE POINTER'),('io_Offset','LONGCARD')]
SERIAL = STANDARD+[('sio_Command','BYTE'),('sio_Aux1','BYTE'),('sio_Aux2','BYTE'),
                   ('sio_Direction','BYTE'),('sio_Profile','CARD'),('sio_TimeoutUS','LONGCARD')]


def constants(abi=ABI,sio=SIO):
    require(abi['abi']=='exec816.io' and abi['revision']==1,'Unsupported I/O ABI')
    require(sio['abi']=='exec816.sio' and sio['revision']==1,'Unsupported SIO ABI')
    require(abi['constants']==CLASSIC and abi['io_errors']==ERRORS,'Invalid classic I/O constants')
    require(sio['constants']==SIO_CONSTANTS,'Invalid SIO constants')
    require(sio['profiles']=={'FASTEST125':1,'STOCK810':2,'HAPPY1050':3,'GENERIC57600':4},'Unsupported SIO profiles')
    message=json.loads((ROOT/'abi/ports.json').read_text())['records']['Message']
    require((message['size'],message['alignment'])==WIDTHS['Message'],'Message prefix ABI changed')
    require(set(abi['services'])=={'OPEN_DEVICE','CLOSE_DEVICE','BEGIN_IO','CHECK_IO','WAIT_REQUEST','ABORT_IO','SEND_IO','CREATE_CHECK','DELETE_CHECK','DO_IO','TEST_STEP'},
            'Invalid guarded I/O operations')
    require(set(abi['errors'])=={'MISUSE'},'Invalid I/O faults')
    console=json.loads((ROOT/'abi/console.json').read_text())['constants']
    require(console['CONERR_INPUTOVERFLOW']==1,'Invalid console input error')
    c={'CONERR_INPUTOVERFLOW':console['CONERR_INPUTOVERFLOW'],**CLASSIC,**ERRORS,**SIO_CONSTANTS,**{'SIO_PROFILE_'+k:v for k,v in sio['profiles'].items()}}
    dispatch=abi['resident_dispatch']
    require(dispatch['tag']==0x20000,'Resident tag overlaps completion/pending result')
    require(dispatch['residents']=={
        'SIO':dict(id=1,module='SIODRIVER',device_offset=64,name_offset=224,test_only=False,task_offset=160,lease_offset=108),
        'IMMEDIATE':dict(id=2,module='IOTESTDRIVER',device_offset=0,name_offset=32,test_only=True),
        'CONSOLE':dict(id=3,module='CONSOLEDRIVER',storage='console_storage',device_offset=0,name_offset=107,test_only=False,task_offset=36,lease_offset=136),
        'TIMER':dict(id=4,module='TIMERDRIVER',storage='timer_device_storage',device_offset=16,name_offset=480,test_only=False)},
        'Unsupported resident dispatch description')
    c['ROUTE_TAG']=dispatch['tag']
    for name,resident in dispatch['residents'].items():
        c['ROUTE_'+name]=dispatch['tag']|resident['id']
    for group,prefix,low,high in [('services','SERVICE',0,255),('errors','ERROR',0xff00,0xffff)]:
        values=list(abi[group].values())
        require(len(values)==len(set(values)),'Duplicate I/O '+group)
        existing=set()
        for name in ('exec816-v1.json','tasks.json','heap-v1.json','ports.json'):
            existing.update(json.loads((ROOT/'abi'/name).read_text())[group].values())
        for name,value in abi[group].items():
            integer(value,low,high,name)
            require(value not in existing,'I/O '+group+' collision')
            c[prefix+'_'+name]=value
    require(set(abi['records'])=={'IORequest','IOStdReq'} and set(sio['records'])=={'IOSIOReq'},
            'Invalid I/O records')
    for name,record in {**abi['records'],**sio['records']}.items():
        expected={'IORequest':FIELDS,'IOStdReq':STANDARD,'IOSIOReq':SERIAL}[name]
        require([(f,k) for f,k,_ in record['fields']]==expected,'Invalid '+name+' fields/prefix')
        cursor=0
        for field,kind,offset in record['fields']:
            size,alignment=WIDTHS[kind]
            cursor=(cursor+alignment-1)//alignment*alignment
            require(type(offset) is int and offset==cursor,'Invalid '+name+' field offset')
            c[name.upper()+'_'+field.upper()]=offset;cursor+=size
        require(record['alignment']==2 and record['size']==(cursor+1)//2*2,'Invalid '+name+' size/alignment')
        c[name.upper()+'_BYTES']=record['size']
    require(set(abi['imports'])==set(DECLARATIONS),'Invalid I/O imports')
    for name,shape in abi['imports'].items():
        args=[dict(alignment=1,offset=0,size=3)];outgoing=3
        result=3 if name in ('CreateIORequest','CheckIO') else 2 if name in ('OpenDevice','DoIO','WaitIO') else 0
        if name=='CreateIORequest':
            args+=[dict(alignment=2,offset=4,size=4)];outgoing=9
        elif name=='OpenDevice':
            args+=[dict(alignment=2,offset=4,size=4),dict(alignment=1,offset=8,size=3),
                   dict(alignment=2,offset=12,size=4)];outgoing=17
        require(shape==dict(arguments=args,outgoing_bytes=outgoing,result_bytes=result),
                'Invalid native I/O call shape: '+name)
    return c


def types(public=False):
    return ''.join(('PUBLIC ' if public else '')+'TYPE '+name+'=[\n'+''.join(
        f'  {kind} {field}\n' for field,kind,_ in record['fields'])+']\n'
        for name,record in {**ABI['records'],**SIO['records']}.items())


def literal(value):
    return str(value) if value<0 else f'${value:x}'


def public_api():
    c=constants()
    return HEADER+types(True)+''.join(f'PUBLIC CONST {name}={literal(value)}\n'
        for name,value in {'CONERR_INPUTOVERFLOW':c['CONERR_INPUTOVERFLOW'],**CLASSIC,**ERRORS,**SIO_CONSTANTS,**{'SIO_PROFILE_'+k:v for k,v in SIO['profiles'].items()}}.items())+''.join(
        f'PUBLIC CONST {name.upper()}_SIZE={record["size"]}\n'
        for name,record in {**ABI['records'],**SIO['records']}.items())


def declarations():
    return ''.join('PUBLIC EXTERNAL '+line+'\n' for line in DECLARATIONS.values())


def c_header():
    constants()
    kinds={'Message':'struct Message','BYTE POINTER':'void EXEC_PTR *',
           'BYTE':'UBYTE','CARD':'UWORD','LONGCARD':'ULONG'}
    text='/* Generated by tools/generate_io.py; do not edit. */\n#ifndef EXEC_IO_H\n#define EXEC_IO_H\n#include <exec/ports.h>\n'
    for name,record in ABI['records'].items():
        text+='\nstruct '+name+' {\n'+''.join(
            f'    {"BYTE" if field=="io_Error" else kinds[kind]} {field};\n'
            for field,kind,_ in record['fields'])+'};\n'
    text+='\n'+''.join(f'#define {name} ({value})\n' for name,value in (CLASSIC | ERRORS).items())
    return text+'#endif\n'


def check_routine(routine,name):
    expected=ABI['imports'][name]
    args=[{k:a[k] for k in ('alignment','offset','size')} for a in routine['arguments']]
    require(args==expected['arguments'] and routine['outgoing_bytes']==expected['outgoing_bytes'],
            'I/O native call layout changed: '+name)
    if 'result_bytes' in routine:require(routine['result_bytes']==expected['result_bytes'],'I/O result width changed')
    if 'result' in routine:require(routine['result']==RESULTS[expected['result_bytes']],'I/O result ABI changed')


IMPLEMENTED = {name:label for name,label in (
    ('CreateIORequest','create_request'),('DeleteIORequest','delete_request'),
    ('OpenDevice','open_device'),('CloseDevice','close_device'),
    ('BeginIO','begin_io'),('SendIO','send_io'),('CheckIO','check_io'),
    ('WaitIO','wait_io'),('DoIO','do_io'),('AbortIO','abort_io'))}


def reserve_metadata(memory):
    start=(memory['profile']['code_origin']+15)//16*16
    require(start+256 <= (memory['constants']['KERNEL_BANK']+1)*65536,'Device metadata exceeds kernel bank')
    memory['upper_reservations'].append(dict(name='device-residents',address=start,size=256))
    memory['profile']['code_origin']=start+256
    memory['io_storage']=dict(BASE=start,BYTES=256)


def registration_include(output,memory,test_device=False):
    if 'io_storage' not in memory: reserve_metadata(memory)
    write(Path(output)/'io-storage-action.inc',HEADER+''.join(
        f'CONST IS_{name}=${value:x}\n' for name,value in memory['io_storage'].items())+
        f'CONST IS_TEST_DEVICE={int(test_device)}\n',False)
    switching=adapter.addresses(memory['profile'])['SWITCHING']
    meta='MODULE IORESIDENTMETA\n'+f'PUBLIC CONST TAG=${ABI["resident_dispatch"]["tag"]:x}, BASE=${memory["io_storage"]["BASE"]:x}, TEST_DEVICE={int(test_device)}, SWITCHING=${switching:x}\n'
    for name,resident in ABI['resident_dispatch']['residents'].items():
        meta+=f'PUBLIC CONST {name}={resident["id"]}\n'
    write(Path(output)/'ioresidentmeta.act',HEADER+meta+'ENDMODULE\n',False)
    entries={
        'Bound':('BYTE FUNC','EXEC.IORequest POINTER request','request'),
        'Open':('INT FUNC','BYTE POINTER name LONGCARD unit EXEC.IORequest POINTER request LONGCARD flags','name,unit,request,flags'),
        'Close':('PROC','EXEC.IORequest POINTER request','request'),
        'BeginIO':('PROC','EXEC.IORequest POINTER request','request'),
        'AbortIO':('PROC','EXEC.IORequest POINTER request','request')}
    residents=[r for r in ABI['resident_dispatch']['residents'].values()
               if (test_device or not r['test_only']) and r.get('storage','io_storage') in memory]
    text=HEADER+'MODULE IORESIDENT\nUSE EXEC\nUSE HEAPCORE\n'+''.join('USE '+r['module']+'\n' for r in residents)
    for name,(kind,args,values) in entries.items():
        text+=f'PUBLIC {kind} {name}(CARD route {args})\n'
        for resident in residents:
            call=f'{resident["module"]}.{name}({values})'
            text+=f'  IF route={resident["id"]} THEN '+(call+' RETURN' if kind=='PROC' else f'RETURN({call})')+' FI\n'
        text+='  HEAPCORE.Abort(4)\n'+('RETURN\n' if kind=='PROC' else 'RETURN(0)\n')
    write(Path(output)/'ioresident.act',text+'ENDMODULE\n',False)


def production_binding(interface):
    check_routine(interface,interface['name'].split('.')[1])
    name=interface['name'].split('.')[1]
    require(name in IMPLEMENTED,'Unimplemented device I/O import: '+interface['name'])
    return 'io_'+IMPLEMENTED[name]


def generate(output,check=False):
    c=constants();output=Path(output)
    write(output/'io.inc',HEADER+''.join(f'IO_{name} = {literal(value)}\n' for name,value in c.items()),check)
    write(output/'io-action.inc',HEADER+''.join(f'CONST IO_{name}={literal(value)}\n' for name,value in c.items())+types(),check)
    return c


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',type=Path);parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    write(ROOT/'lib/exec/exec-io-types.inc',public_api(),args.check)
    write(ROOT/'c/include/exec/io.h',c_header(),args.check)
    if args.output:generate(args.output,args.check)
