#!/usr/bin/env python3
"""Shared technical boot event labels and native/C event numbers."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ABI = json.loads((ROOT/'abi/boot-diagnostics.json').read_text())


def files():
    constants = {name: index for index, (name, _) in enumerate(ABI['events'])}
    assembly = '; Generated by tools/generate_boot_diagnostics.py; do not edit.\n'
    assembly += ''.join(f'DIAG_{name} = {value}\n' for name, value in constants.items())
    assembly += f'DIAG_FAILURE_FIRST = {ABI["failure_first"]}\n'
    assembly += f'DIAG_FAILURE_LAST = {ABI["failure_last"]}\n'
    assembly += ''.join(f'DIAG_PHASE_{name} = {value}\n'
                        for name, value in ABI['phases'].items())
    action = '; Generated by tools/generate_boot_diagnostics.py; do not edit.\n'
    action += ''.join(f'PUBLIC CONST {name}={value}\n' for name, value in constants.items())
    header = '/* Generated by tools/generate_boot_diagnostics.py; do not edit. */\n'
    header += '#ifndef EXEC_BOOT_DIAGNOSTICS_H\n#define EXEC_BOOT_DIAGNOSTICS_H\n'
    header += ''.join(f'#define BOOT_DIAG_{name} {value}\n' for name, value in constants.items())
    header += '#endif\n'
    labels = '; Generated boot labels; each has a fixed 16-byte stride.\nboot_labels:\n'
    for name, label in ABI['events']:
        if '=' in label:
            key, value = label.split('=', 1)
            label = key.ljust(ABI['label_columns'])+'='+value
        if len(label.encode('ascii')) >= ABI['label_bytes']:
            raise ValueError('Boot label is too long: '+name)
        labels += f'    .byte "{label}",0\n    .res {ABI["label_bytes"]-len(label)-1},0\n'
    return {ROOT/'platform/altirraos/boot-diagnostics.inc': assembly,
            ROOT/'platform/altirraos/boot-labels.inc': labels,
            ROOT/'lib/exec/boot-diagnostics-action.inc': action,
            ROOT/'c/include/hardware/boot-diagnostics.h': header}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in files().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit('Stale boot diagnostics: '+str(path))
        else:
            path.write_text(content)
