#!/usr/bin/env python3
"""Generate the resident Process contract and capacity-sized upper-RAM table."""
from library_paths import library_file
import argparse
import json
import re
from pathlib import Path
from generate_memory import ROOT, require
from generate_heap import write

ABI = json.loads((ROOT/'abi/process.json').read_text())
HEADER = '; Generated by tools/generate_process.py; do not edit.\n'


def state_source(capacity=4, base=0):
    require(type(capacity) is int and 2 <= capacity <= 16, 'Invalid Process capacity')
    require(ABI['abi'] == 'exec816.process' and ABI['version'] == 6, 'Unsupported Process ABI')
    text = HEADER+'MODULE PROCESSSTATE\n'
    text += f'PUBLIC CONST CAPACITY={capacity}\nPUBLIC CONST RECORD_BYTES={ABI["record_bytes"]}\n'
    for name, value in ABI['resident_entries'].items():
        text += f'PUBLIC CONST RESIDENT_{name.upper()}={value}\n'
    for group, prefix in [('states','STATE'), ('operations','OP')]:
        require(len(set(ABI[group].values())) == len(ABI[group]), 'Duplicate Process '+group)
        text += ''.join(f'PUBLIC CONST {prefix}_{name}={value}\n' for name,value in ABI[group].items())
    text += 'PUBLIC TYPE Entry=[\n'
    cursor = 0
    for name, kind, offset in ABI['record']:
        array = re.fullmatch(r'BYTE\[(\d+)\]', kind)
        size, align = (int(array[1]),1) if array else {
            'BYTE':(1,1), 'CARD':(2,2), 'LONGCARD':(4,2), 'LONGINT':(4,2),
            'BYTE POINTER':(3,1), 'PROC POINTER':(3,1), 'LONGINT FUNC POINTER':(3,1)}[kind]
        cursor = (cursor+align-1)//align*align
        require(cursor == offset, 'Invalid Process field: '+name)
        cursor += size
        if array:
            text += f'  BYTE ARRAY {name}({size})\n'
        else:
            text += f'  {kind} {name}'+('()' if kind in ('PROC POINTER','LONGINT FUNC POINTER') else '')+'\n'
    require(cursor == ABI['record_bytes'], 'Invalid Process stride')
    return (text+']\nPUBLIC TYPE Table=[Entry ARRAY entries(CAPACITY) LONGCARD nextIdentity]\n'
            +'PUBLIC Table POINTER FUNC Registry()\n'
            +f'RETURN(Table POINTER(ADDRESS(${base:x})))\nENDMODULE\n')


def reserve_metadata(memory, capacity):
    base = (memory['profile']['code_origin']+1)//2*2
    size = ABI['record_bytes']*capacity+4
    require(base >= 65536 and base+size <= (memory['constants']['KERNEL_BANK']+1)*65536,
            'Process table exceeds kernel bank')
    require(all(base+size <= r['address'] or base >= r['address']+r['size']
                for r in memory['upper_reservations']), 'Process table overlap')
    memory['upper_reservations'].append(dict(name='process-table',address=base,size=size))
    memory['profile']['code_origin'] = base+size
    memory['process_storage'] = dict(BASE=base,BYTES=size,CAPACITY=capacity,
                                     RECORD_BYTES=ABI['record_bytes'],TABLE_BYTES=size-4)


def public_types():
    return (HEADER+f'PUBLIC CONST PROCESS_ABI_VERSION={ABI["version"]}\n'
            +f'PUBLIC CONST ARGUMENT_LIMIT={ABI["argument_limit"]}\n'
            +''.join(f'PUBLIC CONST ERROR_{name}={value}\n' for name,value in ABI['errors'].items())
            +'PUBLIC TYPE Result=[\n  LONGINT primary\n  LONGINT secondary\n]\n')


def check_public():
    for name, expected in [('process-types.inc',public_types()), ('processstate.act',state_source())]:
        require((library_file(name)).read_text().replace('\r\n','\n') == expected, 'Stale Process definition: '+name)


def resident_entries(image):
    """Checked function callbacks, separate from AddTask's procedure registry."""
    from generate_tasks import application_entry, ABI as task_abi
    from generate_program import ABI as program_abi
    reserved={name.split('.')[0].upper() for name in task_abi['registered_entries']}
    entries=[]
    for routine in image['routines']:
        if any(routine['name'].startswith('M_'+name+'_') for name in reserved):continue
        if not application_entry(routine):continue
        if routine['arguments'] or routine['result_bytes'] != 4:continue
        if routine['signature'] != program_abi['entry_signature']:continue
        require(routine['outgoing_bytes']==1,'Process entry call layout changed')
        address=routine['address']
        require(type(address) is int and any(s['executable'] and s['address']<=address
                and address+routine['size']<=s['address']+len(s['bytes']) for s in image['segments']),
                'Process entry is outside executable image memory')
        require(address not in entries,'Duplicate Process entry address')
        entries.append(address)
    shape=ABI['resident_entries']
    require(shape['entries_offset']+3*shape['capacity']<=shape['descriptor_bytes'],
            'Process entry reservation exceeds DOS descriptor')
    require(len(entries)<=shape['capacity'],'Too many resident Process entries')
    return entries


def check_calls(image):
    for name, spec in ABI['calls'].items():
        matches = [r for r in image['routines'] if re.fullmatch('M_PROCESS_'+name.upper()+r'_[0-9A-F]+',r['name'])]
        for routine in matches:
            cursor, arguments = 0, []
            for size in spec['sizes']:
                align = 1 if size in (1,3) else 2
                cursor = (cursor+align-1)//align*align
                arguments.append(dict(size=size,alignment=align,offset=cursor))
                cursor += size
            require([{k:a[k] for k in ('size','alignment','offset')} for a in routine['arguments']] == arguments
                    and routine['outgoing_bytes'] == (cursor|1) and routine['result_bytes'] == spec['result_bytes'],
                    'Process call shape changed: '+name)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args = parser.parse_args()
    write(ROOT/'lib/dos/process-types.inc',public_types(),args.check)
    write(ROOT/'lib/dos/processstate.act',state_source(),args.check)
