#!/usr/bin/env python3
"""Fixed shared timer state in the existing upper Task arena."""
import argparse
import json
from pathlib import Path
from generate_memory import ROOT, require
from generate_heap import write

ABI = json.loads((ROOT/'abi/platform-timer.json').read_text())
HEADER = '; Generated by tools/generate_platform_timer.py; do not edit.\n'


def assembly():
    a = ABI
    require(a['schema_version'] == 1 and a['state_bytes'] == 32,
            'Invalid shared timer state')
    console = json.loads((ROOT/'abi/console.json').read_text())['storage']
    require(a['state_offset'] >= console['keymap_offset']+128
            and a['state_offset']+a['state_bytes'] <= 0x1000,
            'Timer overlaps console tables or native code')
    return (HEADER+f'TIMER_STATE = T_BASE+${a["state_offset"]:04x}\n'
            + ''.join(f'{k} = TIMER_STATE+{v}\n' for k, v in a['fields'].items())
            + f'TIMER_DIVISOR = {a["divisor"]}\nTIMER_AUDCTL = ${a["audctl"]:02x}\n')


def generate(output, base, memory):
    require((ROOT/'platform/altirraos/platform-timer.inc').read_text() == assembly(),
            'Stale shared timer layout')
    memory['timer_storage'] = dict(BASE=base+ABI['state_offset'], BYTES=ABI['state_bytes'])
    write(Path(output)/'timer-storage-action.inc', HEADER+''.join(
        f'CONST {k}=${base+ABI["state_offset"]+v:x}\n' for k, v in ABI['fields'].items()), False)


if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--check', action='store_true')
    args = p.parse_args()
    write(ROOT/'platform/altirraos/platform-timer.inc', assembly(), args.check)
