#!/usr/bin/env python3
"""Generate the ordinary display lease ABI, shared by native and C adapters."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ABI = json.loads((ROOT/'abi/display.json').read_text())


def files():
    constants = {'LEASE_BYTES': ABI['lease_bytes'], **ABI['errors'], **ABI['states'], **ABI['kinds']}
    native = '; Generated by tools/generate_display.py; do not edit.\n'
    native += '\n'.join(f'PUBLIC CONST {k}={v}' for k,v in constants.items())+'\n'
    native += '''PUBLIC TYPE Lease=[
  EXEC.TaskLease owner
  LONGCARD generation
  BYTE kind,state
  CARD reserved
]
'''
    header = '''/* Generated by tools/generate_display.py; do not edit. */
#ifndef EXEC_DISPLAY_H
#define EXEC_DISPLAY_H
#include <exec/tasklease.h>
'''
    header += '\n'.join(f'#define DISPLAY_{k} {v}' for k,v in constants.items())+'\n'
    header += '''struct DisplayLease {
    struct TaskLease owner;
    ULONG generation;
    UBYTE kind, state;
    UWORD reserved;
};
UWORD DisplayAcquire(struct DisplayLease *lease, UWORD kind);
UWORD DisplayActivate(struct DisplayLease *lease);
UWORD DisplayCheck(struct DisplayLease *lease);
UWORD DisplayBeginRelease(struct DisplayLease *lease);
UWORD DisplayRelease(struct DisplayLease *lease);
UWORD DisplayFault(struct DisplayLease *lease);
UWORD DisplayBaseline(void);
UWORD DisplayTicks(void);
void DisplayResetRequired(void);
#endif
'''
    layout = '#include <exec/display.h>\n__attribute__((section("exec_layout")))\nconst unsigned short __exec_layout[] = {\n'
    layout += '    sizeof(struct DisplayLease),\n'
    layout += ''.join(f'    offsetof(struct DisplayLease, {name}),\n' for name in ABI['fields'])
    layout += '};\n'
    return {ROOT/'lib/display/display-types.inc':native,
            ROOT/'c/include/exec/display.h':header,
            ROOT/'c/calypsi/display-layout.c':layout}


def expected_layout():
    return [('DisplayLease size',ABI['lease_bytes']),
            *((f'DisplayLease {k}',v) for k,v in ABI['fields'].items())]


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args = parser.parse_args()
    for path,content in files().items():
        if args.check:
            if not path.exists() or path.read_text()!=content:
                raise SystemExit('Stale display ABI: '+str(path))
        else:
            path.write_text(content)
