#!/usr/bin/env python3
"""Private supervisor/application records shared by Action! and Calypsi."""
import argparse
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
DEST=ROOT/'ports/gem4xe/interactive'
ABI=ROOT/'abi/gem-interactive.json'

def expected_layout():
    return [(expr,value) for name,r in json.loads(ABI.read_text())['records'].items()
            for expr,value in [(f'sizeof(struct Ui{name})',r['size'])]+
            [(f'offsetof(struct Ui{name}, {f})',o) for f,t,o,n in r['fields']]]

def files():
    abi=json.loads(ABI.read_text())
    h=['/* Generated by tools/generate_gem_interactive.py. */','#ifndef UI_ABI_H','#define UI_ABI_H',
       '#include <proto/exec.h>',f'#define UI_VERSION {abi["version"]}']
    a=['; Generated by tools/generate_gem_interactive.py.', 'MODULE GEMCONTROL', 'USE EXEC',
       f'PUBLIC CONST VERSION={abi["version"]}']
    ct={'Message':'struct Message','Lease':'struct TaskLease','u16':'UWORD','u32':'ULONG','u8':'UBYTE',
        'Task':'struct Task EXEC_PTR *','Port':'struct MsgPort EXEC_PTR *'}
    at={'Message':'EXEC.Message','Lease':'EXEC.TaskLease','u16':'CARD','u32':'LONGCARD','u8':'BYTE',
        'Task':'ADDRESS','Port':'ADDRESS'}
    for k,v in abi['commands'].items():
        h.append(f'#define UI_{k} {v}'); a.append(f'PUBLIC CONST CMD_{k}={v}')
    for name,r in abi['records'].items():
        h.extend([f'#define UI_{name.upper()}_BYTES {r["size"]}',f'struct Ui{name} {{'])
        a.append(f'PUBLIC TYPE {name}=[')
        offset=0
        for f,t,o,n in r['fields']:
            if o!=offset: raise ValueError('Implicit padding')
            h.append(f'    {ct[t]} {f};'); a.append(f'  {at[t]} {f}')
            offset+=n
        if offset!=r['size']: raise ValueError('Wrong record extent')
        h.append('};'); a.append(']')
    h.extend(['#endif','']); a.extend(['ENDMODULE',''])
    probe=['/* Generated by tools/generate_gem_interactive.py. */','#include "ui-abi.h"',
           '__attribute__((section("exec_layout")))','const UWORD UiLayout[] = {']
    probe.extend(f'    {e},' for e,v in expected_layout()); probe.extend(['};',''])
    keymaps=json.loads((ROOT/'abi/console.json').read_text())['keymaps']
    keys='/* Generated from abi/console.json by tools/generate_gem_interactive.py. */\n'+''.join('static const UBYTE '+name+'Keys[64] = {'+','.join(map(str,values))+'};\n' for name,values in keymaps.items())
    return {DEST/'ui-keymap.h':keys,DEST/'ui-abi.h':'\n'.join(h),DEST/'gemcontrol.act':'\n'.join(a),DEST/'ui-layout.c':'\n'.join(probe)}

if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__); p.add_argument('--check',action='store_true'); args=p.parse_args()
    for path,content in files().items():
        if args.check:
            if not path.exists() or path.read_text()!=content: raise SystemExit('Stale '+str(path))
        else: path.write_text(content)
