#!/usr/bin/env python3
"""Private resident keyboard state; independent of console metadata."""
import argparse
import json
from pathlib import Path
from generate_console import WIDTHS
from generate_memory import ROOT, require
from generate_heap import write

ABI = json.loads((ROOT/'abi/input-native.json').read_text())
HEADER = '; Generated by tools/generate_input_native.py; do not edit.\n'


def definitions():
    widths = dict(WIDTHS)
    values = {}
    native = HEADER+'MODULE INPUTNATIVE\nUSE EXEC\n'
    for name, record in ABI['records'].items():
        end = 0
        native += 'PUBLIC TYPE '+name+'=[\n'
        for field, kind, offset in record['fields']:
            base, count = kind[:-1].split('[') if '[' in kind else (kind, 1)
            size, align = widths[base]
            end = (end+align-1)//align*align
            require(offset == end, 'Invalid input-native field: '+name+'.'+field)
            values[name.upper()+'_'+field.upper()] = offset
            native += f'  {base} ARRAY {field}({count})\n' if '[' in kind else f'  {base} {field}\n'
            end += size*int(count)
        require((end+1)//2*2 == record['size'], 'Invalid input-native size')
        widths[name] = (record['size'],record['alignment'])
        values[name.upper()+'_SIZE'] = record['size']
        native += ']\n'
    native += ''.join(f'PUBLIC CONST {k}=${v:x}\n' for k,v in values.items())
    return values, native+'ENDMODULE\n'


def generate(output, memory):
    from generate_tasks import storage
    values, _ = definitions()
    base = storage(memory)['BASE']
    state = ABI['storage']['state_offset']
    capture = ABI['storage']['capture_offset']
    require(state >= 0xa60 and state+values['STATE_SIZE'] <= capture
            and capture+values['CAPTURE_SIZE'] <= 0xe30, 'Input exceeds existing Task arena slack')
    memory['input_storage'] = dict(STATE=base+state, CAPTURE=base+capture,
        STATE_BYTES=values['STATE_SIZE'], CAPTURE_BYTES=values['CAPTURE_SIZE'])
    for suffix, prefix in [('inc', ''), ('act.inc', 'CONST ')]:
        write(Path(output)/('input-storage.'+suffix), HEADER+''.join(
            f'{prefix}IN_{k}=${v:x}\n' for k,v in memory['input_storage'].items()), False)


if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--check',action='store_true')
    a = p.parse_args()
    values, native = definitions()
    write(ROOT/'lib/input/inputnative.act', native, a.check)
    write(ROOT/'platform/altirraos/input-native.inc', HEADER+''.join(
        f'IN_{k}=${v:x}\n' for k,v in values.items()), a.check)
