#!/usr/bin/env python3
"""Ordinary VBXE bitmap-copy descriptors, shared by C and native libraries."""
import argparse
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
ABI=json.loads((ROOT/'abi/bitmap.json').read_text())


def files():
    header='''/* Generated by tools/generate_bitmap.py; do not edit. */
#ifndef EXEC_VBXE_COPY_H
#define EXEC_VBXE_COPY_H
#include <exec/types.h>
#define VBXE_COPY_VERSION 1
struct VbxeSurface { ULONG offset; UWORD pitch, width, height; };
struct VbxeCopy {
    struct VbxeSurface source, destination;
    UWORD sourceX, sourceY, destinationX, destinationY, width, height;
};
#endif
'''
    native='''; Generated by tools/generate_bitmap.py; do not edit.
PUBLIC TYPE BitmapSurface=[LONGCARD offset CARD pitch,width,height]
PUBLIC TYPE BitmapCopy=[
  BitmapSurface source,destination
  CARD sourceX,sourceY,destinationX,destinationY,width,height
]
'''
    layout='#include <hardware/vbxe-copy.h>\n__attribute__((section("exec_layout")))\nconst unsigned short __exec_layout[]={\n'
    for name,key in [('VbxeSurface','surface'),('VbxeCopy','copy')]:
        layout+=f'    sizeof(struct {name}),\n'
        layout+=''.join(f'    offsetof(struct {name}, {field}),\n' for field in ABI[key+'_fields'])
    layout+='};\n'
    return {ROOT/'c/include/hardware/vbxe-copy.h':header,
            ROOT/'lib/display/bitmap-types.inc':native,ROOT/'c/calypsi/bitmap-layout.c':layout}


def expected_layout():
    result=[]
    for name,key in [('VbxeSurface','surface'),('VbxeCopy','copy')]:
        result.append((name+' size',ABI[key+'_bytes']))
        result.extend((name+' '+field,offset) for field,offset in ABI[key+'_fields'].items())
    return result


if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');a=p.parse_args()
    for path,content in files().items():
        if a.check:
            if not path.exists() or path.read_text()!=content:raise SystemExit('Stale bitmap ABI: '+str(path))
        else:path.write_text(content)
