#!/usr/bin/env python3
"""Generate native desktop records for ordinary Exec messages, not a gateway."""
import argparse
import json
from pathlib import Path

from generate_layers import layout as layer_layout

ROOT = Path(__file__).resolve().parents[1]
ABI = json.loads((ROOT / 'abi/desktop.json').read_text())


def layout():
    sizes = {'BYTE': (1, 1), 'CARD': (2, 2), 'INT': (2, 2),
             'LONGCARD': (4, 2), 'EXEC.Message': (16, 2),
             'EXEC.MsgPort': (27, 1), 'EXEC.TaskLease': (12, 2),
             'EXECLISTS.List': (11, 1)}
    sizes.update({'LAYERTYPES.' + n: (r['size'], r['alignment'])
                  for n, r in layer_layout().items()})
    records = {}
    for name, fields in ABI['records'].items():
        offset, alignment, offsets = 0, 1, {}
        for field, kind, *counts in fields:
            count = ABI['constants'].get(counts[0], counts[0]) if counts else 1
            size, align = (3, 1) if kind.endswith(' POINTER') else sizes[kind]
            offset = (offset + align - 1) // align * align
            offsets[field] = offset
            offset += size * count
            alignment = max(alignment, align)
        size = (offset + alignment - 1) // alignment * alignment
        sizes[name] = size, alignment
        records[name] = dict(size=size, alignment=alignment, fields=offsets)
    return records


def files():
    lines = ['; Generated by tools/generate_desktop.py; do not edit.',
             'MODULE DESKTYPES', 'USE EXEC', 'USE EXECLISTS', 'USE LAYERTYPES',
             f'PUBLIC CONST VERSION={ABI["version"]}']
    lines += [f'PUBLIC CONST {n}={v}' for n, v in ABI['constants'].items()]
    vram = json.loads((ROOT/'platform/altirraos/vbxe-vram.json').read_text())
    slots = [r for r in vram['regions'] if r['name'].startswith('snapshot_')]
    assert len(slots) == ABI['constants']['SNAPSHOTS'] == 2
    for slot in slots:
        lines += [f'PUBLIC CONST {slot["name"].upper()}_BASE={slot["base"]}']
    assert all(r['capacity_bytes'] == 65536 for r in slots)
    lines += [f'PUBLIC CONST SNAPSHOT_BYTES={slots[0]["capacity_bytes"]}']
    for name, fields in ABI['records'].items():
        lines.append(f'PUBLIC TYPE {name}=[')
        for field, kind, *counts in fields:
            lines.append(f'  {kind}' + (' ARRAY' if counts else '') +
                         f' {field}' + (f'({counts[0]})' if counts else ''))
        lines.append(']')
    for name, record in layout().items():
        lines.append(f'PUBLIC CONST {name.upper()}_SIZE={record["size"]}')
        lines += [f'PUBLIC CONST {name.upper()}_OFFSET_{f.upper()}={offset}'
                  for f, offset in record['fields'].items()]
    header = ['/* Generated by tools/generate_desktop.py; do not edit. */',
              '#ifndef EXEC_VBXE_SNAPSHOTS_H', '#define EXEC_VBXE_SNAPSHOTS_H']
    for slot in slots:
        header += [f'#define DESKTOP_{slot["name"].upper()}_BASE {slot["base"]}UL']
    header += [f'#define DESKTOP_SNAPSHOT_BYTES {slots[0]["capacity_bytes"]}UL', '#endif', '']
    return {ROOT / 'lib/desktop/desktypes.act': '\n'.join(lines + ['ENDMODULE', '']),
            ROOT / 'c/include/hardware/vbxe-snapshots.h': '\n'.join(header)}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in files().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit('Stale desktop layout: ' + str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
