"""Embed the Exec repository identity and configured shell mount, without probing."""
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROFILE_NAMES = {1: '125k', 2: '19.2k', 3: '19.2k', 4: '57.6k'}


def identity(root=ROOT):
    def git(*args):
        return subprocess.check_output(['git', '-C', str(root), *args], text=True,
                                       stderr=subprocess.DEVNULL).strip()
    try:
        revision = git('rev-parse', 'HEAD')
        dirty = bool(git('status', '--porcelain', '--untracked-files=normal'))
        return dict(revision=revision, dirty=dirty,
                    display=revision[:7] + ('-dirty' if dirty else ''))
    except (OSError, subprocess.CalledProcessError):
        return dict(revision=None, dirty=False, display='unknown')


def generate(output, mounts, task_capacity, stack_checks=True, system_mount=None):
    build = identity()
    compiler = json.loads((ROOT/'toolchain/actionc.json').read_text())['revision']
    build.update(actionc_pin=compiler, task_capacity=task_capacity, stack_checks=stack_checks)
    mount = next((m for m in mounts if system_mount is not None and m['alias'].upper() == system_mount.upper()), None)
    build['mount'] = mount
    strings = dict(banner=f"Exec816 ({build['display']})\n\n",
                   slots=f'exec: {task_capacity} task slots\n',
                   stackChecks=f'exec: stack checks {"enabled" if stack_checks else "disabled"}\n',
                   version=f"Exec816 ({build['display']})\nactionc pin: {compiler[:7]}\n")
    if mount:
        strings.update(sioReady=' ready, '+PROFILE_NAMES[mount['profile']]+' profile\n',
                       mountStart='SYS: mounting...\n')
    else:
        strings.update(sioReady='', mountStart='SYS: no system volume configured\n')
    build['strings'] = strings
    text = '; Generated by tools/generate_build_info.py; do not edit.\nMODULE EXECBUILD\n'
    for name, value in strings.items():
        text += f'PUBLIC BYTE ARRAY {name}=['+' '.join(map(str, value.encode('ascii')+b'\0'))+']\n'
    text += 'ENDMODULE\n'
    (Path(output)/'execbuild.act').write_text(text)
    (Path(output)/'exec-build.json').write_text(json.dumps(build, indent=2)+'\n')
    return build
