#!/usr/bin/env python3
"""Generate shared Exec gateway/record constants; --check rejects stale files."""
from adapter_state import addresses, direct_pages, stack_addresses, resident_addresses, hosted_config, diagnostic_addresses
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generate():
    abi = json.loads((ROOT / "abi/exec816-v1.json").read_text())
    constants = {"E816_VERSION": abi["version"], "E816_COP": abi["cop_signature"]}
    for group, prefix in (("services", "SERVICE"), ("errors", "ERROR"), ("task_states", "STATE")):
        constants.update({f"E816_{prefix}_{key}": value for key, value in abi[group].items()})
    constants.update({f"E816_{key}": value for key, value in addresses().items()})
    constants.update({f"E816_{key}": value for key, value in direct_pages().items()})
    constants.update({f"E816_{key}": value for key, value in stack_addresses().items()})
    constants.update({f"E816_{key}": value for key, value in resident_addresses().items()})
    constants.update({f"E816_{key}": value for key, value in diagnostic_addresses().items()})
    constants.update({f"E816_FRAME_{key.upper()}": value for key, value in abi["compiler_frame"].items()})
    cursor = 0
    for field in abi["task_record"]["fields"]:
        width = {"BYTE": 1, "CARD": 2}[field["type"]]
        cursor = (cursor+width-1)//width*width
        if field["offset"] != cursor:
            raise ValueError(f"Incorrect native record offset: {field['name']}")
        constants[f"E816_TCB_{field['name'].upper()}"] = cursor
        cursor += width
    if cursor != abi["task_record"]["size"]:
        raise ValueError("Incorrect native record size")
    constants["E816_TCB_SIZE"] = cursor
    assembly = "; Generated by tools/generate_exec_abi.py; do not edit.\n"
    assembly += "".join(f"{name} = ${value:04x}\n" for name, value in constants.items())
    action = "; Generated by tools/generate_exec_abi.py; do not edit.\n"
    action += "".join(f"CONST {name}=${value:04x}\n" for name, value in constants.items())
    action += "TYPE TaskRecord=[\n" + "".join(
        f"  {field['type']} {field['name']}\n" for field in abi["task_record"]["fields"]) + "]\n"
    return {ROOT / "platform/altirraos/exec-abi.inc": assembly,
            ROOT / "platform/altirraos/hosted.cfg": hosted_config(),
            ROOT / "lib/exec/exec-abi.inc": action,
            ROOT / "lib/exec/adapter-state.inc": "; Generated by tools/generate_exec_abi.py; do not edit.\n" +
                "".join(f"CONST ASTATE_{name}=${value:04x}\n" for name,value in addresses().items())}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in generate().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Stale generated ABI file: {path}")
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
