#!/usr/bin/env python3
"""Generate the resident VBXE notification mailbox, within Task metadata."""
import argparse
import json
from pathlib import Path
from generate_memory import ROOT, require
from generate_heap import write

ABI=json.loads((ROOT/'abi/blitter.json').read_text())


def assembly():
    require(ABI['version']==1 and ABI['state_bytes']==64,'Invalid blitter mailbox')
    return ('; Generated by tools/generate_blitter.py; do not edit.\n'+
            ''.join(f'BV_{k} = T_BLITTER_STATE+{v}\n' for k,v in ABI['fields'].items())+
            ''.join(f'BV_{k} = {v}\n' for k,v in ABI['states'].items())+
            f'BV_COMMAND = ${ABI["command_address"]:x}\n')


if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--check',action='store_true')
    write(ROOT/'platform/altirraos/blitter.inc',assembly(),p.parse_args().check)
