#!/usr/bin/env python3
"""Generate the ordinary input records shared by Action!, assembly and C."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ABI = json.loads((ROOT/'abi/input.json').read_text())
TYPES = {'u8': ('BYTE', 'UBYTE', 1), 'u16': ('CARD', 'UWORD', 2),
         'i16': ('INT', 'WORD', 2), 'u32': ('LONGCARD', 'ULONG', 4),
         'TaskLease': ('EXEC.TaskLease', 'struct TaskLease', 12)}
PROTOTYPES = '''/* Acquire/Release validate registration lifetime. Keep the original lease
 * and signal live until successful Release; only its owner may Take/Release.
 * Ordinary operations trust that contract and writable, aligned, bank-contained output
 * storage in production. Full per-use audits require --input-diagnostics.
 * Output buffers are borrowed only for the call; EMPTY leaves all bytes intact.
 * Shared Pending/route users must stop before owner Release. C huge-pointer
 * shape checks always precede narrowing. Dynamic route and queue checks remain.
 */
UWORD InputAcquire(struct InputLease *lease, const struct InputConfig *config);
UWORD InputCreateRoute(struct InputLease *lease, UWORD flags, ULONG *tag);
UWORD InputPublishRoute(struct InputLease *lease, ULONG tag);
UWORD InputRetireRoute(struct InputLease *lease, ULONG tag);
UWORD InputDiscard(struct InputLease *lease, ULONG tag);
UWORD InputPending(struct InputLease *lease, UWORD *mask);
UWORD InputTake(struct InputLease *lease, struct InputEvent *event);
UWORD InputRelease(struct InputLease *lease);
'''


def validate(abi):
    if abi['version'] != 4 or abi['alignment'] != 2:
        raise ValueError('Unsupported input record version/alignment')
    for name, record in abi['records'].items():
        end = 0
        names = set()
        for field, kind, offset in record['fields']:
            size = TYPES[kind][2]
            aligned = (end+min(size, 2)-1)//min(size, 2)*min(size, 2)
            if field in names or offset != aligned:
                raise ValueError('Invalid input field: '+name+'.'+field)
            names.add(field)
            end = offset+size
        if (end+1)//2*2 != record['bytes']:
            raise ValueError('Invalid input record size: '+name)


def expected_layout(abi=ABI):
    validate(abi)
    return [(label, value) for name, record in abi['records'].items()
            for label, value in [(f'Input{name} size', record['bytes']),
                *((f'Input{name} {field}', offset) for field, _, offset in record['fields'])]]


def files(abi=ABI):
    validate(abi)
    constants = {'VERSION': abi['version'], **abi['constants'],
                 **{name.upper()+'_BYTES': r['bytes'] for name, r in abi['records'].items()}}
    native = '; Generated by tools/generate_input.py; do not edit.\n'
    native += ''.join(f'PUBLIC CONST {name}={value}\n' for name, value in constants.items())
    assembly = '; Generated by tools/generate_input.py; do not edit.\n'
    assembly += ''.join(f'INPUT_{name} = {value}\n' for name, value in constants.items())
    header = '''/* Generated by tools/generate_input.py; MIT public interface. */
#ifndef EXEC_INPUT_H
#define EXEC_INPUT_H
#include <exec/tasklease.h>
'''
    header += ''.join(f'#define INPUT_{name} {value}\n' for name, value in constants.items())
    layout = '#include <exec/input.h>\n__attribute__((section("exec_layout")))\nconst unsigned short __exec_layout[] = {\n'
    for name, record in abi['records'].items():
        native += f'PUBLIC TYPE {name}=[\n'
        header += f'struct Input{name} {{\n'
        layout += f'    sizeof(struct Input{name}),\n'
        for field, kind, offset in record['fields']:
            native += f'  {TYPES[kind][0]} {field}\n'
            header += f'    {TYPES[kind][1]} {field};\n'
            layout += f'    offsetof(struct Input{name}, {field}),\n'
            assembly += f'INPUT_{name.upper()}_{field.upper()} = {offset}\n'
        native += ']\n'
        header += '};\n'
    header += PROTOTYPES+'#endif\n'
    layout += '};\n'
    return {ROOT/'lib/input/input-types.inc': native,
            ROOT/'platform/altirraos/input.inc': assembly,
            ROOT/'c/include/exec/input.h': header,
            ROOT/'c/calypsi/input-layout.c': layout}


if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--check', action='store_true')
    args = p.parse_args()
    for path, content in files().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit('Stale input ABI: '+str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
