#!/usr/bin/env python3
"""One native widget layout for Action!, Calypsi and host fixtures."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ABI = json.loads((ROOT/'abi/widgets.json').read_text())


def layout():
    sizes = {'BYTE': (1, 1), 'CARD': (2, 2), 'INT': (2, 2), 'LONGCARD': (4, 2)}
    records = {}
    for name, fields in ABI['records'].items():
        offset, align, offsets = 0, 1, {}
        for field, kind, *counts in fields:
            size, alignment = sizes[kind]
            count = ABI['constants'].get(counts[0], counts[0]) if counts else 1
            offset = (offset+alignment-1)//alignment*alignment
            offsets[field] = offset
            offset += size*count
            align = max(align, alignment)
        size = (offset+align-1)//align*align
        sizes[name] = size, align
        records[name] = dict(size=size, alignment=align, fields=offsets)
    return records


def expected_layout():
    return [(name+' size', r['size']) for name, r in layout().items()] + [
        (name+'.'+field, offset) for name, r in layout().items()
        for field, offset in r['fields'].items()]


def files():
    act = ['; Generated by tools/generate_widgets.py.', 'MODULE WIDGETTYPES']
    hdr = ['/* Generated by tools/generate_widgets.py. MIT public interface. */',
           '#ifndef EXEC_WIDGET_TYPES_H', '#define EXEC_WIDGET_TYPES_H',
           '#include <stdint.h>', '#pragma pack(push, 2)']
    ctypes = {'BYTE':'uint8_t', 'CARD':'uint16_t', 'INT':'int16_t', 'LONGCARD':'uint32_t'}
    for name, value in ABI['constants'].items():
        act.append(f'PUBLIC CONST {name}={value}')
        hdr.append(f'#define WIDGET_{name} {value}')
    for name, fields in ABI['records'].items():
        act.append(f'PUBLIC TYPE {name}=[')
        hdr.append(f'struct Widget{name} {{')
        for field, kind, *counts in fields:
            count = counts[0] if counts else None
            act.append(f'  {kind}'+(' ARRAY' if counts else '')+f' {field}'+(f'({count})' if counts else ''))
            ctype = ctypes.get(kind, 'struct Widget'+kind)
            hdr.append(f'    {ctype} {field}'+(f'[WIDGET_{count}]' if counts else '')+';')
        act.append(']'); hdr.append('};')
    for name, record in layout().items():
        act.append(f'PUBLIC CONST {name.upper()}_SIZE={record["size"]}')
        hdr.append(f'#define WIDGET_{name.upper()}_SIZE {record["size"]}')
        act += [f'PUBLIC CONST {name.upper()}_OFFSET_{f.upper()}={o}' for f,o in record['fields'].items()]
    probe = ['/* Generated emitted-layout probe. */', '#include <stddef.h>',
             '#include "widget-types.h"', '__attribute__((section("exec_layout"))) const unsigned short __exec_layout[] = {']
    probe += [f'    sizeof(struct Widget{n}),' for n in layout()]
    probe += [f'    offsetof(struct Widget{n}, {f}),' for n,r in layout().items() for f in r['fields']]
    probe += ['};', '']
    return {ROOT/'lib/widgets/widgettypes.act':'\n'.join(act+['ENDMODULE','']),
            ROOT/'c/include/exec/widget-types.h':'\n'.join(hdr+['#pragma pack(pop)', '#endif','']),
            ROOT/'ports/gem4xe/aes/widget-layout.c':'\n'.join(probe).replace('"widget-types.h"','<exec/widget-types.h>')}


if __name__ == '__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');a=p.parse_args()
    for path,content in files().items():
        if a.check:
            if not path.exists() or path.read_text()!=content:raise SystemExit('Stale widgets: '+str(path))
        else:
            path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content)
