#!/usr/bin/env python3
"""Private ordinary-call packet; no public kernel or device ABI."""
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
ABI=json.loads((ROOT/'abi/console-bitmap.json').read_text())
def files():
    ops=ABI['operations']
    c='/* Generated by tools/generate_console_bitmap.py. */\n#ifndef EXEC_CONSOLE_BITMAP_H\n#define EXEC_CONSOLE_BITMAP_H\n#include <hardware/vbxe-copy.h>\n'
    c+='struct ConsoleBitmapPacket { UWORD operation,status; ULONG text; UWORD x,y,width,height,foreground,background; struct VbxeCopy copy; ULONG token; };\n'
    c+=''.join(f'#define CON_BITMAP_{k} {v}\n' for k,v in ops.items())+'#endif\n'
    a='; Generated by tools/generate_console_bitmap.py.\nPUBLIC TYPE Packet=[\n  CARD operation,status\n  LONGCARD text\n  CARD x,y,width,height,foreground,background\n  DISPLAY.BitmapCopy copy\n  LONGCARD token\n]\n'
    a+='PUBLIC TYPE Binding=[ADDRESS entry BYTE POINTER packet BYTE enabled,failed]\n'
    a+=''.join(f'PUBLIC CONST OP_{k}={v}\n' for k,v in ops.items())
    layout='#include <hardware/console-bitmap.h>\n__attribute__((section("exec_layout"))) const unsigned short __exec_layout[]={\nsizeof(struct ConsoleBitmapPacket),\n'
    layout+=''.join(f'offsetof(struct ConsoleBitmapPacket,{f}),\n' for f in ABI['fields'])+'};\n'
    return {ROOT/'c/include/hardware/console-bitmap.h':c,ROOT/'lib/console/console-bitmap-types.inc':a,ROOT/'c/calypsi/console-bitmap-layout.c':layout}
def expected_layout():
    return [('packet size',ABI['packet_bytes']),*ABI['fields'].items()]
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');a=p.parse_args()
    for path,content in files().items():
        if a.check:
            if not path.exists() or path.read_text()!=content:raise SystemExit('Stale bitmap packet: '+str(path))
        else:path.write_text(content)
