#!/usr/bin/env python3
"""Generate the desktop's integer curve and explicit build profile."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = json.loads((ROOT/'config/mouse.json').read_text())
INPUT = json.loads((ROOT/'abi/input-native.json').read_text())
PROFILES = {'off': 0, 'mild': 1}
HEADER = '; Generated by tools/generate_mouse_acceleration.py; do not edit.\n'


def gains():
    assert CONFIG['version'] == 1 and CONFIG['fraction_bits'] == 2
    assert CONFIG['default_profile'] in PROFILES
    table = [CONFIG['slow_gain_quarters']]*64
    for diagonal in (0, 1):
        numerator = CONFIG['diagonal_speed_numerator'] if diagonal else 1
        denominator = CONFIG['diagonal_speed_denominator'] if diagonal else 1
        for i, age in enumerate(INPUT['motion_interval_upper_bounds']):
            table[diagonal*32+i] = next((b['gain_quarters'] for b in CONFIG['bands']
                if age*denominator <= b['maximum_age']*numerator), CONFIG['slow_gain_quarters'])
    assert set(table) <= {4, 6, 8, 12, 16}
    return table


def configuration(profile=None):
    profile = CONFIG['default_profile'] if profile is None else profile
    if profile not in PROFILES:
        raise ValueError('Unknown desktop mouse profile: '+str(profile))
    return HEADER+'MODULE DESKMOUSECONFIG\n'+''.join(
        f'PUBLIC CONST {name.upper()}={value}\n' for name,value in PROFILES.items())+f'PUBLIC CONST DEFAULT={PROFILES[profile]}\nENDMODULE\n'


def metadata(profile=None):
    profile = CONFIG['default_profile'] if profile is None else profile
    configuration(profile)
    return dict(profile=profile, coordinates='relative-pixel-clamp', clock='PAL-VCOUNT-2-scanlines',
                parameters=CONFIG, gain_table_sha256=hashlib.sha256(bytes(gains())).hexdigest(),
                interval_upper_bounds=INPUT['motion_interval_upper_bounds'],
                source_inputs={name: hashlib.sha256((ROOT/name).read_bytes()).hexdigest() for name in
                    ('config/mouse.json','abi/input-native.json','tools/generate_mouse_acceleration.py',
                     'lib/desktop/deskmouse.act','lib/desktop/mouse-gains.inc','lib/desktop/deskinput.act')})


def files():
    return {ROOT/'lib/desktop/deskmouseconfig.act': configuration(),
            ROOT/'lib/desktop/mouse-gains.inc': HEADER+'BYTE ARRAY mouseGains=[\n'+
            '\n'.join('  '+' '.join(map(str,gains()[i:i+16])) for i in range(0,64,16))+'\n]\n'}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, source in files().items():
        if args.check:
            if path.read_text() != source:
                raise SystemExit('Stale mouse profile: '+str(path))
        else:
            path.write_text(source)
